### ISSUE TITLE
after npm start error. can not run.

### ISSUE THREAD

**Issue by zhangpengcool** [havfo/multiparty-meeting#103]

**Comment by havfo** [comment]
Please describe the problem in more detail. This is impossible to solve as is.

**Comment by dekins** [comment]
➜  server git:(develop) npm start

> multiparty-meeting-server@3.0.0 start /Users/dekins/Documents/labs/multiparty-meeting/server
> node server.js

- process.env.DEBUG: undefined
- config.mediasoup.logLevel: warn
- config.mediasoup.logTags: [ 'info', 'ice', 'dtls', 'rtp', 'srtp', 'rtcp', 'rbe', 'rtx' ]

can not run

**Comment by havfo** [comment]
I see no unusual output here, are you sure it is not running? Have you tried the docker version?

**Comment by so010** [comment]
Repuduced this at develop branch, which is default.
As a workaround, checkout master branch

**Comment by so010** [comment]
Correction, since develop and master are pointing to the same location and I have just installed this from master at a different machine it be be something dependency related. Will check ...

**Comment by so010** [comment]
Check your server/config/config.js last section 
               webRtcTransport :
                {
                        listenIps :
                        [
                                { ip: '1.2.3.4', announcedIp: null }
ip should be your servers ip address

**Comment by misi** [comment]
OIDC discovery needs a timeout. Sorry..
