### ISSUE TITLE
PictureChange only works in lobby

### ISSUE THREAD

**Issue by misi** [havfo/multiparty-meeting#110]
In develop branch, after I join the meeting without auth, and after it if I login the my user avatar picture don't change, and I do not receive notification about it, 
but I can see that from my side that I have the new picture and a 'changePicture' is sent out to server.

It works perfectly only if I log in in from the lobby.

**Comment by misi** [comment]
https://github.com/havfo/multiparty-meeting/blob/69677e49723d34b3c2ed8cd92ee9aae9b06a0e45/server/lib/Room.js#L381

**Comment by havfo** [comment]
Fixed in `develop`
