### ISSUE TITLE
Fix filmstrip

### ISSUE THREAD

**Issue by havfo** [havfo/multiparty-meeting#115]
Filmstrip is buggy when resizing and in general feels broken.

**Comment by so010** [comment]
Transparency for speaker is not looking right

**Comment by havfo** [comment]
Is now almost fixed. Need to fix buttons inside filmstrip videos somehow.

**Comment by misi** [comment]
Transparency for active speaker is still there check https://mm-dev.lab.vvc.niif.hu with 2 peers in filmstrip

**Comment by havfo** [comment]
@misi That was added on purpose at one point, but I guess it is better without it. It was added to show which one is in the active speaker view.

**Comment by misi** [comment]
@havfo I want to state that we need this highlight function for active speaker,  but we need to take care if background is not black then it is not as nice as it should be..
