### ISSUE TITLE
meeting locked + network disconnetct/reconnect

### ISSUE THREAD

**Issue by misi** [havfo/multiparty-meeting#128]
A teacher told me that he was dropped out, from a VC, and couldn't connect back. 
Student's waited waited for the teacher reconnect, but teacher couldn't reconnect because room was locked... So room is not empty.
We need to address such events. Any ideas?

**Comment by havfo** [comment]
This should now be fixed for reconnects.

**Comment by misi** [comment]
It is addressed in admin and moderator roles almost. We only need to allow room lock to moderator if there is an operator in the room.

**Comment by Astagor** [comment]
Or allow moderator to bypass lock in config.js by changing BYPASS_ROOM_LOCK?

**Comment by so010** [comment]
As Håvar said this case should be solved by reconnecting with session-cookie. Since we have no room ownership / database backend in place yet, we can't just allow all moderators to access locked rooms.

**Comment by misi** [comment]
I will close the issue and we will discuss internally how to solve the remaining issue.

My idea is to get mappin of user and room from AAI or DB, and and allow moderator to override  room lock if it's own room is locked.
