### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#131]
I have a problem on building on a machine
Ubuntu 18.04.3
Node version v10.19.0
NPM version 6.13.4

in the APP folder
npm install
npm run build

are both successful, but then in the server folder
npm install
fails.

I get the error:

Error: you need to install gyp in deps/gyp first, run:
  ./scripts/get-dep.sh gyp
Makefile:23: recipe for target 'default' failed
make: *** [default] Error 42
make: Leaving directory '/var/www/test/multiparty-meeting/server/node_modules/mediasoup/worker'

What is interesting on a second machine with the same configuration (OS and Node), the build does not fail.

I'm lost.

**Comment by havfo** [comment]
If you haven't already, delete the `node_modules` folder in `server` and try `npm install` again.

**Comment by havfo** [comment]
And make sure you have the debian/ubuntu package `build-essential` installed.

**Comment by Astagor** [comment]
Hi thanks for the answers. I got the build-essential installed.
I have solved the problem by removing node from the machine and cleared all leftover files and folders from node. Then a fresh node install and it works.
