### ISSUE TITLE
File sharing not working

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#132]
Hi,

I have a problem with the file sharing, sometimes it works but most file uploads fail. 
In Chrome console I see:

index.js:60 WebSocket connection to 'wss://tracker.fastcast.nz/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

index.js:60 WebSocket connection to 'wss://tracker.openwebtorrent.com/' failed: Error during WebSocket handshake: Unexpected response code: 522

index.js:60 WebSocket connection to 'wss://tracker.btorrent.xyz/' failed: Error during WebSocket handshake: Unexpected response code: 500

It seems that I cannot connect to any f the torrent web sockets. Do I have to configure something?

Please help.

BR,

Piotr

**Comment by misi** [comment]
Can you add to dev console in application->local storage
`debug : *`
key value pair, and send a more detailed report..
Thanks for your cooperation!

**Comment by Astagor** [comment]
`engine.io-client:socket writing ping packet - expecting pong within 5000ms +22s
browser.js:183 engine.io-client:socket flushing 1 packets in socket +1ms
browser.js:183 engine.io-client:socket socket receive: type "pong", data "undefined" +29ms
browser.js:183 webtorrent [2d57573] seed +27s
browser.js:183 webtorrent [2d57573] add +1ms
browser.js:183 webtorrent:torrent [2d57573] [unknown infohash] new torrent +0ms
browser.js:183 webtorrent:torrent [2d57573] [ee9872c] got metadata +148ms
browser.js:183 webtorrent:torrent [2d57573] [ee9872c] select 0-10 (priority 0) +3ms
browser.js:183 webtorrent:torrent [2d57573] [ee9872c] on store +2ms
browser.js:183 bittorrent-tracker:client new client ee9872c3cba68b228b64a07a0b992a775efdc0fe +0ms
browser.js:183 bittorrent-tracker:websocket-tracker new websocket tracker wss://tracker.btorrent.xyz +0ms
browser.js:183 simple-websocket [59220cd] new websocket: {allowHalfOpen: false, url: "wss://tracker.btorrent.xyz"} +0ms
browser.js:183 bittorrent-tracker:websocket-tracker new websocket tracker wss://tracker.fastcast.nz +15ms
browser.js:183 simple-websocket [df3efbb] new websocket: {allowHalfOpen: false, url: "wss://tracker.fastcast.nz"} +7ms
browser.js:183 bittorrent-tracker:websocket-tracker new websocket tracker wss://tracker.openwebtorrent.com +17ms
browser.js:183 simple-websocket [9599724] new websocket: {allowHalfOpen: false, url: "wss://tracker.openwebtorrent.com"} +16ms
browser.js:183 bittorrent-tracker:client setInterval 900000 +47ms
browser.js:183 bittorrent-tracker:client send `start` {numwant: 50, uploaded: 0, downloaded: 167616, left: 0, event: "started"} +4ms
browser.js:183 webtorrent:torrent [2d57573] [ee9872c] file done: piotr.jpg +64ms
browser.js:183 webtorrent:torrent [2d57573] [ee9872c] torrent done: ee9872c3cba68b228b64a07a0b992a775efdc0fe +1ms
10.afc63315.chunk.js:2 [Violation] 'setTimeout' handler took 77ms
index.js:60 WebSocket connection to 'wss://tracker.fastcast.nz/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
c @ index.js:60
_openSocket @ websocket-tracker.js:179
u @ websocket-tracker.js:35
(anonymous) @ client.js:113
p @ client.js:85
_createTracker @ index.js:152
e.exports @ index.js:63
_startDiscovery @ torrent.js:317
_onStore @ torrent.js:624
_onMetadata @ torrent.js:517
_onListening @ torrent.js:285
_onParsedTorrent @ torrent.js:244
(anonymous) @ torrent.js:205
h.run @ browser.js:153
p @ browser.js:123
browser.js:183 simple-websocket [df3efbb] destroy (error: connection error to wss://tracker.fastcast.nz) +67ms
browser.js:183 bittorrent-tracker:websocket-tracker reconnecting socket in 120540 ms +72ms
browser.js:183 webtorrent [2d57573] on seed +311ms
common.js:114 multiparty-meeting:RoomClient sendFile() [magnetUri: "magnet:?xt=urn:btih:ee9872c3cba68b228b64a07a0b992a775efdc0fe&dn=piotr.jpg&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com"] +25s
browser.js:183 socket.io-client:socket emitting packet with ack id 8 +25s
browser.js:183 socket.io-client:manager writing packet {"type":2,"data":["request",{"method":"sendFile","data":{"magnetUri":"magnet:?xt=urn:btih:ee9872c3cba68b228b64a07a0b992a775efdc0fe&dn=piotr.jpg&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com"}}],"options":{"compress":true},"id":8,"nsp":"/"} +25s
browser.js:133 socket.io-parser encoding packet {"type":2,"data":["request",{"method":"sendFile","data":{"magnetUri":"magnet:?xt=urn:btih:ee9872c3cba68b228b64a07a0b992a775efdc0fe&dn=piotr.jpg&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com"}}],"options":{"compress":true},"id":8,"nsp":"/"} +25s
browser.js:133 socket.io-parser encoded {"type":2,"data":["request",{"method":"sendFile","data":{"magnetUri":"magnet:?xt=urn:btih:ee9872c3cba68b228b64a07a0b992a775efdc0fe&dn=piotr.jpg&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com"}}],"options":{"compress":true},"id":8,"nsp":"/"} as 28["request",{"method":"sendFile","data":{"magnetUri":"magnet:?xt=urn:btih:ee9872c3cba68b228b64a07a0b992a775efdc0fe&dn=piotr.jpg&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com"}}] +1ms
browser.js:183 engine.io-client:socket flushing 1 packets in socket +2s
browser.js:183 engine.io-client:socket socket receive: type "message", data "38[]" +41ms
browser.js:133 socket.io-parser decoded 38[] as {"type":3,"nsp":"/","id":8,"data":[]} +47ms
browser.js:183 socket.io-client:socket calling ack 8 with [] +56ms
index.js:60 WebSocket connection to 'wss://tracker.btorrent.xyz/' failed: Error during WebSocket handshake: Unexpected response code: 500
c @ index.js:60
_openSocket @ websocket-tracker.js:179
u @ websocket-tracker.js:35
(anonymous) @ client.js:113
p @ client.js:85
_createTracker @ index.js:152
e.exports @ index.js:63
_startDiscovery @ torrent.js:317
_onStore @ torrent.js:624
_onMetadata @ torrent.js:517
_onListening @ torrent.js:285
_onParsedTorrent @ torrent.js:244
(anonymous) @ torrent.js:205
h.run @ browser.js:153
p @ browser.js:123
browser.js:183 simple-websocket [59220cd] destroy (error: connection error to wss://tracker.btorrent.xyz) +21s
browser.js:183 bittorrent-tracker:websocket-tracker reconnecting socket in 59336 ms +21s
browser.js:183 engine.io-client:socket writing ping packet - expecting pong within 5000ms +23s
browser.js:183 engine.io-client:socket flushing 1 packets in socket +5ms
browser.js:183 engine.io-client:socket socket receive: type "pong", data "undefined" +32ms`

**Comment by Astagor** [comment]
OK, some update. It seems that the upload itself was maybe ok, as when I press F5 and reload the room, the file appears, and I can press download. However then, the download also fails with the following log:

`webtorrent [2d57573] add +19s`

`browser.js:183 webtorrent:torrent [2d57573] [ee9872c] new torrent +0ms`

`browser.js:183 bittorrent-tracker:client new client ee9872c3cba68b228b64a07a0b992a775efdc0fe +0ms`

`browser.js:183 bittorrent-tracker:websocket-tracker new websocket tracker wss://tracker.btorrent.xyz +0ms`

`browser.js:183 simple-websocket [f023acb] new websocket: {allowHalfOpen: false, url: "wss://tracker.btorrent.xyz"} +0ms`

`browser.js:183 bittorrent-tracker:websocket-tracker new websocket tracker wss://tracker.fastcast.nz +7ms`

`browser.js:183 simple-websocket [895453a] new websocket: {allowHalfOpen: false, url: "wss://tracker.fastcast.nz"} +4ms`

`browser.js:183 bittorrent-tracker:websocket-tracker new websocket tracker wss://tracker.openwebtorrent.com +7ms`

`browser.js:183 simple-websocket [c06ca9c] new websocket: {allowHalfOpen: false, url: "wss://tracker.openwebtorrent.com"} +7ms`

`browser.js:183 bittorrent-tracker:client setInterval 900000 +18ms`

`browser.js:183 bittorrent-tracker:client send `start` {numwant: 50, uploaded: 0, downloaded: 0, left: NaN, event: "started"} +13ms`

`index.js:60 WebSocket connection to 'wss://tracker.fastcast.nz/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED`

`c @ index.js:60`

`_openSocket @ websocket-tracker.js:179`

`u @ websocket-tracker.js:35`

`(anonymous) @ client.js:113`

`p @ client.js:85`

`_createTracker @ index.js:152`

`e.exports @ index.js:63`

`_startDiscovery @ torrent.js:317`

`_onListening @ torrent.js:288`

`_onParsedTorrent @ torrent.js:244`

`(anonymous) @ torrent.js:205`

`h.run @ browser.js:153`

`p @ browser.js:123`

`browser.js:183 simple-websocket [895453a] destroy (error: connection error to wss://tracker.fastcast.nz) +24ms`

`browser.js:183 bittorrent-tracker:websocket-tracker reconnecting socket in 126249 ms +33ms`

`browser.js:183 engine.io-client:socket writing ping packet - expecting pong within 5000ms +22s`

`browser.js:183 engine.io-client:socket flushing 1 packets in socket +0ms`

`browser.js:183 engine.io-client:socket socket receive: type "pong", data "undefined" +25ms`

`index.js:60 WebSocket connection to 'wss://tracker.btorrent.xyz/' failed: Error during WebSocket handshake: Unexpected response code: 522`

`c @ index.js:60`

`_openSocket @ websocket-tracker.js:179`

`u @ websocket-tracker.js:35`

`(anonymous) @ client.js:113`

`p @ client.js:85`

`_createTracker @ index.js:152`

`e.exports @ index.js:63`

`_startDiscovery @ torrent.js:317`

`_onListening @ torrent.js:288`

`_onParsedTorrent @ torrent.js:244`

`(anonymous) @ torrent.js:205`

`h.run @ browser.js:153`

`p @ browser.js:123`

`browser.js:183 simple-websocket [f023acb] destroy (error: connection error to wss://tracker.btorrent.xyz) +31s`

`browser.js:183 bittorrent-tracker:websocket-tracker reconnecting socket in 55062 ms +31s`

`index.js:60 WebSocket connection to 'wss://tracker.openwebtorrent.com/' failed: Error during WebSocket handshake: Unexpected response code: 522`

`c @ index.js:60`

`_openSocket @ websocket-tracker.js:179`

`u @ websocket-tracker.js:35`

`(anonymous) @ client.js:113`

`p @ client.js:85`

`_createTracker @ index.js:152`

`e.exports @ index.js:63`

`_startDiscovery @ torrent.js:317`

`_onListening @ torrent.js:288`

`_onParsedTorrent @ torrent.js:244`

`(anonymous) @ torrent.js:205`

`h.run @ browser.js:153`

`p @ browser.js:123`

`browser.js:183 simple-websocket [c06ca9c] destroy (error: connection error to wss://tracker.openwebtorrent.com) +204ms`

`browser.js:183 bittorrent-tracker:websocket-tracker reconnecting socket in 64914 ms +205ms`

`browser.js:183 engine.io-client:socket writing ping packet - expecting pong within 5000ms +25s`

`browser.js:183 engine.io-client:socket flushing 1 packets in socket +6ms`

`browser.js:183 engine.io-client:socket socket receive: type "pong", data "undefined" +27ms`

**Comment by misi** [comment]
Ok I think these are just. Ho w can I say. Cosmetic errors can't connect to all tracker. The issue is that the seeder don't get feedback see pending issue #124 . If you F5 and reload seeder then no body seed the file anymore... So try to use 2 browser tab and exepect that you will not get back any feedback on seeder side.. Only the second client will get notification that file is available.
Sorry about iAFAIU I see only the known issue #124

**Comment by havfo** [comment]
There was a bug in torrent-handling. The user that shared never got feedback that the share had started.
