### ISSUE TITLE
Mistake in German translation

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#139]
I found 2 mistakes in German translation
the is:
`23 "room.accessCodeOff": "Yugangskode deaktiviert",`
`35 "room.aboutToJoin": "Du bist dabei den Raum yu betreten",`

should be:
`23 "room.accessCodeOff": "Zugangscode deaktiviert",`
`35 "room.aboutToJoin": "Du bist dabei den Raum zu betreten",`

**Comment by so010** [comment]
Thanks

**Comment by Astagor** [comment]
My team is preparing an Italian translation, would you be interested in including it when we finish?

**Comment by havfo** [comment]
Absolutely!
