### ISSUE TITLE
Audio routing problem

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#148]
My users have sometimes strange audio issues. There are 3 sites connected:

User1: can hear User2 and User3
User2: can hear User1, but cannot hear User3
User3: can hear User1, but cannot hear User2 and additionally hears the delayed audio of User1

It seems as if User2 instead of sending their own audio to User3, re-sends the audio that he receives from User1.

**Comment by havfo** [comment]
This seems very weird, and should be impossible. Do you have any info on the browsers involved, and also, what codecs do you have activated on the server?

**Comment by Astagor** [comment]
Well audio was opus, video VP8, simulcast disabled.
Well User1 and User3 where on chrome, but I don't know on what browser User2 (who I think was causing the problem) was on.  They even reconnected and still the problem existed. Unfortunately, I cannot ask them about their browser, as they are external users.

**Comment by havfo** [comment]
Hmm...I am not sure how to diagnose this other than that you try to reproduce the issue and do some debugging to get some logs on what is happening...

We have not experienced this issue in any of our testing.

**Comment by Astagor** [comment]
OK, I will try. On Thursday we will be using the same instance for a conference between doctors from China and from Poland. I hope it will go smoothly.

**Comment by havfo** [comment]
Please let us know if there are any issues.

**Comment by Astagor** [comment]
OK, from the server logs
 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"

So is is the current FF on windows 10. I have the same on my system and never had experienced such problems. And it cannot be a Windows audio routing problem as then the audio from both User1 and User3 would be sent back.

**Comment by havfo** [comment]
Have you configured a working TURN server (preferably on port 443) for the clients?

**Comment by Astagor** [comment]
`urls : [
				'turn:ltc.turn.geant.org:3478?transport=tcp'
			],`
Yes and I'm using my credentials.

The version I'm using is from Sunday, so without the current changes to TURN configuration.

**Comment by so010** [comment]
We have changed a lot the last days. Checkout latest develop branch ( there are breaking config changes - begin from config.example.js in server and app folder )
There are especially some changes to TURN  there which should solve your problem.
NOTE: TURN config moved from app to server folder.  ( turnAPIKey / turnAPIURI is not needed test with backup turn )

**Comment by Astagor** [comment]
One more question, I'm still on the old config with credentials.
The TURN URL I use is 
`turn:ltc.turn.geant.org:3478?transport=tcp`

Now in one hospital 3478 is blocked. Is there a TURN server on 443?

**Comment by so010** [comment]
New config has only added functionality for the distributed geant turn service (turn.geant.org). Old way to configure is still possible but moved to server/config/config.js as backupTurnServers. If you have control over TURN server by yourself you can configure to 443 which is quite standard for webRTC.

**Comment by Astagor** [comment]
For now I have used 
`turn:ltc.turn.geant.org:443?transport=tcp`
and it works great.
During the weekend I will migrate to the version using the API to get the TURN servers.

I will continue to check if the audio routing problem happens again.

**Comment by christian-2** [comment]
Could this be an issue with VPN/bandwidth (esp. in combination with ssh/SOCKS, where TCP may be chosen for media transport in case of `enableTcp`)?

**Comment by havfo** [comment]
I can confirm that we have reproduced this issue with Firefox. Any Firefox user in a room can potentially ruin the experience for all others by echoing the other users. We are looking into any possible way to fix this.

**Comment by havfo** [comment]
Fix for this issue will land in Firefox 76 on May 5, ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1627313
