### ISSUE TITLE
cannot share screen with 4K resolution

### ISSUE THREAD

**Issue by tapionx** [havfo/multiparty-meeting#150]
when a user try to share a 3840 x 2160 screen, the participants of that room only see a black or grey square.
The resolution shown for that square (if you enable advanced settings) is 0x0

**Comment by havfo** [comment]
Could you please increase the `maxIncomingBitrate` on the server to something like `3000000` and try again?

**Comment by misi** [comment]
@tapionx  Can I close this issue, we didn't get answer from you.

**Comment by tapionx** [comment]
i cannot reproduce the issue, maybe it's solved with version 3.2.1.
I will open the issue again if I gather more info.
Thanks for your work!
