### ISSUE TITLE
Lobby info in bold

### ISSUE THREAD

**Issue by so010** [havfo/multiparty-meeting#154]
For waiting in the lobby: this info probably should be bold or header:
"The room is locked - hang on until somebody lets you in ..."

**Comment by cap19** [comment]
Thank you for all the enhancements to the platform. It's awesome! My 2 cents on this one...

Now, there is 6 different font sizes and types with very little text in this window. It looks fine but I think the new bold text and size is too loud.  Plus on a small mobile screen now the text does not properly. Just my personal opinion...
