### ISSUE TITLE
Please add Italian language to Master

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#156]
Like recommended I have moved from develop to master branch, but the Italian language is not merged into master. Please do.

**Comment by misi** [comment]
I will do it on Monday..

**Comment by misi** [comment]
It will be included in 3.2.1 release. That will be released according our actual plan tomorrow.

**Comment by havfo** [comment]
Fixed in b975b16dac5f90cec241f3c768e31357b6e658a7
