### ISSUE TITLE
End to end encryption

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#159]
Another question, a hospital has asked me how it is with the encryption. Are the streams encrypted and is it end to end?

**Comment by havfo** [comment]
The streams are not encrypted end-to-end. The mediaserver decodes the streams to be able to distribute them between the other participants in a meeting.

**Comment by misi** [comment]
Let me add that E2E can't scale because of the full mesh connection.
So you can only make very limited conferences with E2E. 
We used E2E encryption in knockplop. 
See:   https://vc.up2university.eu/
