### ISSUE TITLE
Firefox not working (development branch)

### ISSUE THREAD

**Issue by tobias231h** [havfo/multiparty-meeting#160]
Hi, I just wanted to note that Multiparty-Meeting (development branch) video 
is not working in Firefox.
No video of other users is shown.

**Comment by misi** [comment]
Which FF version ? OS version?

**Comment by Astagor** [comment]
I have extra changed to the develop branch to test. But on Windows 10 and FF 74 I have no problems, everything works like expected. On Android it works also.

**Comment by misi** [comment]
My experience is the same from Debian Linux 68.6.0esr

**Comment by Astagor** [comment]
Maybe you have not configured your turn server, as now it moved to server config.js and you have a restrictive firewall?

**Comment by tobias231h** [comment]
I think I just found the solution.
As you pointed out, I didn't configure a TURN server because I dont have a restricted firewall.

So I reverted the changes of commit 0600d1207b207e0b00e7f8129ab3944df653dc16 and that did the trick. 
Currently, `iceTransportPolicy` is set to `relay` if your browser is firefox. 
This setting enforces the use of a TURN-server, even if you don't specify one in the config.
You should probably check if `this._turnServers` is empty and only set `iceTransportPolicy `if a TURN-server was specified in the config.

**Comment by havfo** [comment]
Good point, will fix this.
