### ISSUE TITLE
Move audio codec option to app config

### ISSUE THREAD

**Issue by misi** [havfo/multiparty-meeting#162]
We should add exmaple config for VC use case and Musician.

**Comment by ClaudioAllocchio** [comment]
more in details, minimal controls which should be allowed inside app config:
- adjust/do not adjust automatically mic level
- enable/disable echo cancellation

further work should lead to a "music profile audio mode" button, which adjust Opus codec parameters in optimal setup for use when users are not "talking" but doing "music" (lesson for example).

**Comment by havfo** [comment]
Need to add following constraints to the audio:

`const constraints = {
  audio: {
    echoCancellation: false,
    noiseSuppression: false,
    autoGainControl: false,
  }
};`

**Comment by havfo** [comment]
How about an address parameter, `audioProcessing=false`?

**Comment by ClaudioAllocchio** [comment]
yes it may work! and we can name it n the user interface appropriately (enable music audio settings for example). with in case a more fine control of single parameters inside the "advanced settings" mode where you can control parameters one by one. I asked the networked music developers (LoLa, Ultragrid, JamKazam) also to have a look and provide suggestions.

**Comment by misi** [comment]
@havfo 
I agree with audioProcessing parameter option, 
but we should have a configurable/tunable default option too, 
so I think we should have anyway in app config the audio codec option as default for the server.

**Comment by ClaudioAllocchio** [comment]
yes Misi, it should be configurable, as audio settings for voice and other uses (music) are different, and advanced users should be able to do also some self tuning.

**Comment by so010** [comment]
I made this configurable as defaultAudio in app/config and added user controls for echoCancelation, autoGain, noiseSuppression. Additionally I made ptime for Opus codec to the minimum possible 2.5ms in order to minimize latency ( should be later configurable as well).

Please test in current development branch and soon on letsmeet.no

**Comment by fabiofarina** [comment]
Hello, here @GARR we're trying to deploy version 3.3 to use the new audio controls with some beta users selected by @ClaudioAllocchio . We cannot find the v.3.3 Docker image on Docker Hub.
What tag should we specify to have this version? Thanks

**Comment by havfo** [comment]
Use the dev tag to get latest develop.
