### ISSUE TITLE
Videoconference user/codec/bandwidth utilization performance 

### ISSUE THREAD

**Issue by erotavlas-turbo** [havfo/multiparty-meeting#163]
Hi,
I’m currently testing different platforms for videoconferencing. In particular, I’m comparing multiparty meeting, jitsi, bbb, hangouts, teams and other.
Do you have performance evaluation about the limits of multiparty meeting? Number of users per room? Users per server?
In particular, I’m comparing bandwidth requirements: for instance [hangouts](https://support.google.com/hangouts/answer/2944865?hl=en&visit_id=637198545124000077-2837229424&rd=2) has minimum of 300 kbit/s, [teams](https://docs.microsoft.com/en-US/microsoftteams/prepare-network) has a minimum of 500 kbit/s while jitsi and bbb are close to teams.
Hangout is using [VP9](https://developers.google.com/web/updates/2016/01/vp9-webrtc), teams [h.264](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/network-requirements) codec while jitsi and bbb VP8. VP9 is comparable to h.265 and one step ahead to both VP8 and h.264.
What are the codecs used by multiparty-meeting? Does multiparty-meeting allow to adjust video quality (LD, SD, HD)?
Thank you

**Comment by havfo** [comment]
Hi,

the limits vary based on usage of the room. The limits are tied to the number of active, non-muted, streams. We have cases of ~130 users in a single room that worked fine. The codec options are configurable in the server config, but beware that not all browsers support all codecs. The default one in the config is VP8.

As for users pr. server, a modern 8 core server is able to handle ~600 users. This again varies based on how big the individual rooms are, but this is a lower limit that holds true.

The bandwidth requirements are very configurable. You have several options for limiting this, both on client, and server.

The biggest impact on client upload bandwidth is in the: `maxIncomingBitrate`
This option sets the maximum bandwidth the client is allowed to send to the server. Apart from that, the mediastack (Mediasoup) uses transport BWE, that scales the traffic based on available bandwidth.

Regarding client download bandwidth, you can configure `lastN` that limits the amount of videos shown, and thus the amount of traffic.

If you want even better scaling, activate simulcast.

**Comment by erotavlas-turbo** [comment]
Thank you for your prompt response.
Is there any comparison similar to [this paper of 2018](https://uploads-ssl.webflow.com/5c6853c495409838d874a0d2/5cbed66cae2b88609106befa_IPTComm_2018_LoadTesting-12%5B23229%5D.pdf) which include mediasoup too? Unfortunately, it only include: jitsi, kurento, janus and medooze.

**Comment by so010** [comment]
This could be interesting https://webrtchacks.com/sfu-load-testing

**Comment by erotavlas-turbo** [comment]
> This could be interesting https://webrtchacks.com/sfu-load-testing

The article is written by the same group [Cosmo](https://www.cosmosoftware.io/) within few months of distance while the results are completely different for the same SFU. Which one is reliable?

**Comment by so010** [comment]
I think if you read there under "SFU improvements during testing" you get the general idea. And pointing to that I have to add that this is already over 17 months old so this will be a completely different situation today. At least mediasoup is written from scratch v2->v3 since then and it depends on a lot of set-up conditions (codecs used, codec-parameters, browser versions, network hardware/driver  serverside, simulcast / svc, ...)

**Comment by dorinmusteata** [comment]
Hi , as I can see in the docs 
https://github.com/havfo/multiparty-meeting/blob/master/HAproxy.md

Technically we can exceed the limit of 130 users in a room ? By deploying more instances with 8 core cpus, let’s say 6 servers , and achieve 780 users per room , “tehnically” , which mean we are horizontally scalling by use of redis as a central communication instance?

**Comment by havfo** [comment]
The room limit is still 130, but we have a branch that addresses this called `feat-server-scaling`. At the  moment every instance is able to handle ~600 users with 8 cores, but not in the same room yet.

**Comment by dorinmusteata** [comment]
So i've checked the `feat-server-scaling` branch , as i've seen `router.pipeToRouter` is used which means that the same instance power will be used. But will it be possible to scale users across multiple instances ? for example. instance1 where room1 has 100 users would we be able exceed room capacity by setting 30 users on instance2 where is room1 ?

**Comment by havfo** [comment]
We are also working on `feat-media-node` which separates the mediasoup handling to its own server. This will enable you to launch a number of media-nodes to scale out properly. The combination of these two branches is what you are after.

**Comment by dorinmusteata** [comment]
Thank you for the advice.

**Comment by varundabke** [comment]
What is the current status of feat-media-node & feat-server-scaling ?
Has feat-server-scaling already integrated to master?
I want to use one room ( large ) across multiple servers; is feat-media-node is usable state for prod environment?

Thanks for the wonderful work you have done!

**Comment by jmencak** [comment]
I was wondering about `feat-server-scaling` merging into master too.  I believe it is merged in the master and first release it had the functionality was the 3.3 release.  See: https://github.com/edumeet/edumeet/commit/5af3306 and `git log --graph --decorate --oneline`. Cannot comment about the rest.

**Comment by so010** [comment]
`feat-server-scaling` is merged `feat-media-node` is not.
So max room size multiplied by number of virtual cpu cores to
