### ISSUE TITLE
Login button shown although Logout should be sown

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#166]
Hi,
I have noticed some error in the function of the Login/Logout button.

After I log in with a user and enter a room, the Logout button  is show correctly.
Now when I exit and renter the room (or enter another room) I'm let in as I'm still authenticated, but instead of the Logout button the Login button is show. 

So after changing the room a logged in user has no possibility to logout from the UI.

**Comment by misi** [comment]
Please try the just release 3.2.1..

**Comment by Astagor** [comment]
Hmm, I'm using the current develop branch, with nothing to pull from git.

**Comment by Astagor** [comment]
I want to use the develop version in order to have all the Roles. I did more testing, but on the develop branch the problem persist.

**Comment by misi** [comment]
I need to check that all fixes are in develop too.
