### ISSUE TITLE
microphone voice activity gain control

### ISSUE THREAD

**Issue by nullaegy** [havfo/multiparty-meeting#167]
It would be awesome if we could limit how sensitive is the voice activation microphone is.
something like in [the discord preferences](https://i.imgur.com/xkp4Pvn.png): 

Even more awesome if you can control this on the main window without going to the settings.
maybe on the right side next to the mute audio/video/share icons.
[something like this.](https://i.imgur.com/9BWAUB7.png)

**Comment by so010** [comment]
IMHO user should at best not be confused with special controls. Hope we con solve this analyzing audio more by intelligently. (analyze SNR and if signal is high enough above noise - at the moment there is only an absolute threshold)

**Comment by nullaegy** [comment]
don't underestimate the users, a big portion of them like to see under the hood and tweak a bit of these and that to their liking. And on the other hand stock solutions not always best for everyone.

Discord has over 250 million users, and if they have it, I doubt that this feature is that a bad idea ;]

> IMHO user should at best not be confused with special controls.

**Comment by havfo** [comment]
Done in develop
