### ISSUE TITLE
FF 74 - windows 10 - Branch develop - no media streams

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#170]
On the current develop branch in FF 74, Win 10 the media streams are not being sent nor received. On Master it works.

**Comment by havfo** [comment]
Have you updated your config to have the turnserver config in server, not app?

**Comment by Astagor** [comment]
Yes the trun server is in the server config.
OK, I found out what was causing it. My TURN setup was:
 'turns:ltc.turn.geant.org:443?transport=tcp'
when I change it to 
 'turn:ltc.turn.geant.org:443?transport=tcp'

But as it runs on 443 I thought it should be TURNS and not TURN.

**Comment by havfo** [comment]
We are forcing TURN for Firefox because of issue #72 . To disable this you can remove the two following lines in RoomClient.js:
`iceTransportPolicy     : this._device.flag === 'firefox' && this._turnServers ? 'relay' : undefined,`

**Comment by Astagor** [comment]
OK, got it. I think I will recommend my users to use Chrome, except for iOS, as on iOS 13 I get a white screen in Chrome, but in Safari it works. I have disabled the compression like suggested in the issue with iOS, but it didn't help. Still Chrome shows white screen.

**Comment by havfo** [comment]
Sorry to say that at the moment, yes, it is preferable to use Chrome.
