### ISSUE TITLE
Project includes hard-coded tracker 

### ISSUE THREAD

**Issue by JanLuca** [havfo/multiparty-meeting#171]
In commit e56ff28b911621f6cb4e2e2ccd6d9b5fe3f7a453 there was a hard-coded tracker tracker.lab.vvc.niif.hu added to the project. Could you please remove the tracker or document this url and make it configurable?

**Comment by behrmann** [comment]
niif.hu seems to be something like the Hungarian HPC society and https://vvc.niif.hu/ and their video conference arm. Is this tracker simply a [wt-tracker](https://github.com/Novage/wt-tracker) instance (or similar)?

If so it would be great to self-host this aspect as well.

**Comment by so010** [comment]
We added this tracker in order to be not dependent from public trackers wich are hardcoded in webtorrent as well and yes it should be configurable.
