### ISSUE TITLE
Make the code run in Windows (with node 10.x dependency)

### ISSUE THREAD

**Issue by sabyasachi-basu-i** [havfo/multiparty-meeting#172]
Dear All,

I tried following the mentioned steps to make the code work in windows platform with node10.x dependency, however, it does not work. May you please try in case you can provide a guided step to make this work in windows.

Also, I tried running the app locally using a Ubuntu terminal available for windows. It fails in the attached error.

Regards,
Sabyasachi Basu
[192.168.10.7-1585977075601.log](https://github.com/havfo/multiparty-meeting/files/4430786/192.168.10.7-1585977075601.log)

**Comment by misi** [comment]
Unfortunately we don't have any experience to run it on windows. 

Sorry for the late reply.
We run it mostly on debian or alpine linux dists.
@sabyasachi-basu-i

**Comment by sabyasachi-basu-i** [comment]
hey @misi I agree with you. However, it does work with WSL perfectly. thank you for your response, I'll close the thread. I'm still trying to make it work in Windows. I'll keep you updated in case I can figure the dependencies out. Thanks for the help!

**Comment by misi** [comment]
Many thanks for your feedback!
