### ISSUE TITLE
Can not enter the room after start  the server and attain the room id

### ISSUE THREAD

**Issue by fengkouxiaozhu** [havfo/multiparty-meeting#174]
Sorry to bother you!
 When I run your multiparty-meeting demo on github, I met some difficulties.    as your guides,  when I finish the configurations.  no matter run in local or server mode, the demo can not  enter the room when I press the button. and the post request is directed to letsmeet.no. when i  install it on the local server, whether the multiparty-meeting server  address need to be changed to mine or not.    I really need your instruction!

  Thank you for your suggestions!

**Comment by havfo** [comment]
Hi, which branch are you testing. If `master`, have you det the `app/public/config/config.js:multipartyServer`?

**Comment by fengkouxiaozhu** [comment]
No, I keep it with letsmeet.no  address. but when i change my address.  i cannot enter the room in the last step.    The response code is 404

**Comment by havfo** [comment]
You will not be able to run it with letsmeet.no, that server is incompatible, you need your own. Go over your config for server and app to see if there is something you missed.

**Comment by havfo** [comment]
By the way, the preferred method of installation is with docker or ansible.

**Comment by fengkouxiaozhu** [comment]
Thanks very much!!!!   i will try to reinstall and re config it  today!

**Comment by fengkouxiaozhu** [comment]
What a pity!  I reinstall the multiparty-demo.  There is still the same problem.  Thanks u for your help! wait for your sugesstion!
![微信图片_20200407154325](https://user-images.githubusercontent.com/63183456/78643260-91136500-78e6-11ea-896c-86e9da68c3b8.jpg)

**Comment by fengkouxiaozhu** [comment]
> By the way, the preferred method of installation is with docker or ansible.

What a pity! I reinstall the multiparty-demo. There is still the same problem. Thanks u for your help! wait for your sugesstion!






![微信图片_20200407154325](https://user-images.githubusercontent.com/63183456/78643677-32022000-78e7-11ea-899f-6cecdfa7ed3a.jpg)

**Comment by fengkouxiaozhu** [comment]
my app config.js file in detail as follows:

var config =
{
	loginEnabled     : false,
	developmentPort  : 3443,
	productionPort   : 443,
	multipartyServer : 'mediasoup.ros.com',
	turnServers      : [
		{
			urls : [
				'turn:turn.example.com:443?transport=tcp'
			],
			username   : 'example',
			credential : 'example'
		}
	],
	/**
	 * If defaultResolution is set, it will override user settings when joining:
	 * low ~ 320x240
	 * medium ~ 640x480
	 * high ~ 1280x720
	 * veryhigh ~ 1920x1080
	 * ultra ~ 3840x2560
	 **/
	defaultResolution  : 'medium',
	// Enable or disable simulcast for webcam video
	simulcast          : true,
	// Enable or disable simulcast for screen sharing video
	simulcastSharing   : false,
	// Simulcast encoding layers and levels
	simulcastEncodings :
	[
		{ scaleResolutionDownBy: 4 },
		{ scaleResolutionDownBy: 2 },
		{ scaleResolutionDownBy: 1 }
	],
	// Socket.io request timeout
	requestTimeout    : 10000,
	transportOptions  :
	{
		tcp : true
	},
	lastN       : 4,
	mobileLastN : 1,
	background  : 'images/background.jpg',
	// Add file and uncomment for adding logo to appbar
	// logo       : 'images/logo.svg',
	title       : 'Multiparty meeting',
	theme       :
	{
		palette :
		{
			primary :
			{
				main : '#313131'
			}
		},
		overrides :
		{
			MuiAppBar :
			{
				colorPrimary :
				{
					backgroundColor : '#313131'
				}
			},
			MuiFab :
			{
				primary :
				{
					backgroundColor : '#5F9B2D',
					'&:hover'       :
					{
						backgroundColor : '#518029'
					}
				}
			},
			MuiBadge :
			{
				colorPrimary :
				{
					backgroundColor : '#5F9B2D',
					'&:hover'       :
					{
						backgroundColor : '#518029'
					}
				}
			}
		},
		typography :
		{
			useNextVariants : true
		}
	}
};

**Comment by fengkouxiaozhu** [comment]
i guess the turnserver configuration is trouble.   Thanks!
I did not config turnserver.  is it necessary?

**Comment by havfo** [comment]
It is not necessary, but you can run into issues in certain network scenarios if you don't have one.
