### ISSUE TITLE
What is the source of Flex-container that shows the video and audio resolution and properties?

### ISSUE THREAD

**Issue by sabyasachi-basu-i** [havfo/multiparty-meeting#178]
What is the source of Flex-container that shows the video and audio resolution and properties? 

For me it is:
<div class="jss418"><div class="jss419"><p>opus</p><p>VP8</p><p>640x480</p></div></div>

**Comment by havfo** [comment]
I am sorry, but I do not understand your question. Are you asking where the data for that container is coming from?

**Comment by sabyasachi-basu-i** [comment]
Yes, what is the source of this attached image? or as you said where that container is coming from.
![onVideoDetails](https://user-images.githubusercontent.com/59440889/78623265-e29b0000-78a4-11ea-8352-b680471a1675.png)

**Comment by havfo** [comment]
It simply gets the data about audio and video codecs from the respective producers and consumers. If you have simulcast enabled, it also shows information about simulcast layers. The codecs are chosen based on your server config. Your resolution is chosen based on your client config or settings.

**Comment by sabyasachi-basu-i** [comment]
thank you, that's really helpful. but may you please tell me the javascript(source) that encodes this in the video layer.

**Comment by havfo** [comment]
It is not encoded into the video layer, it is a simple overlay. The code for it can be seen here: https://github.com/havfo/multiparty-meeting/blob/d2a6f12aac04d0fefa4c1bb205087561a485e1c9/app/src/components/VideoContainers/VideoView.js#L169

**Comment by sabyasachi-basu-i** [comment]
that's extremely helpful.. thank you so much!
