### ISSUE TITLE
can not enter the room again

### ISSUE THREAD

**Issue by fengkouxiaozhu** [havfo/multiparty-meeting#184]
What a pity! I reinstall the multiparty-demo. There is still the same problem. Thanks u for your help! wait for your sugesstion!

![微信图片_20200407154325](https://user-images.githubusercontent.com/63183456/78735371-3f69e980-797d-11ea-8136-8d0b7acc2c83.jpg)

**Comment by misi** [comment]
Did you set in your app config your server 'FQDN' so replace 'fqdn' in app config with your servers 'hostname.domain'

**Comment by fengkouxiaozhu** [comment]
my app config.js file in detail as follows:

var config =
{
loginEnabled : false,
developmentPort : 3443,
productionPort : 443,
multipartyServer : 'mediasoup.ros.com',
turnServers : [
{
urls : [
'turn:turn.example.com:443?transport=tcp'
],
username : 'example',
credential : 'example'
}
],
/**
* If defaultResolution is set, it will override user settings when joining:
* low ~ 320x240
* medium ~ 640x480
* high ~ 1280x720
* veryhigh ~ 1920x1080
* ultra ~ 3840x2560
**/
defaultResolution : 'medium',
// Enable or disable simulcast for webcam video
simulcast : true,
// Enable or disable simulcast for screen sharing video
simulcastSharing : false,
// Simulcast encoding layers and levels
simulcastEncodings :
[
{ scaleResolutionDownBy: 4 },
{ scaleResolutionDownBy: 2 },
{ scaleResolutionDownBy: 1 }
],
// Socket.io request timeout
requestTimeout : 10000,
transportOptions :
{
tcp : true
},
lastN : 4,
mobileLastN : 1,
background : 'images/background.jpg',
// Add file and uncomment for adding logo to appbar
// logo : 'images/logo.svg',
title : 'Multiparty meeting',
theme :
{
palette :
{
primary :
{
main : '#313131'
}
},
overrides :
{
MuiAppBar :
{
colorPrimary :
{
backgroundColor : '#313131'
}
},
MuiFab :
{
primary :
{
backgroundColor : '#5F9B2D',
'&:hover' :
{
backgroundColor : '#518029'
}
}
},
MuiBadge :
{
colorPrimary :
{
backgroundColor : '#5F9B2D',
'&:hover' :
{
backgroundColor : '#518029'
}
}
}
},
typography :
{
useNextVariants : true
}
}
};

**Comment by fengkouxiaozhu** [comment]
> Did you set in your app config your server 'FQDN' so replace 'fqdn' in app config with your servers 'hostname.domain'
my app config.js file in detail as follows:

var config =
{
loginEnabled : false,
developmentPort : 3443,
productionPort : 443,
multipartyServer : 'mediasoup.ros.com',
turnServers : [
{
urls : [
'turn:turn.example.com:443?transport=tcp'
],
username : 'example',
credential : 'example'
}
],
/**
* If defaultResolution is set, it will override user settings when joining:
* low ~ 320x240
* medium ~ 640x480
* high ~ 1280x720
* veryhigh ~ 1920x1080
* ultra ~ 3840x2560
**/
defaultResolution : 'medium',
// Enable or disable simulcast for webcam video
simulcast : true,
// Enable or disable simulcast for screen sharing video
simulcastSharing : false,
// Simulcast encoding layers and levels
simulcastEncodings :
[
{ scaleResolutionDownBy: 4 },
{ scaleResolutionDownBy: 2 },
{ scaleResolutionDownBy: 1 }
],
// Socket.io request timeout
requestTimeout : 10000,
transportOptions :
{
tcp : true
},
lastN : 4,
mobileLastN : 1,
background : 'images/background.jpg',
// Add file and uncomment for adding logo to appbar
// logo : 'images/logo.svg',
title : 'Multiparty meeting',
theme :
{
palette :
{
primary :
{
main : '#313131'
}
},
overrides :
{
MuiAppBar :
{
colorPrimary :
{
backgroundColor : '#313131'
}
},
MuiFab :
{
primary :
{
backgroundColor : '#5F9B2D',
'&:hover' :
{
backgroundColor : '#518029'
}
}
},
MuiBadge :
{
colorPrimary :
{
backgroundColor : '#5F9B2D',
'&:hover' :
{
backgroundColor : '#518029'
}
}
}
},
typography :
{
useNextVariants : true
}
}
};

**Comment by sabyasachi-basu-i** [comment]
I'm not an expert, but i guess you are trying to do "npm start" while you are in your **app** folder. you need do follow these steps as mentioned in the readme and below even to have a localhost server.
from **app** folder
$ npm run build
then
set up the server:
$ cd ..
$ cd server
$ npm install
$ sudo npm start

then try again accessing only localhost 80/443 port.

also ensure your **redis-server** is running either from terminal or background when you do "sudo npm start"

**Comment by fengkouxiaozhu** [comment]
> I'm not an expert, but i guess you are trying to do "npm start" while you are in your **app** folder. you need do follow these steps as mentioned in the readme and below even to have a localhost server.
> from **app** folder
> $ npm run build
> then
> set up the server:
> $ cd ..
> $ cd server
> $ npm install
> $ sudo npm start
> 
> then try again accessing only localhost 80/443 port.
> 
> also ensure your **redis-server** is running either from terminal or background when you do "sudo npm start"

Thank you very much! I will try again ASAP!

**Comment by fengkouxiaozhu** [comment]
> I'm not an expert, but i guess you are trying to do "npm start" while you are in your **app** folder. you need do follow these steps as mentioned in the readme and below even to have a localhost server.
> from **app** folder
> $ npm run build
> then
> set up the server:
> $ cd ..
> $ cd server
> $ npm install
> $ sudo npm start
> 
> then try again accessing only localhost 80/443 port.
> 
> also ensure your **redis-server** is running either from terminal or background when you do "sudo npm start"

excuse me,  I wondor that how do i  config the app/config.js  in localserver mode?     the mulitparty-server: "localhost"  is correct?

**Comment by sabyasachi-basu-i** [comment]
if you are using local server and hosting internally, within the networks coverage, then simple localhost would work (there would be some socket.io exceptions) but you'll be allowed to join and test.

If you're trying to host globally you'll need domain and certificate; replace the same in config.js(app), in server - config.js, and in cert folder.

**Comment by misi** [comment]
I see all open questions are solved. Many thanks for the help to @sabyasachi-basu-i! 
@fengkouxiaozhu please let me know if there is any open question here,
 or close the issue if you agree that it is now solved.
Thanks!
