### ISSUE TITLE
Image sharing on mobile

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#191]
One question, is I do file sharing on mobile I can take a picture or share a file.
Can it be set that the mobile gives also an option of sharing a picture from gallery?
Is this doable or is it under the browser control?

**Comment by havfo** [comment]
As far as I know, this is not something we control. The mobile answers with apps that can do file sharing.

**Comment by Astagor** [comment]
OK, I have checked and yes we can!

in FileSharing.js you have:
`		<Paper className={classes.root}>
			<input
				className={classes.input}
				type='file'
				disabled={!canShare}
				onChange={handleFileChange}
				id='share-files-button'
			/>
			<label htmlFor='share-files-button'>
				<Button
					variant='contained'
					component='span'
					className={classes.button}
					disabled={!canShareFiles || !canShare}
				>
					{buttonDescription}
				</Button>
			</label>

			<FileList />
		</Paper>`

You would have to add an additional button and input with accept="image/*" but only for mobile:

`		<Paper className={classes.root}>
			<input
				className={classes.input}
				type='file'
				disabled={!canShare}
				onChange={handleFileChange}
				id='share-files-button'
			/>
			<label htmlFor='share-files-button'>
				<Button
					variant='contained'
					component='span'
					className={classes.button}
					disabled={!canShareFiles || !canShare}
				>
					{buttonDescription}
				</Button>
			</label>

{ isMobile ?
			<input
				className={classes.input}
				type='file'
				accept="image/*"
				disabled={!canShare}

				onChange={handleFileChange}
				id='share-files-button'
			/>
			<label htmlFor='share-gallery-button'>
				<Button
					variant='contained'
					component='span'
					className={classes.button}
					disabled={!canShareFiles || !canShare}
				>
					{buttonDescription}
				</Button>
			</label>
: ''

}

			<FileList />
		</Paper>`

**Comment by havfo** [comment]
Thank you for ivestigating, will look into this. All your testing, feedback and help is highly appreciated!

**Comment by Astagor** [comment]
No problem, I am doing it also for myself. :-)

**Comment by Astagor** [comment]
I have created a pull request
#292

**Comment by misi** [comment]
I feel it is done so I close it. Please reopen if something missing
