### ISSUE TITLE
File share not working

### ISSUE THREAD

**Issue by LucaGabi** [havfo/multiparty-meeting#196]
Hi, what is this fixed address ? Is there a config I should set for file share function to work ?

wss://tracker.lab.vvc.niif.hu:443

Thanks!

**Comment by havfo** [comment]
This is a torrent tracker hosted by us, the developers, instead of using public trackers. You may of course set up your own. It is used for filesharing in the client.

**Comment by LucaGabi** [comment]
Thanks .. in the end .. I got that .. but it seems not to work .. to download the file ..after I replaced the value with wss://tracker.openwebtorrent.com.

If you can help with some more info I'd be grateful.

**Comment by LucaGabi** [comment]
Can I enable debug on production site ? I have no logs in console ..

**Comment by havfo** [comment]
`REACT_APP_DEBUG=* npm run build`

**Comment by Astagor** [comment]
But the defining of own torrent is just in develop branch. In Master I think it is not there. At least it is not listed in config.example.js.

**Comment by LucaGabi** [comment]
I could not setup the file sharing functionality .. video and audio are working fine .. for file sharing there is configuration I'm missing .. please help..

**Comment by Astagor** [comment]
on the develop it works fine, as in server/config.js you can add you own torrent tracker. For my users I have installed my own tracker https://github.com/webtorrent/bittorrent-tracker on my server. You set up everything within 15 minutes.

**Comment by LucaGabi** [comment]
This is my console output:
[fs.txt](https://github.com/havfo/multiparty-meeting/files/4462317/fs.txt)

**Comment by LucaGabi** [comment]
bittorrent-tracker runs on localhost .. is this corect ? I expected to bind to ip any or to specific address .. am I wrong ?

**Comment by havfo** [comment]
Have you configured a TURN server?

**Comment by LucaGabi** [comment]
Yes

**Comment by LucaGabi** [comment]
I think I get a timeout from the 'tracker' ..I'm not sure ..

**Comment by havfo** [comment]
That is the reason we set up a private tracker, the public ones are unreliable.

**Comment by LucaGabi** [comment]
but can you help me with that ? it's not clear how to setup one ... 

the one above .. runs on localhost ..... how to set an ip ? (bittorrent-tracker)

**Comment by verbavolant** [comment]
> on the develop it works fine, as in server/config.js you can add you own torrent tracker. For my users I have installed my own tracker https://github.com/webtorrent/bittorrent-tracker on my server. You set up everything within 15 minutes.

Hi Astagor, where can i put torrent tracker url into config.js? Which variable?
Because i've installed a tracker, but webtorrent won't announce the files (tried udp, wss, tcp, http...)
It seems webtorrent (in multiparty) won't contact the external server. Multiparty runs a standalone tracker on localhost?

Thanks a lot

**Comment by Astagor** [comment]
It works on the DEVELOP branch, I think in MASTER it is not yet there.
You just put
fileTracker  : 'wss://bittorrent-tracker.YOUR-DOMAIN.COM:443',
and it works. Of course I put 443 as my tracker is behind Nginx, which is a proxy to my tracker. I would recommend this, as 443 should be opened on most firewalls. My clients use my service from within hospitals, so I have everything also multiparty and torrent on 443.

**Comment by verbavolant** [comment]
Thanks a lot Astagor. It works!
i try to reproduce here:
1) MASTER git: modified RoomClient.js with an open wss tracker (wss is *important*) [1]
2) apache .conf : changed proxy settings and added rewrote for wss call [2]

would you like to add a comment into readme for proxy configurations?

Thanks a lot for your work!


[1]: Open wss tracker https://github.com/ngosang/trackerslist/blob/master/trackers_all_ws.txt
[2]: first answer  https://stackoverflow.com/questions/27526281/websockets-and-apache-proxy-how-to-configure-mod-proxy-wstunnel/27534443#27534443

**Comment by LucaGabi** [comment]
@verbavolant useful info thanks!

can you help me use nginx instead of apache ?

**Comment by verbavolant** [comment]
@LucaGabi  try this from stackoverflow [1]
I don't run nginx so i can't try...

server {
listen 443;
server_name xx.xx.xxx.xx;

location / {
    proxy_set_header   X-Forwarded-For $remote_addr;
    proxy_set_header   Host $http_host;
    proxy_pass         "https://127.0.0.1:443";
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
}

[1]
 https://stackoverflow.com/questions/41381444/websocket-connection-failed-error-during-websocket-handshake-unexpected-respon

**Comment by verbavolant** [comment]
@Astagor thanks again for your suggestion ( https://github.com/webtorrent/bittorrent-tracker )

i leave here the apache configuration (need a proxy for the secure side of ws protocol):
https://github.com/webtorrent/bittorrent-tracker/issues/339#issuecomment-603994750

**Comment by verbavolant** [comment]
@havfo last question: did you changed tracker from webtorrent tracker to opentracker?
better? how to enable wss in opentracker?
thanks again!

**Comment by misi** [comment]
@verbavolant We use webtorrent tracker, AFAIK @havfo also can't tell you more, because unfortunately we don't have experience with open tracker yet, but interested in if you have any..

**Comment by misi** [comment]
Is here any open question still here?

Can we conclude with the following?
When we will merge develop to master the hardcoded tracker will be faded out. 

@verbavolant @LucaGabi @Astagor what are your thoughts?

**Comment by verbavolant** [comment]
@misi i've seen yesterday tracker.lab.vvc.niif.hu:443 running opentracker, now is running again webtorrent.
I've installed opentracker but i've seen the master branch can't dialog with http tracker, only wss.
I'll try with develop branch tonight.
For opentracker take a look here: https://github.com/coldwinds/opentracker-auto-installer (and my issue for debian)

@misi (again) ok for me, you can conclude this discussion.

**Comment by accidentul** [comment]
can someone pleas explain to me how to setup the [bittorrent-tracker] it seems to start on my ip 
this._tracker = 'ws://x.x.x.x:8000/announce'; but when i set the ip in roomClient.js and config.json this are the stats 
0 torrents (0 active)
Connected Peers: 0
Peers Seeding Only: 0
Peers Leeching Only: 0
Peers Seeding & Leeching: 0
IPv4 Peers: 0
IPv6 Peers: 0
Clients:
