### ISSUE TITLE
error 443

### ISSUE THREAD

**Issue by alimaqsood3** [havfo/multiparty-meeting#198]
hi , i tried to host it online on ubantu 18.04 with my hosting domain.but issue is when i send url to another perosn even another tab its shows Not Found The requested URL was not found on this server.  Apache/2.4.29 (Ubuntu) Server at  Port 443

**Comment by misi** [comment]
Sorry from this information, we don't see any issue and can not help. Please provide a very detailed problem description, that you experience connected to our developments.

**Comment by alimaqsood3** [comment]
> Sorry from this information, we don't see any issue and can not help. Please provide a very detailed problem description, that you experience connected to our developments.

thanks for reply, I have application live where multiparty meeting is running .....i moved build folder to /var/www/html  it works fine but i am not able to create room ...when i move all files from build to main directory which /var/www/html ..i can make room but when i send link to join it shows Not Found The requested URL was not found on this server. Apache/2.4.29 (Ubuntu) Server at Port 443
![demo3](https://user-images.githubusercontent.com/44001150/79075493-a0424a80-7d0c-11ea-834c-e497d56ad369.png)
![Uploading demo.png…]()

**Comment by misi** [comment]
You don't have to run an Apache or any external web server, you should run the server part of our service. 
Even more I propose to just use the ansible playbook and the docker image.

See this screencast.
[![asciicast](https://asciinema.org/a/311365.svg)](https://asciinema.org/a/311365)

**Comment by misi** [comment]
Please open a new issue if we can help you further.. Thanks!
