### ISSUE TITLE
Implement screensharing

### ISSUE THREAD

**Issue by havfo** [havfo/multiparty-meeting#2]
Implement screensharing with - at least - Chrome and Firefox.

**Comment by misi** [comment]
It would be great if we could pop up screensharing in a separated new window too.
Could you please update me about the actual status? Thx...

**Comment by havfo** [comment]
The current status is that I will fix the layout code in the screensharing branch now that we have the democratic view patch in develop. When it is stable, I will merge it to develop, and we can do new things from there.

Screensharing in separate window is a good idea, i propose we look at it when the base code for screensharing has been merged.

I hope to merge some time this week, hopefully tomorrow.

**Comment by havfo** [comment]
Screensharing is now technically done and merged back to develop branch. Lets branch out from there.
