### ISSUE TITLE
Chrome 81.0.4044.92  don't ask consent to reach camera or audio device for the first time

### ISSUE THREAD

**Issue by misi** [havfo/multiparty-meeting#202]
In newly installed chrome don't pop up consent for audio and video with mm development branch. And for the user it seams there is an overconstraint error, because not allowed to reach any audio or video device.

**Comment by misi** [comment]
You can reproduce to revert consent to ask again..

**Comment by misi** [comment]
I can reproduce it on master also, so it is generic issue in our app, but the same chrome version ask consent as it should in other apps like konckplop..

**Comment by misi** [comment]
In chrome with in constraint mach type `exact` (with initaly a `null`) device id results a overconstraint error.
So we should use `ideal` constraint match in enableWebcam and in enableMic.
See commit:  f57a246d1b6560ec927d8ad97ea8713bff13edbe

**Comment by tapionx** [comment]
@misi all our servers are affected with this bug at the moment (https://iorestoacasa.work/server.html)

User is not asked to enable camera and microphone access.
Two error red error messages are shown in the left bottom corner.
The issue started with Chrome 81.0.4044.113, version 80.0.3987.163 was not affected.
User needs to manually allow access to camera and mic and reload the page.
Check the attached video for the steps to reproduce the issue:
[mm_bug_chrome.zip](https://github.com/havfo/multiparty-meeting/files/4492278/mm_bug_chrome.zip)

https://lepida1.iorestoacasa.work is an example of affected server.

The servers are running a fork of the mm docker project:
https://github.com/iorestoacasa-work/mm
using MM docker image misi/mm:v3.2.1

How can we fix this issue without waiting for a new release?

**Comment by misi** [comment]
It is fixed in the master branch too.. 
I propose to use docker image to get all bug fixes nightly. Even in stable

**Comment by tapionx** [comment]
@misi i see now that tag v3.2.1 has been updated and it fixes the problem.
So we can simply solve the issue with `docker-compose pull` :partying_face: 
Thanks for your effort!
