### ISSUE TITLE
Individual Video Mute

### ISSUE THREAD

**Issue by a-n-d-i** [havfo/multiparty-meeting#204]
Feature Request. 

So I'm meeting up with friends regularly to remotely share a couple of drinks. Some live in the countryside with a very slow internet connection (like 2 MBit). For them, it would be awesome to be able to video mute all boring video streams and just keep the interesting ones. Like a video mute button next to the audio mute.

I'm totally willing to help develop that feature but I'm new to the project as well as to mediasoup, so it would be awesome if somebody could point me in a helpful direction.

Cheers, Andi

**Comment by havfo** [comment]
We actually had this feature in an earlier version, but removed it. We are reluctant to add more buttons to the video views, but this might be something to add to the participant list. Will get back to you.
