### ISSUE TITLE
Waiting room management

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#208]
If a person is in the room and does not have the right to promote a peer, then the symbol that somebody is waiting in the waiting room should not be shown or when clicked there should be an information that the user does not have permission to promote peers. Now the waiting room list opens and the users can click a person waiting, but as expected nothing happens. This could be misleading for the users, they click but nothing happens. In my opinion to stay conform with GDPR for some use cases (healthcare) the patient (so a user without permission to promote a peer) should not see the waiting room list, as there the name of the next patient can be shown.

**Comment by Astagor** [comment]
Works good, but one issue is there. You have stopped the server from pushing lobby notification to peers without rights to promote peer. That is fine. But I think it should be differently, you should only disable the showing of the waiting room and showing messages about the lobby in the client, as the state of the peer becomes inconsistent. An example:
I login and enter the room.
I logout but I am still in the room.
A new user enters the lobby, as expected I get no notification.
I log in, while still in the room, and get no notification a new user is in the lobby and I have rights to promote him.

If the notification would have been passed from the server to me (but not displayed when Im logged out), the lobby lock would appear and could let the new user in.

**Comment by havfo** [comment]
There are two options, either disable the button and keep the state up to date, or push the lobby info to a user if they get the PROMOTE_PEER permission.

If we keep the state up to date the user without permission will get notification about the name of the user in the lobby, and that is not something we want probably. So I think option 2 is best, any thoughts?

**Comment by Astagor** [comment]
From the GDPR point of view, option 2 is better, that the server actively pushes the notification about users in lobby after I get the rights to promote peers.

**Comment by Astagor** [comment]
If you are changing this, maybe you could add in RoomClient.js that the notification sound is played, when a new peer enters the lobby, by adding in case 'parkedPeer':

`						const canPromote = store.getState().me.roles.some((role) => store.getState().room.permissionsFromRoles.PROMOTE_PEER.includes(role));
						if (canPromote) {
							this._soundNotification();
						}`

**Comment by havfo** [comment]
Will implement option 2, and also add notification sound, good point!

**Comment by Astagor** [comment]
The code looks good, I will test it tomorrow morning. I had 3 Rum&Coke already, so I should not touch  any code anymore. Have a nice evening.

**Comment by Astagor** [comment]
In my option, it should not disable the button, but the whole section should start like:
lobbyPeers.length > 0 && canPromote && <Tooltip

so to stop the icon from showing up at all. Now I saw a situation when I got the red flashing symbol although I had no rights to promote a peer and could not click the icon. But I cannot reproduce.

**Comment by havfo** [comment]
You shouldn't get the icon, because if you don't have the permission you should not get events for when someone enters the lobby. Are you sure you are running the latest server version?

**Comment by Astagor** [comment]
I will try to reproduce. And also look through the code.

**Comment by Astagor** [comment]
![Screenshot_20200504-230340](https://user-images.githubusercontent.com/11389003/81013577-a8009500-8e5b-11ea-977c-6318a9406e18.jpg)

**Comment by Astagor** [comment]
I got it. The scenario was like this:
- 2 peers (1 with can promote - moderator, other without) in the room and 2 peers in the lobby (both without can promote)
- moderator used the button "promote all"
- both peers from lobby joined and one of them got the waiting peer notification icon, although he should not.

**Comment by Astagor** [comment]
I think commit 881eac741aa71b28c99ee84a15bccdba2cb126de could be the problem: as a joining client gets the whole history including the pers in lobby. I don't see that there the information is filtered by can promote.

**Comment by havfo** [comment]
Good catch, thank you!

**Comment by Astagor** [comment]
No problem! Glad that I found it.
