### ISSUE TITLE
Add a button to clear the file list of file sharing and chat

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#209]
As doctors are using my deployment, they would like to have the option as an admin to clear the list of uploaded files and chat. This is because if they have one patient after another, they want to clear the chat and files of the previous patient.

**Comment by Astagor** [comment]
I have a problem with this feature. If I'm logged in and have the rights to clear files and chat, everything is ok. When I now logout, just opening of the drawer causes the screen to turn white with an error:

react-dom.production.min.js:209 Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=Component for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by havfo** [comment]
Should now be fixed, please test.
