### ISSUE TITLE
npm ERR! Failed at the multiparty-meeting-server@3.2.0 start script.

### ISSUE THREAD

**Issue by Wisasm** [havfo/multiparty-meeting#215]
Hi i want to install multiparty-meeting in local

Win 10 
node@v10.9.0
npm@6.2.0
after npm install to server & app then 

$ npm start

i have got 

> multiparty-meeting-server@3.2.0 start D:\Projects\multiparty-meeting-master\multiparty-meeting-master\server
> DEBUG=${DEBUG:='*mediasoup* *INFO* *WARN* *ERROR*'} INTERACTIVE=${INTERACTIVE:='true'} node server.js

'DEBUG' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multiparty-meeting-server@3.2.0 start: `DEBUG=${DEBUG:='*mediasoup* *INFO* *WARN* *ERROR*'} INTERACTIVE=${INTERACTIVE:='true'} node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multiparty-meeting-server@3.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

----------------------------------------------------
debug.log 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle multiparty-meeting-server@3.2.0~prestart: multiparty-meeting-server@3.2.0
6 info lifecycle multiparty-meeting-server@3.2.0~start: multiparty-meeting-server@3.2.0
7 verbose lifecycle multiparty-meeting-server@3.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle multiparty-meeting-server@3.2.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Projects\multiparty-meeting-master\multiparty-meeting-master\server\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\samma\bin;C:\Python27;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Git\cmd;C:\Users\samma\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\wamp64\bin\php\php7.2.14;C:\ProgramData\ComposerSetup\bin;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Microsoft VS Code\bin;D:\Dart\dart-sdk\bin;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\EShare;D:\KasperSky;C:\Windows\System32;C:\Program Files\nodejs;C:\Users\samma\AppData\Local\Programs\Python\Python37-32\Scripts;C:\Users\samma\AppData\Local\Programs\Python\Python37-32;C:\Users\samma\AppData\Local\Microsoft\WindowsApps;C:\Users\samma\AppData\Roaming\Composer\vendor\bin;C:\Users\samma\AppData\Local\GitHubDesktop\bin;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Nmap;C:\Users\samma\AppData\Local\atom\bin;C:\src\flutter\flutter\bin;C:\Users\samma\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3\bin;C:\Program Files\heroku\bin;C:\Users\samma\AppData\Roaming\ScanApp2;C:\Users\samma\AppData\Roaming\npm;C:\Windows\System32;C:\Users\samma\.composer\vendor\bin
9 verbose lifecycle multiparty-meeting-server@3.2.0~start: CWD: D:\Projects\multiparty-meeting-master\multiparty-meeting-master\server
10 silly lifecycle multiparty-meeting-server@3.2.0~start: Args: [ '/d /s /c',
10 silly lifecycle   'DEBUG=${DEBUG:=\'*mediasoup* *INFO* *WARN* *ERROR*\'} INTERACTIVE=${INTERACTIVE:=\'true\'} node server.js' ]
11 silly lifecycle multiparty-meeting-server@3.2.0~start: Returned: code: 1  signal: null
12 info lifecycle multiparty-meeting-server@3.2.0~start: Failed to exec start script
13 verbose stack Error: multiparty-meeting-server@3.2.0 start: `DEBUG=${DEBUG:='*mediasoup* *INFO* *WARN* *ERROR*'} INTERACTIVE=${INTERACTIVE:='true'} node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
14 verbose pkgid multiparty-meeting-server@3.2.0
15 verbose cwd D:\Projects\multiparty-meeting-master\multiparty-meeting-master\server
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.9.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error multiparty-meeting-server@3.2.0 start: `DEBUG=${DEBUG:='*mediasoup* *INFO* *WARN* *ERROR*'} INTERACTIVE=${INTERACTIVE:='true'} node server.js`
22 error Exit status 1
23 error Failed at the multiparty-meeting-server@3.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Thanks

**Comment by misi** [comment]
We run it on linux and unfortunately I don't have experience with win10.

**Comment by Wisasm** [comment]
OK .. No problem, thanks
