### ISSUE TITLE
Enhancement: Unlock room when last peer with CHANGE_ROOM_LOCK right has left

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#219]
The room should unlock automatically if the last peer with the permission CHANGE_ROOM_LOCK leaves the room. Without it situation can happen, that a user after a connection drop cannot reenter the room, because it is locked and in the room are only users without permission to unlock the room nor to promote a peer.

**Comment by havfo** [comment]
A requirement here would be that the room "resets" when this happens. Clears chat and filesharing, or else the peers that might come into the room (and that where left in the lobby for a reason) get access to things they shouldn't have.

**Comment by Astagor** [comment]
OK, you are right that it is more complicated then I thought. Maybe it be left as it is. Because if the user with the rights just dropped out due to internet problems, a teacher, he returns and all his materials he has shared are gone. It sounds like to much auto-magic. 

I would still say that the room should just be unlocked and nothing cleared. And why? Because for me the access right bypass lobby says who has a key to the class room. The lock is like an internal bolt on the class room doors from the inside. So when the room is busy other teachers cannot open it with their keys. So if a teacher leaves the room, or the last teacher that was inside, for whatever reason, he had to unblock the bolt to get out. That why it should be unlocked. New students still would land in the lobby, but he and other teachers can go inside.

**Comment by Astagor** [comment]
One more comment, now when I lock a room and unlock it, all peers from lobby get promoted automatically. I think it is undesired as:
- teachers login to the rooms and are moderators
- they have the permission to let peers in from the lobby on the dialog list
- if the decide the room, it means that no other teacher although moderator cannot enter, as moderators do not have the bypass lock permission.

So locking the room is like taking it for my class and I control who enter using the lobby, wherever students or other teachers. If the opening of the lock allows all to enter automatically from the lobby, it is an undesired feature. I think that lock and lobby should be separated functions.

**Comment by havfo** [comment]
Is this use-case solved by latest commit on  #303 ?

**Comment by havfo** [comment]
Set `allowWhenRoleMissing: [ CHANGE_ROOM_LOCK, PROMOTE_PEER ]`

**Comment by havfo** [comment]
@Astagor

**Comment by Astagor** [comment]
Yes, it works very well. Thank you very much! Sorry for forgetting to write here.

**Comment by Astagor** [comment]
I would like to reopen this issue as my teachers have said that, although the allowWhenRoleMissing works ok, but if the teacher leaves and the students are left to work in group and get the permission to play with the room lock, the deliberately lock they room when the shouldn't and don't let others in. So in my installation I unlock room when is locked and last peer with the right to change room lock has left. I will do a pull request with the code, so you can decide if to include it.
