### ISSUE TITLE
How to change the website title?

### ISSUE THREAD

**Issue by utkarshdubey** [havfo/multiparty-meeting#220]
The title still renders "Multiparty Meeting", any idea which component it might be in?

**Comment by misi** [comment]
Title is hardcoded actually
<title>Multiparty Meeting</title>

**Comment by utkarshdubey** [comment]
Harcoded where exactly?

**Comment by misi** [comment]
It is here: https://github.com/havfo/multiparty-meeting/blob/effdd3005b9641d1d503d70af064eab0a9c550a8/app/public/index.html#L16

**Comment by utkarshdubey** [comment]
Can you answer my latest issue @misi ? It's quite urgent.
