### ISSUE TITLE
Error while deploying on Ubuntu.

### ISSUE THREAD

**Issue by utkarshdubey** [havfo/multiparty-meeting#221]
![image](https://user-images.githubusercontent.com/29272078/79555703-a5f9b080-80bd-11ea-903b-88e2984e4a43.png)
I'm using Ubuntu on Digital Ocean. Not quite sure why this error is popping up considering all the paths were correct in the multiparty-meeting.service file. It was working perfectly in the ``npm start`` development mode.

**Comment by misi** [comment]
check if you run it multiple times...

**Comment by utkarshdubey** [comment]
No I'm not.

**Comment by misi** [comment]
It seems file created already.. killall node process and delete file from tmp and start again..

**Comment by utkarshdubey** [comment]
Thanks, it works.
