### ISSUE TITLE
Prometheus monitoring

### ISSUE THREAD

**Issue by christian-2** [havfo/multiparty-meeting#222]
I have implemented a simple Prometheus exporter. As a current prototype it was already useful in resolving some issues with a local installation of `multiparty-meeting`.

The exporter is optional  (configurable in environment variables and off by default) and consists of a new file `server/lib/promExporter.js` plus a few lines in `server/server.js`:

```
const promExporter = require('./lib/promExporter');

// start Prometheus exporter
await promExporter(rooms, peers);
```
I would like to donate the exporter here. Are you interested in creating a new branch `mm-exporter` or receiving a PR from my fork?

From my perspective it would be good if the exporter were included in the normal build process so that it could be chosen e.g. in [`docker-compose.yml`](https://github.com/misi/mm/blob/master/docker-compose.yml) with a dedicated tag.

<img width="959" alt="Screenshot" src="https://user-images.githubusercontent.com/49752982/79559039-61fab180-80a5-11ea-8340-68b4b28a5bf9.png">

**Comment by tapionx** [comment]
@christian-2 your feature is really interesting!
We are using prometheus for iorestoacasa.work, and we added an exporter with an additional docker image:
https://github.com/iorestoacasa-work/mm/blob/master/docker-compose.yml#L42

Your implementation is cleaner and i would love to see that merged into MM

**Comment by misi** [comment]
Can I ask you all to come and develop together? So I invite you to misi/mm project and merge back all forked new features?

**Comment by christian-2** [comment]
@misi Thanks for the invitation. Since the present changes concern Node.js source code their first landing point would have to be `havfo/multiparty-meeting`. At this point I am using `mm/misi` as is.

**Comment by tapionx** [comment]
@misi ok thanks! I'm not a NodeJS developer but i can help with others tasks

**Comment by misi** [comment]
@christian-2  please send a PR or if you want come and develop with us!

**Comment by christian-2** [comment]
Preparing and testing a PR against base branch `develop` was more difficult than expected. 

My test setup (with an instance of `multiparty-meeting` on an intranet and two laptops connecting from home over VPNs and with TCP partly involved) still works with `master` but does not work with `develop`. This is due in part to #170.

I do not have time now to track these presumably unrelated networking issues further. So I can offer two alternatives: a PR against `develop` that is yet untested or a PR against `master` that I have been using myself. IMO the feature should go into `develop` first. What do you prefer?

**Comment by misi** [comment]
I prefer the develop version..

**Comment by starkers** [comment]
Just wanted to day that this is a very desirable feature and to add my thanks

**Comment by christian-2** [comment]
In retrospect and with tight integration into `multiparty-meeting` it may be better to do the configuration in `server/config/config.js` instead of with environment variables. For instance, the Prometheus exporter could be activated if an object `config.prometheus` were present and the following defaults could apply:

```
prometheus: {
  deidentify: false,
  numeric: false,
  port: 8889,
  quiet: false 
}
```

Please let me know if you prefer this style of configuration.

**Comment by havfo** [comment]
This aligns better with the way we do existing things in `multiparty-meeting`, `config.prometheus` sounds good.
