### ISSUE TITLE
What is the limit for a room?

### ISSUE THREAD

**Issue by utkarshdubey** [havfo/multiparty-meeting#223]
How many people can join a room at a particular time?

**Comment by misi** [comment]
It depends on your cpu, and medistream usage.
See: https://mediasoup.org/documentation/v3/scalability/
~100++ peer in one room

**Comment by so010** [comment]
https://github.com/havfo/multiparty-meeting/wiki/Scaling-and-recommended-Hardware

**Comment by Prudhvi1357** [comment]
Hi, Does this demo project will support 100 users in single room if we host in 16 core machine. with 10 videos published and remaining in passive mode with voice activated.

**Comment by nareshinstavc** [comment]
Hi, Does this demo project will support 100 users in single room if we host in 16 core machine. with 10 videos published and remaining in passive mode with voice activated.

**Comment by misi** [comment]
@nareshinstavc if you increase lastN then it will decrease max peers.

**Comment by nareshinstavc** [comment]
> @nareshinstavc if you increase lastN then it will decrease max peers.

Thank you for your reply. 
I am little confused about the capacity.
I have a requirement where as there are 60 participants joined in single room everyone is subscribed for 5 users audio and video . Does it supports ?


If no by default,  I seen u documentation about scaling distributing the load to another thread or router. does this demo project supports.

**Comment by so010** [comment]
> > @nareshinstavc if you increase lastN then it will decrease max peers.
> I have a requirement where as there are 60 participants joined in single room everyone is subscribed for 5 users audio and video . Does it supports ?

This is slightly over the 500 consumer limit per room. With 4 users audio/video for everyone it should work fine.

**Comment by so010** [comment]
> Hi, Does this demo project will support 100 users in single room if we host in 16 core machine. with 10 videos published and remaining in passive mode with voice activated.

https://github.com/havfo/multiparty-meeting/wiki/Scaling-and-recommended-Hardware

**Comment by Astagor** [comment]
What about the screen sharing stream. I think that by lastN=4 and screen sharing and 60 users it is 4 * 3 * 59 + 4 * 2 = 716

Or am I wrong?

**Comment by Astagor** [comment]
One more question, is this limit of 500 consumers per room a fixed restriction, hardcoded, or is this a value that was discovered during testing?

**Comment by misi** [comment]
It is mediasoup restriction, by default, but we can scale up higher peers numbers for sure, we have two experimental branches not yet merged to develop.
See branch `feat-server-scaling` where with pipes more cpu cores can serve one room, so we can scale up until the max cpu core load on one host, 
and see `feat-server-scaling` wehre we step one step further and we can scale on multiple media nodes, multiple hosts can share one video room media traffic.

**Comment by cap19** [comment]
> https://github.com/havfo/multiparty-meeting/wiki/Scaling-and-recommended-Hardware

Hi - does each MM meeting exclusively use one thread? So, on a 4 core server, there can be 8 concurrent meetings maximum. Is that correct?

**Comment by Astagor** [comment]
I think it is not so, you can have as as many rooms as you want as long as the limit of 500 consumers per room and per thread is not exceeded. 
 So if you have 8 cores, you get 8 workers. Each worker has the limit of 500 consumers and it does not care if the consumers are coming from 1 room of many.

**Comment by havfo** [comment]
As an example, we are running a 12 thread server with 40 rooms with no problems. There is no limit in that sense, the meeting experience will start degrading when your cores are fully loaded.

**Comment by cap19** [comment]
It's clear now. Thank you @Astagor and @havfo

**Comment by so010** [comment]
> What about the screen sharing stream. 
Noboby sad screensharing but yes then there will be 1 extra stream per participant.

>     * I guess all audio streams are always forwarded, that even when not visible someone can start talking, right?
>       60 * 59
Yes this is right but in realworld participants would hopefully mute themselves, We added auto mute for new participants in bigger rooms. I think there should never be more than 5-10 audiochannels active at the same time. But If you say in a 100 participants room "Can everybody unmute and say YES"  would possibly make mediasoup very unhappy. 

> Or am I wrong?
No you're right ;)
