### ISSUE TITLE
Feature: Add maxLastN

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#225]
I would propose to add a maxLastN parameter to app/public/config/config.js to limit na maximum video places for the application. This value should be the maximum that a user can set in drop down list in the settings of the app. For large meetings it is useful not to kill the server.

**Comment by misi** [comment]
Until we scale 1 room 1 core, it is benefitial to have an administrative limit to be able to say how many participant we support in one room. So I support this idea.

**Comment by Astagor** [comment]
I would propose to add something like this in RoomClient.js to verify if somebody has not set lastN and mobileLastN beyond maxLastN

`let requestTimeout,
	transportOptions,
	lastN,
	mobileLastN,
	  //ASTAGOR START
		maxLastN,
	  //ASTAGOR END
	defaultResolution;

if (process.env.NODE_ENV !== 'test')
{
	({
		requestTimeout,
		transportOptions,
		lastN,
		mobileLastN,
	  //ASTAGOR START
		maxLastN,
	  //ASTAGOR END
		defaultResolution
	} = window.config);
}

//ASTAGOR START
if (!('maxLastN' in window.config)) maxLastN = 10;
if (lastN > maxLastN) lastN = maxLastN;
if (mobileLastN > maxLastN) mobileLastN = maxLastN;
//ASTAGOR END`

**Comment by havfo** [comment]
I sort of agree, but this shouldn't be necessary, all these values are configured by admin.
