### ISSUE TITLE
Need help: Server does not render Voice or Video 

### ISSUE THREAD

**Issue by sabyasachi-basu-i** [havfo/multiparty-meeting#232]
Dear Team,

I hosted the tool in gcloud Compute Engine. it's running perfectly with no errors in console. each user can join the room, and it shows the other users also, however, does not show Video or Audio or these users.

![IssueMM](https://user-images.githubusercontent.com/59440889/79628489-055bcd00-815f-11ea-86c1-86875a807cea.PNG)

The second user was sharing Video and Audio both in the room.

Below are my config file details.
## server/config/config.js (adding only changed/impt parameters)
	redisOptions : {},
	listeningPort         : 443,
	listeningRedirectPort : 80,
	httpOnly              : false,
	requireSignInToAccess : false,
        webRtcTransport :
        		{
	        		listenIps :
		        	[
			        	{ ip: '0.0.0.0', announcedIp: null }
        			],
	        		initialAvailableOutgoingBitrate : 1000000,
		        	minimumAvailableOutgoingBitrate : 600000,
        			maxIncomingBitrate              : 1500000
          		}

## server/public/config/config.js
	var config =
	{
		loginEnabled     : true,
		developmentPort  : 3443,
		productionPort   : 443,
		multipartyServer : '35.196.48.131',
		turnServers      : [
			{
				urls : [
					'turn:turn.example.com:443?transport=tcp'
				],
				username   : 'example',
				credential : 'example'
			}
		],
	 }

**Comment by misi** [comment]
Change 0.0.0.0 in listen ip  to your exact private ipv4 and announceIP to your global ipv4.

**Comment by sabyasachi-basu-i** [comment]
i did. the new conf:
`{ ip: '10.142.0.57', announcedIp: '35.196.48.131' }`

but the same issue. Attaching a few error and info logs below, if you may help out.
`  multiparty-meeting-server:ERROR:Room TypeError: Cannot read property 'user' of undefined
  multiparty-meeting-server:ERROR:Room     at Room._handleSocketRequest (/home/sabyasachiba/multiparty-meeting/server/lib/Room.js:431:49)
  multiparty-meeting-server:ERROR:Room     at Socket.peer.socket.on (/home/sabyasachiba/multiparty-meeting/server/lib/Room.js:349:9)
  multiparty-meeting-server:ERROR:Room     at Socket.emit (events.js:198:13)
  multiparty-meeting-server:ERROR:Room     at Socket.EventEmitter.emit (domain.js:448:20)
  multiparty-meeting-server:ERROR:Room     at /home/sabyasachiba/multiparty-meeting/server/node_modules/socket.io/lib/socket.js:528:12
  multiparty-meeting-server:ERROR:Room     at process._tickCallback (internal/process/next_tick.js:61:11) +718ms`
[errorLog_MM.txt](https://github.com/havfo/multiparty-meeting/files/4496254/errorLog_MM.txt)

**Comment by misi** [comment]
Check frirwall/NAT device that the media ports  40000 -49999 udp, are DNAT-ed correctly to your private IP.

**Comment by sabyasachi-basu-i** [comment]
I'm not bragging an inch.. you're a genius.. thank you so much.. My official email address: `sabyasachi.basu@innowise.us` @misi may I connect you, if that's ok..

**Comment by misi** [comment]
Sure of course.

**Comment by ghostsf** [comment]
The same to me, thank you so much.
but why function `getListenIps` sets `announcedIp` `null` ?

`listenIP.push({ ip: iface.address, announcedIp: null });`
