### ISSUE TITLE
can't start a room without signin

### ISSUE THREAD

**Issue by dungeon2567** [havfo/multiparty-meeting#233]
i deployed it on my server but can't start a room without signin

url for testing: https://commercifly.ml/

the problem:

![Sem título](https://user-images.githubusercontent.com/31074903/79628869-81ccbc80-811b-11ea-8d7c-2c7c610614d0.png)

**Comment by sabyasachi-basu-i** [comment]
Check your server/config/config.js file. change the below setting.
    requireSignInToAccess : false,
