### ISSUE TITLE
Is MM communication end-to-end secure?

### ISSUE THREAD

**Issue by cap19** [havfo/multiparty-meeting#236]
How secure are MM meetings?

Are the meetings end-to-end encrypted between all participants (many to many, one to one, etc.)?

**Comment by misi** [comment]
We use SFU so communication data is encrypted between the client and the server. If you need E2E security between the clients, you can user PREC that is not implemented in browsers or the "Insertable Streams that is comming, but not implemented in all browsers, but we are considering to support it. See: https://webrtchacks.com/true-end-to-end-encryption-with-webrtc-insertable-streams/

**Comment by misi** [comment]
I forgot to answer to your initial question.
>How secure are MM meetings?

They are as secure as possible, but we are tring to do our best on this field.

**Comment by cap19** [comment]
Thank you @misi Looking forward to the _potential_ Insertable Streams implementation.

Quick follow-up: Does 1-on-1 communication also go through SFU, and therefore the server, or is it a direct p2p connection with full e2e encryption?

**Comment by so010** [comment]
p2p is not implemented yet
https://github.com/havfo/multiparty-meeting/issues/1
