### ISSUE TITLE
WebSocket connection failed: Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by chiragmewada** [havfo/multiparty-meeting#237]
Hi,

First of all, thank you for this great work. 

I have checkout the development branch and it is working fine on all the browser. But when I am accessing through iOS safari, socket is keep disconnecting with following error.

WebSocket connection failed: Error during WebSocket handshake: Unexpected response code: 400

I am running my server behind the proxy. I have tried with multiple option but nothing working for me.

OS:	Ubuntu 18.04.3 LTS
Server version: Apache/2.4.29 (Ubuntu)
Node Version: v10.20.1
mediasoup: 3.5.7

Can you suggest what could be the issue?

Thanks,
Chirag.

**Comment by chiragmewada** [comment]
I build new server and now I am not using any proxy.

received following error in log

  multiparty-meeting-server:ERROR:Room "request" failed [error:"Error: consumer with id "3606de73-42f0-42b8-a407-ec72df9cb943" not found at Room._handleSocketRequest (/mnt/multiparty-meeting/server/lib/Room.js:815:12) at Socket.<anonymous> (/mnt/multiparty-meeting/server/lib/Room.js:425:9)     at Socket.emit (events.js:315:20)     at Socket.EventEmitter.emit (domain.js:485:12) at /mnt/multiparty-meeting/server/node_modules/socket.io/lib/socket.js:528:12     at processTicksAndRejections (internal/process/task_queues.js:79:11)"] +0ms

**Comment by chiragmewada** [comment]
this is what I found
https://github.com/jampy/react-wakelock/issues/1

iOS: HTTP requests cancelled every 15 seconds #1

**Comment by chiragmewada** [comment]
Resolved

app/src/components/Room.js
had to comment 

				{/* { isMobile &&
					<WakeLock />
				} */}


// import WakeLock from 'react-wakelock-react16';

**Comment by misi** [comment]
@chiragmewada  can you please write which iOS version did you used?
If it is a general issue we should fix it.
Thanks!!

**Comment by chiragmewada** [comment]
> @chiragmewada can you please write which iOS version did you used?
> If it is a general issue we should fix it.
> Thanks!!

I am performing test on **iPhone X - iOS version 13.3.1**

Feel free to reach me out if you want me to test in future. Happy to help :)

**Comment by misi** [comment]
Many Thanks!
I will start working on a fix to disable wakelock on ios,
