### ISSUE TITLE
Warnings while installing

### ISSUE THREAD

**Issue by hdavy2002** [havfo/multiparty-meeting#239]
Tried to do manual install. Got a bunch of warning after I did npm install. Also tried yarn install
root@li2118-38:~/multiparty-meeting/app# nodejs -v
**v10.20.1**

With npm install#

root@li2118-38:~/multiparty-meeting/app# npm -v
**6.14.4**
root@li2118-38:~/multiparty-meeting/app# npm install
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperj                                                                                                                                                             s/core, this package is dedicated to the legacy v1
npm WARN deprecated fsevents@2.0.6: Please update: there are crash fixes
npm WARN deprecated chokidar@2.1.8: Upgrade to chokidar 3 with 15x less dependen                                                                                                                                                             cies. Chokidar 2 will break on node v14.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://git                                                                                                                                                             hub.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#dep                                                                                                                                                             recated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprec                                                                                                                                                             ated
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not r                                                                                                                                                             ecommended for usage due to the number of issues. Please, upgrade your dependenc                                                                                                                                                             ies to the actual version of core-js@3.

root@li2118-38:~/multiparty-meeting/app# ^C

With yarn install

root@li2118-38:~/multiparty-meeting/app# yarn --version
**1.22.4**
root@li2118-38:~/multiparty-meeting/app# yarn install
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
warning @material-ui/core > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning react-scripts > fsevents@2.0.6: Please update: there are crash fixes
warning react-scripts > webpack-dev-server > chokidar@2.1.8: Upgrade to chokidar 3 with 15x less dependencies. Chokidar 2 will break on node v14.
warning react-scripts > react-dev-utils > fork-ts-checker-webpack-plugin > chokidar@2.1.8: Upgrade to chokidar 3 with 15x less dependencies. Chokidar 2 will break on node v14.
warning react-scripts > webpack > watchpack > chokidar@2.1.8: Upgrade to chokidar 3 with 15x less dependencies. Chokidar 2 will break on node v14.
warning react-scripts > jest-environment-jsdom-fourteen > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning react-scripts > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning react-scripts > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning react-scripts > webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-scripts > webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning react-scripts > workbox-webpack-plugin > workbox-build > strip-comments > babel-plugin-transform-object-rest-spread > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[2/4] Fetching packages...
warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
warning url-loader@1.1.2: Invalid bin field for "url-loader".
info fsevents@2.0.6: The platform "linux" is incompatible with this module.
info "fsevents@2.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "react-scripts > @typescript-eslint/parser@1.6.0" has unmet peer dependency "typescript@*".
warning "react-scripts > @typescript-eslint/eslint-plugin@1.6.0" has unmet peer dependency "typescript@*".
warning "react-scripts > @typescript-eslint/parser > @typescript-eslint/typescript-estree@1.6.0" has unmet peer dependency "typescript@*".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > riek@1.1.0" has incorrect peer dependency "react@^0.14.0 || ^15.5.4".
warning " > riek@1.1.0" has incorrect peer dependency "react-dom@^0.14.0 || ^15.5.4".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 101.43s.

root@li2118-38:~/multiparty-meeting/server# yarn install
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
warning ims-lti > node-uuid@1.4.8: Use uuid module instead
warning ims-lti > xmlbuilder > lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
warning mediasoup > clang-tools-prebuilt > nugget > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 558.10s.

**Comment by viveksi** [comment]
dealing with same issue while doing the npm install on existing angular 8 application getting lot of errors 

```
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.12: fsevents 1 will break on node v14+. Upgrade to fsevents 2 with massive improvements.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

```

**Comment by misi** [comment]
Warnings are general, and hopefully go away as our dependencies are fixing them.
