### ISSUE TITLE
How to Install from A to Z ? 

### ISSUE THREAD

**Issue by Soriasat** [havfo/multiparty-meeting#246]
I would like to ask you to help me to install the multiparty-meeting on my own server. 

I am a beginner.

I tried a lot and it didn't complete successfully . 

I always start with a new operating system , I tried  Ubuntu 16.04 , Ubuntu 18 , Debian 10 and all that not success. 

I try to Install with manual-installation method .

What are the prerequisites and what exactly are the steps to get the job done successfully!.

I followed the sequence mentioned on this page " https://github.com/havfo/multiparty-meeting#manual-installation "    and did not succeed.

How to test every steps when it complete  ?

are you make any "sh" script to install  multiparty-meeting on my own server ?
Please Help me ..

Thank you for all .

**Comment by misi** [comment]
For very most simple way of installing it please check the ansible script or docker image installation way.

**Comment by Soriasat** [comment]
Thank you misi.

But I would like to do it by manual type for many reason . I would ask you  to explain steps and I will be very thanks for you .

**Comment by enterux** [comment]
Please check if you are using node version 10.x otherwise you may not be able to finish the compilations.

**Comment by misi** [comment]
@enterux  Now the dependency issue solved, so you can use node version 12.0 or 13.0 if you like.

**Comment by misi** [comment]
@Soriasat  see the README.md and follow that steps in manual install. 
During these steps if you have any issue then, please describe it with very detailed description, to be able to help you more.

**Comment by Navneet923** [comment]
any one to help me to Install from A to Z . I followed the sequence mentioned on this page " https://github.com/havfo/multiparty-meeting#manual-installation " and did not succeed.
 I would like to do it by manual type
