### ISSUE TITLE
in an installation an user cannot use video and audio

### ISSUE THREAD

**Issue by verbavolant** [havfo/multiparty-meeting#247]
Hello, ad user (he can use webcam and audio) with lastest git can't use video and audio . MM does not ask him for use webcam and audio.

with anoter installation (a release, not git) works

windows 10, system updated, drivers updated. A workaround in next message.

with debug on:
multiparty-meeting:ERROR:RoomClient enableMic() failed:OverconstrainedError +0ms (common.js 109)

on the server i've got:

 mediasoup:Channel request() [method:transport.setMaxIncomingBitrate, id:6] +1ms
  mediasoup:Channel request succeeded [method:transport.setMaxIncomingBitrate, id:6] +0ms
  multiparty-meeting-server:ERROR:Room TypeError: Cannot read property 'user' of undefined
  multiparty-meeting-server:ERROR:Room     at Room._handleSocketRequest (/home/mm/multiparty-meeting/server/lib/Room.js:430:49)
  multiparty-meeting-server:ERROR:Room     at Socket.peer.socket.on (/home/mm/multiparty-meeting/server/lib/Room.js:349:9)
  multiparty-meeting-server:ERROR:Room     at Socket.emit (events.js:189:13)
  multiparty-meeting-server:ERROR:Room     at Socket.EventEmitter.emit (domain.js:441:20)
  multiparty-meeting-server:ERROR:Room     at /home/mm/multiparty-meeting/server/node_modules/socket.io/lib/socket.js:528:12
  multiparty-meeting-server:ERROR:Room     at process._tickCallback (internal/process/next_tick.js:61:11) +2m

**Comment by verbavolant** [comment]
workaround:
in chrome, site settings, (with videocam and microphone enabled) you must say enabled (not auto) to audio settings

with this will fail
![image](https://user-images.githubusercontent.com/27216842/79962273-22a6d900-8488-11ea-8e9f-d80c9975bed6.png)

with this is ok
![image](https://user-images.githubusercontent.com/27216842/79962348-37836c80-8488-11ea-8794-bd8f787ca9e5.png)

(i need an english chrome...)

**Comment by misi** [comment]
Which git commit do you use?

**Comment by so010** [comment]
Just to be sure: For manual install, you should begin from scratch or at least rm -rf node_modules in app an server folder.

**Comment by misi** [comment]
It is fixed see #202

**Comment by misi** [comment]
Please try to get the latest master it should work, many people confirmed that it is fixed. 
Otherwise if you still experience it please let me know.

**Comment by verbavolant** [comment]
i've tested with lastest master (git pull).
Let's test with another fresh install.

**Comment by verbavolant** [comment]
i confirm: on a fresh install now it works.
Maybe add in readme to do a clean every git pull?

Thanks a lot

Marco

**Comment by misi** [comment]
Please sen a PR about it and we will include it. I conclude this issue is done. Please confirm and close then. Many thanks for the cooperation..
