### ISSUE TITLE
TURN credentials using static-auth

### ISSUE THREAD

**Issue by bpcurse** [havfo/multiparty-meeting#251]
Is it possible to enter a static-auth secret in app/public/config/config.js instead of username/credential for the TURN Server?
If not, could this config option be added?

Thank you for this great tool!

**Comment by misi** [comment]
It could be used in development branch you need to create and external REST API server that generates username and secret in response. 
I tried to follow this draft: 
https://tools.ietf.org/html/draft-uberti-rtcweb-turn-rest-00
See this example: https://github.com/misi/stun-api

So we don't use the shared secret directly, you need to have an external entity that provides the Time Limited Long Term Credential information, so REST STUN/TURN API server that you provide your shared secret and in response it gives back server and credential.
```
{
  "username": "1587680293",
  "password": "VlHm/ofiE5qlNUnW9zqCssdABQE=",
  "ttl": 86400,
  "uris": [
    "turn:192.0.2.29:80?transport=tcp",
    "turn:192.0.2.29:3478?transport=tcp",
  ]
}
```

**Comment by aksdb** [comment]
Aren't both a security risk if the credentials are stored in the web app? I thought (especially with the shared secret) that the server/backend would use this to generate a (short living) secret for the client to use. Otherwise anyone who can access the web application could read the secret to do whatever he wants with the TURN server.

**Comment by misi** [comment]
@aksdb We move in next version see `develop` branch config from app config to server side, and then we use a rest API to get  Time limited credential, and we could fallback (only if set) to the old Long Term Credential so username/password without time limit.

**Comment by aksdb** [comment]
Ah nice. Awesome. I'm very impressed so far. Thanks for that project!
