### ISSUE TITLE
Clear Files and Clear Chat causes app to crash

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#252]
I have a problem with this feature. If I'm logged in and have the rights (set in config.js) to clear files and chat, everything is ok. When I now logout and am still in the room, just opening of the drawer causes the screen to turn white with an error:

react-dom.production.min.js:209 Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=Component for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by havfo** [comment]
Should be fixed in fcc37f5d89791d4fb1ac4bd956a771614f567c9c

**Comment by Astagor** [comment]
Is fixed, thx.
