### ISSUE TITLE
Clear Files problem

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#257]
If I share a file and then as moderator I clear the file list, everything works as expected, the file list is cleared. However, then if I want to add the same file again, the sharing fails. Other files can be shred. It is as although I have cleared the files, somewhere it is still stored as shared and I cannot share the same file again.

**Comment by misi** [comment]
@Astagor 
Is there any error the js console?
I guess the torrent file or magic link is not cleared from webtorrent client.

**Comment by so010** [comment]
Yes, webtorrent is not accepting same file since it exists already. We should cleanup webtorrent client  as well or just test if it exists already and return the torrent.
