### ISSUE TITLE
icecandidateerror (connection between local transport and mediasoup) is failed 

### ISSUE THREAD

**Issue by tarekkhaled** [havfo/multiparty-meeting#263]

**Comment by tarekkhaled** [comment]
#### here's my turn server 
![turnServer](https://user-images.githubusercontent.com/20762427/80309073-c8cd4880-87d2-11ea-8874-db765a5e1c2b.png)

#### here's screens for setLocalDescription in chrome (webrtc-internal)
![local offer from (create transport)](https://user-images.githubusercontent.com/20762427/80309078-df739f80-87d2-11ea-95cb-5e1f1dc26a27.png)
![local offer from (create transport)2](https://user-images.githubusercontent.com/20762427/80309271-5198b400-87d4-11ea-8f2d-fb14a06770be.png)
![local offer from (create transport)3](https://user-images.githubusercontent.com/20762427/80309278-5c534900-87d4-11ea-8914-f60e0249a025.png)

#### here's screen for setRemoteDescription in chrome (webrtc-internal)
![remote offer from (create transport)](https://user-images.githubusercontent.com/20762427/80309099-f914e700-87d2-11ea-9d92-243359026ddd.png)

#### here's mediasoup server logs for the transport with transport stats
![transportgetstats](https://user-images.githubusercontent.com/20762427/80309116-18137900-87d3-11ea-8b77-e045f3c8eebb.png)

#### here's screen for the error on (RTCPeerConnection)
![webrtc-error](https://user-images.githubusercontent.com/20762427/80309315-9ae90380-87d4-11ea-801b-e7b0918bda32.png)

**Comment by havfo** [comment]
`turn.example.com` is not a valid TURN server, please use a valid TURN server.

**Comment by tarekkhaled** [comment]
@havfo , i used a vaild Turn Server as you said and i solved the previous problem and now iceconnectionstate changed to "complete" in chrome://webrtc-internal but sendTransport connection state always stuck at "new" any help for that ? if i'm understand correctly sendTransport should also change to connected when iceconnectionstate be completed and here will starting send bytes to mediasoup server  so for now no media send on the transport 

_here's also screen for RTCPeerConnection in chrome after i changed to vaild turn server_
![connectionstatenew](https://user-images.githubusercontent.com/20762427/80406581-94d25000-88c4-11ea-843e-63336809e1aa.png)

**Comment by misi** [comment]
Check that you replaced in server config the example 0.0.0.0 to your server listening IP address, if you are behind NAT check global and local ip in the same pleace and also check NAT config for media rtp port range.

**Comment by tarekkhaled** [comment]
sorry if my questions seems very basic but there are still some things that i try to understand it till now so first i'm working on localhost so change 0.0.0.0 to 127.0.0.1 it's vaild right? 
second can you please provide me some external information about what are global and local ip is and how can i check if they are in same place ?

**Comment by tarekkhaled** [comment]
i change listenIps to 127.0.0.1 and turn server seems to work and my rtc ports in config (rtcMinPort : 10000,    rtcMaxPort : 59999)  and here's screen for turn server which seems working successfully to find connection path from mediasoup and browser transports
![turnsuccess](https://user-images.githubusercontent.com/20762427/80446729-ebb54500-8917-11ea-9fc9-4d90c1e5fb79.png)
but mediasoup-client and webrtc-internal keep giving me "ice connection state" failed then disconnected 
![turnfailure](https://user-images.githubusercontent.com/20762427/80446818-228b5b00-8918-11ea-9698-43c6de1a944a.png)

**Comment by cap19** [comment]
Do 

> sorry if my questions seems very basic but there are still some things that i try to understand it till now so first i'm working on localhost so change 0.0.0.0 to 127.0.0.1 it's vaild right?
> second can you please provide me some external information about what are global and local ip is and how can i check if they are in same place ?

127.0.0.1 is your localhost ip address.

Local ip are assigned by your network e.g. your work or home router/network can 5 devices connected to it and they all get local ip address like 192.154.XX.XX. Each device will get a local ip. However your home internet router has one global ip address like 154.167.555.666. This is the ip address Turn server recognizes. Turn server does not know 127.0.0.1

You probably need to search for NAT.

**Comment by tarekkhaled** [comment]
I know a little about nat which is mapping privite ip to public and ports also the problem here that I tried to test my turn server in webrtc trickle and it's give me a relay candidate and "Done" which seems to be working but in case above there's some thing wrong happened when I tried to establish a ice connection path between mediasoup sever and mediasoup client with my turn server always give me "disconnected"

**Comment by so010** [comment]
> i change listenIps to 127.0.0.1 and turn server seems to work and my rtc ports in config

Not easy to set this up with everything on localhost. Where is your turnserver, on localhost as well then you should configure not colliding listening ports? For testing purposes this will work without 
configuring TURN at all on local host / local network. 

Don't use TURN**S** but TURN because Firefox will not support TURN**S**.

In your app config.js
  productionPort   : 443,
should point to servers 
  listeningPort         : 443,
Then you can run your server and build your application.
