### ISSUE TITLE
Server not working

### ISSUE THREAD

**Issue by cemkoker** [havfo/multiparty-meeting#265]
Followed the full install procedure and setup as a systemd service.
I see the login screen; and when I click 'Audio/Video' nothing happens ...

<img width="488" alt="Capture d’écran 2020-04-27 à 11 31 55" src="https://user-images.githubusercontent.com/13544103/80357103-bf97b680-887a-11ea-9963-cd708735cedc.png">

**Comment by misi** [comment]
Set in serve config 
requireSignInToAccess : false,

**Comment by cemkoker** [comment]
Thank you for the very quick reply; updated now i 'kinda' see the meeting but then right back to login : https://giphy.com/gifs/eHciWyXescnyz5s1fw/links

**Comment by cemkoker** [comment]
My turnserver.conf: 
server-name=xxx.com
cert=/etc/letsencrypt/live/xxx.com/cert.pem
pkey=/etc/letsencrypt/live/xxx.com/privkey.pem
realm=xxx.com
fingerprint
listening-ip=0.0.0.0
external-ip=<PUBLIC IP>/<INTERNAL IP>
listening-port=443
min-port=40000
max-port=49999
log-file=/var/log/turnserver.log
verbose

user=user:password
lt-cred-mech

**Comment by misi** [comment]
@cemkoker  check the js borwser console. 
I guess the web app can't reach the websocket server..

**Comment by misi** [comment]
It is not connected to TURN

**Comment by cemkoker** [comment]
Weird because I can reach the server with Trickle ICE
But in server log i see:
[pid:1796 RTC::PortManager::Bind() | throwing MediaSoupError: port bind failed due to address not available [transport:udp, ip:'x.x.x.x', port:44239, attempt:1/10000] +0ms

**Comment by havfo** [comment]
Have you configured server IP address here:
https://github.com/havfo/multiparty-meeting/blob/f083a407ea0b3bcdd93fb9e9f5e97ae5a3d8a6d4/server/config/config.example.js#L155

**Comment by misi** [comment]
@havfo  we need to state it more clear that 0.0.0.0 need to be replaced. Maybe we need to replace it with a documentation ip  e.g. 192.0.2.1

**Comment by cemkoker** [comment]
ok that was it; i was confused with 'which server' to put here; i did put the turn server by mistake. My bad. And yes; precising that it's the lan address is better. Thanks for your help works fine now !

**Comment by havfo** [comment]
@misi Yeah, let's change it to either a address that crashes or is invalid.
