### ISSUE TITLE
Chat/Participant flyout panel width

### ISSUE THREAD

**Issue by cap19** [havfo/multiparty-meeting#266]
Hi - on a 13' laptop the width of the flyout panel for chat, file sharing and participant list takes up ~40% of the screen size on the left side.

Where can I change this width in the code?

**Comment by havfo** [comment]
Change the widths in this CSS:
https://github.com/havfo/multiparty-meeting/blob/8a3cfb68de2c6188c8531614ef517f283cd49618/app/src/components/Room.js#L43

**Comment by misi** [comment]
@havfo  in app config.js you mean in theme=>overrides=> MuiDrawer =>`paper` rule ?
https://material-ui.com/api/drawer/

Am I right?

**Comment by cap19** [comment]
Hi - I made the change @havfo suggested and the width did compress but the effect is not desirable as the Participant text is then cut off.

I guess a better way would be to compress the whole flyout rather than just change the width. Thank you @havfo

**Comment by misi** [comment]
You can override all element width as I wrote above, chek css and adjust it.

**Comment by cap19** [comment]
Thank you @misi. This can be closed now from my perspective.
