### ISSUE TITLE
Mic, Camera and Share icon always visible in develop branch

### ISSUE THREAD

**Issue by cap19** [havfo/multiparty-meeting#267]
Hi - there seems to be a change in the develop branch vs. the master branch in terms of the vertical icons for mic, camera and share. These icons are always visible, even in the flimstrip view.

I feel the current implementation in master branch is cleaner. Users know where the icons are as they see it when the app launches.

Additionally, on flimstrip view, the icon don't fit nicely in the small strip at the bottom in a small laptop.

Is there a setting for this or something I can change in the code?

**Comment by misi** [comment]
It was this change because we got from some of the users that feedback that they don't find the buttons and even it is problematic on mobile. If you like we can make it configurable this, until it check the commits in dev for the change..
Do you want to make it configurable? If yes please send a PR and help us, we are busy with other features actually. Thanks for your cooperation!

**Comment by cap19** [comment]
Hi @misi 

I would like to definitely contribute. Although I'm not a full fledged developer, I can find my way through using Google to figure things out.

What files should I be looking at?

**Comment by Astagor** [comment]
One comment :-)
I think that when now the hiding of the controls is enabled, the text "You are muted, hold down SPACE-BAR to talk" will never appear. In my opinion this is like a toast message and should appear wherever the buttons ar shown or not.

**Comment by cap19** [comment]
@havfo thank you for implementing this. The screen is neat again  :)

**Comment by Astagor** [comment]
Thanks. I will test tomorrow.

**Comment by Astagor** [comment]
Works fine!

**Comment by cap19** [comment]
Currently "Hidden media control" setting controls the media buttons in the Me window. It does not have any effect on the participant window as the button(s) are hidden by default. They become visible on cursor over the window.

I wonder if "Hidden media control" setting is intended to work in this fashion?

**Comment by havfo** [comment]
Fixed in 02b6c617c5957c2c044ddc19cedff886fd07c7e5

**Comment by havfo** [comment]
That is by intent, but not something that is set in stone.

**Comment by Astagor** [comment]
I also think it is fine like this.

**Comment by cap19** [comment]
I feel it's little inconsistent. From a user perspective it would be nice to have a consistent hover over functionality. 

I know I can control it on my install. But just my thought...
