### ISSUE TITLE
Loudspeaker on Android's Firefox

### ISSUE THREAD

**Issue by DonPiotr** [havfo/multiparty-meeting#270]
Hi,
i saw that in android's Chrome i can choose audio device,
i can't do this same on Firefox because device's list is empty.

**Comment by so010** [comment]
Firefox does not support audio sink at the moment

**Comment by misi** [comment]
Not yet fully implemented. https://bugzilla.mozilla.org/show_bug.cgi?id=1498512
It is behind flag, with reason..
