### ISSUE TITLE
p-try@2.2.0 checking installable status

### ISSUE THREAD

**Issue by mehmetyeter** [havfo/multiparty-meeting#271]
Hello,
we preferred manual installation for multiparty-meeting but after /app/npm install command, process froze at the following status despite 2 attempt
p-try@2.2.0 checking installable status

Thanks.
Best Regards.

**Comment by cap19** [comment]
Hi - I just did manual reinstall on Ubuntu 19.10 from develop branch and it worked fine.

**Comment by misi** [comment]
If you have issues try the docker image.
It should work fine the manual install on debian 10 according my tests.

**Comment by misi** [comment]
try to update node version and checkout the latest code

**Comment by mehmetyeter** [comment]
I will try docker because process froze at the following again.
![image](https://user-images.githubusercontent.com/64595522/81286428-b7edc400-9069-11ea-90dc-194969398f69.png)
Thank you.

**Comment by mehmetyeter** [comment]
Hello, 
This problem is resolved l
first install yarn with npm : "npm install -g yarn" 
app/public/config/yarn install
server/public/config/ yarn install
Thanks.
