### ISSUE TITLE
Throw an error or handle wrongly provided protocol

### ISSUE THREAD

**Issue by bpcurse** [havfo/multiparty-meeting#273]
I was a bit tired when setting up mm late at night and set the multipartyServer setting in the app's config.js to `https://mm.mydomain.com`. When trying to join a room a click on `audio` or `audio and video` simply did nothing.

Is it possible to integrate a warning if a protocol has been mistakenly added to the FQDN, add a hint to the config file or simply strip it automatically?

Could something like this in /app/src/urlFactory.js work? (I am not experienced with javascript)
```
if (window.config.multipartyServer.indexOf("http://") !== -1) {
	const hostname = window.config.multipartyServer.substr(7);
}
else if (window.config.multipartyServer.indexOf("https://") !== -1) {
	const hostname = window.config.multipartyServer.substr(8);
}
else {
	const hostname = window.config.multipartyServer;
}
```

**Comment by cap19** [comment]
In the new design (develop branch), FDQN is not even required.... very slick !

**Comment by havfo** [comment]
Version 3.3 will be released next week, which means that this FQDN will not be required any more.
