### ISSUE TITLE
LICENSE.md

### ISSUE THREAD

**Issue by christian-2** [havfo/multiparty-meeting#274]
MIT License is currently referred to by name ("MIT") in `README.md`, but this is a bit hard to spot and does not meet GitHub's [best practice](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#determining-the-location-of-your-license). Hence `LICENSE.md` should be added to the repository from the[ license template](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository): MIT License, year: 2020, full name: GÉANT Association.

This will in particular [include](https://en.wikipedia.org/wiki/MIT_License) the statement: THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED ...

Please let me know if you welcome a PR to this effect.

**Comment by misi** [comment]
Yes please send a PR! Many Thanks for your contribution!!

**Comment by misi** [comment]
Many Thanks!
