### ISSUE TITLE
Logout not logging out completely it seems...

### ISSUE THREAD

**Issue by cap19** [havfo/multiparty-meeting#275]
How is logout designed to function? Currently it is partially working like LEAVE button.

I logged out from the room and closed the Chrome browser. Then, I opened a new browser and could initiate a new room as an authenticated user without logging in again. It seems like my logged in credentials were still stored in the browser. I wasn't truly logged out.

 I'm testing with Auth0 as oidc provider.

**Comment by Astagor** [comment]
Have you logged out form your oidc provider? Not only left the room and closed the browser.

**Comment by cap19** [comment]
Well, I log-in to OIDC provider from MM. The OIDC provider login window leads into the MM app once the login is successful. That's as far as OIDC goes. I don't have a separate OIDC logout functionality built anywhere in the app or the browser.

The only logout is in MM. In case of Google OIDC auth, it's little different when using Chrome.

What is the logout supposed to do in MM? 

Can something be added in OIDC config in MM to accommodate logout at OIDC provider as well?

**Comment by Astagor** [comment]
Logout in MM removes the user from the react session, but if your oidc did not log him out, then when he enters next room he gets reauthenticated by oidc and passport puts the user data again in the session. I think this happens in your scenario.

**Comment by havfo** [comment]
When you click log out in m-m, passport should log you out on the m-m server, and you should not be authenticated the next time you join.

You say that it works like a leave button, what do you mean? Logging out should not drop you out of a meeting.

**Comment by cap19** [comment]
Logout from m-m does not log me out from the m-m server. I can come right back in without logging again.

Additionally, when I login from the lobby screen, I return back to lobby screen instead of the meeting room. On the lobby screen my username and picture is updated from the OIDC provider. 

I tried to see how it works on letsmeet.no but OIDC is showing a blank screen there.

What I mean by logging out working partially like leave is that I can leave and come right back into the meeting again without logging in. Since logout is not logging me out of m-m server, I can leave/close the browser and came right back in without logging in again

**Comment by cap19** [comment]
Just fyi.... my test setup: HA Proxy and Redis on one server and 3 m-m nodes.

Setup works great expect for the logout issue. Not sure if cluster setup would impact logout in any way.

**Comment by cap19** [comment]
Another issue - after logout, Clear Chat, Clear files, mute all video, etc.  (logged in user features) are still available in the flyout panel.

**Comment by cap19** [comment]
@havfo when I use m-m in standalone mode on just one server, login and logout works fine.

When using it in cluster mode with HAProxy, login and logout features behave erratically as mentioned above. Any suggestions on what could be the issue?

**Comment by havfo** [comment]
Yes, so we need to add `roomId` to `logout` function in RoomClient to make the logout request arrive at the correct server in a load balanced scenario.

**Comment by cap19** [comment]
Ok, I think the same would have to be done for login function because it does not work in load balanced scenario from the lobby room. It randomly works when clicked a few times.
