### ISSUE TITLE
sudo apt install npm build-essential redis  errors

### ISSUE THREAD

**Issue by Klagio** [havfo/multiparty-meeting#276]
I installed nodejs v10, but after this I get as below

~$ sudo apt install npm build-essential redis
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: nodejs but it is not going to be installed
       Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
       Depends: node-ansi (>= 0.3.0-2) but it is not going to be installed
       Depends: node-ansi-color-table but it is not going to be installed
       Depends: node-archy but it is not going to be installed
       Depends: node-block-stream but it is not going to be installed
       Depends: node-fstream (>= 0.1.22) but it is not going to be installed
       Depends: node-fstream-ignore but it is not going to be installed
       Depends: node-github-url-from-git but it is not going to be installed
       Depends: node-glob (>= 3.1.21) but it is not going to be installed
       Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
       Depends: node-inherits but it is not going to be installed
       Depends: node-ini (>= 1.1.0) but it is not going to be installed
       Depends: node-lockfile but it is not going to be installed
       Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed
       Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
       Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
       Depends: node-gyp (>= 0.10.9) but it is not going to be installed
       Depends: node-nopt (>= 3.0.1) but it is not going to be installed
       Depends: node-npmlog but it is not going to be installed
       Depends: node-once but it is not going to be installed
       Depends: node-osenv but it is not going to be installed
       Depends: node-read but it is not going to be installed
       Depends: node-read-package-json (>= 1.1.0) but it is not going to be installed
       Depends: node-request (>= 2.25.0) but it is not going to be installed
       Depends: node-retry but it is not going to be installed
       Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
       Depends: node-semver (>= 2.1.0) but it is not going to be installed
       Depends: node-sha but it is not going to be installed
       Depends: node-slide but it is not going to be installed
       Depends: node-tar (>= 0.1.18) but it is not going to be installed
       Depends: node-underscore but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by sascha73** [comment]
Hi,
faced the same issues here.
Managed to cover them by using aptitude.
- apt install aptitude
- aptitude install npm build-essential redis

HTH
Sascha

**Comment by sascha73** [comment]
However when starting with "npm start"

i get

npm start
npm WARN npm npm does not support Node.js v10.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

**Comment by sascha73** [comment]
i had to install nodejs from the regular debian buster repos, which makes it nodejs 10.19.0.
If i install nodejs from https://deb.nodesource.com/setup_10.x the installation of npm and redis will fail because of some unmet dependencies.

**Comment by mertcelen** [comment]
Actual problem is debian packages which are old. First, you should follow instructions here https://github.com/nodesource/distributions/blob/master/README.md to install latest nodejs version.

Also you can update npm with `sudo npm install -g npm`

**Comment by misi** [comment]
@mertcelen  Thanks! I think there is no more open question here where we can help. 
Please open a new issue if you feel I missed sg here, and there is something we could help.

**Comment by durimjusaj** [comment]
I have the same problem.
Installed Node v13.14.0 ( Currently multiparty-meeting will only run on nodejs v13.x )

**Comment by mertcelen** [comment]
> I have the same problem.
> Installed Node v13.14.0 ( Currently multiparty-meeting will only run on nodejs v13.x ) - not working
> Installed Node v14.3.0 - not working

Current issue is about debian packages which is different than your problem. Could you share more information so we can help you.

**Comment by durimjusaj** [comment]
@mertcelen found a workaround just execute sudo apt install build-essential redis without git and npm and all good thnx :)

**Comment by misi** [comment]
@durimjusaj  @mertcelen 
We have issues with node 13, and 14. There is a random error we saw that does not occour on node 10.x please be aware of it. #255

**Comment by Kolanu-nikshith** [comment]
@durimjusaj  may i know what os you are using.

**Comment by misi** [comment]
@Kolanu-nikshith  We use Debian Linux.
