### ISSUE TITLE
Spotlight list browsing

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#286]
I have implemented the possibility to use the arrows keys (left and right) to iterate over the participates and put them into the spotlight, just as if I would click the participant on the participant list. This allows to quickly browse thought speakers that are currently passive and fix a chosen one on the screen. However, as I'm not a react programmer, the code is a bit clumsy, so you might want to implement it yourself.

**Comment by Astagor** [comment]
I have created a pull request
#291

**Comment by misi** [comment]
It is merged so I close this. 
The only open thing is here to review. @havfo @so010 please review it if you have time.
