### ISSUE TITLE
Add all from lobby button

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#287]
In the LockDialog.js should have a button to join all participants currently waiting in the lobby, so the moderator would not have to click so many times. Something like this:

`				lobbyPeers.length > 0 &&
				<Button
					disabled={!canPromote}
					onClick={(e) =>
					{
						e.stopPropagation();
						lobbyPeers.forEach(function(peerToPromoteId){
							let peerToPromote = lobbyPeersMap[peerToPromoteId]
							if (!peerToPromote.promotionInProgress) {
								roomClient.promoteLobbyPeer(peerToPromote.id);
							}
						});
					}}
					color='primary'>
					<FormattedMessage
						id='room.promoteAllInLobby'
						defaultMessage='Let all in'
					/>
				</Button>`

**Comment by havfo** [comment]
Good point!
