### ISSUE TITLE
Warning when building

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#305]
Compiled with warnings.

./src/components/VideoContainers/VideoView.js
  Line 7:10:  'green' is defined but never used                  no-unused-vars
  Line 13:8:  'SignalCellularAltIcon' is defined but never used  no-unused-vars

**Comment by misi** [comment]
Thanks! We decided to no show network condition indicator when it is normal. This is regression.
I will comment it out or delete it. Thanks!
