### ISSUE TITLE
Feature request - ability to own the meeting when there are several logged in users

### ISSUE THREAD

**Issue by cap19** [havfo/multiparty-meeting#307]
In an environment (school, NGO, etc.) where everybody can login to join a meeting, the user roles loses it significance.

Can there be a way for a person to take ownership of the meeting? Once they check a box or something, everyone else is still logged in or can login in, but they are like a Normal user.

The owner can be highlighted in the participant list.

**Comment by havfo** [comment]
We want to have this feature, but it is a bit difficult to implement a good solution for this at the moment when we have no persistent rooms. We might want to have some sort of "first come first serve" room owner role, and based on timestamp of joining this role will be passed on to the next in line if the owner leaves.

That said, we plan on freezing 3.3 this week, and hopefully release next week. In the next version we will have a room API that enables you to reserve rooms and own them. As an example, a teacher would then be able to reserve the room "Algebra 10a", and always be owner for that room, and set certain rules for the room.

**Comment by cap19** [comment]
There have been tons of upgrade in 3.3, which is super cool.

So, in the next version, will this API integrate with a calendar like Outlook for Google to schedule and reserve the room? It sounds like there will be some sort of m-m database.

In my opinion, "first come first serve" might not work well. e.g. teacher might be a few minutes late to the meeting, or students might game the system by always joining first. 

WebEx allows the host/owner role to be transferred to anyone in the participant list. Works quite well. They have persistent rooms to your point, so it's little different.

**Comment by havfo** [comment]
There will be an optional server role you can run. This will then act as an API for the main server and 3rd party applications or services to reserve and manage rooms.

The plan is that if you don't set up this optional server role, there will be no change to the experience that you have today.

**Comment by tapionx** [comment]
In my experience, based on the feedback at https//iorestoacasa.work, a moderation role to mute and kick intruders in needed in any case.

My suggestion is the following:
when the room is created, a random token is associated in redis to the room.
Users who connect with ?token=XXXXX in the URL as a get parameter have moderations role.

This way the secret moderation URL can be shared to others users.

**Comment by cap19** [comment]
Ok, got it. Then someone could write a plugin for Outlook to reserve and manage rooms.

Will there be m-m database in the future version?

**Comment by havfo** [comment]
> In my experience, based on the feedback at https//iorestoacasa.work, a moderation role to mute and kick intruders in needed in any case.
> 
> My suggestion is the following:
> when the room is created, a random token is associated in redis to the room.
> Users who connect with ?token=XXXXX in the URL as a get parameter have moderations role.
> 
> This way the secret moderation URL can be shared to others users.

The problem with this is that we don't have persistent rooms, so the token will not be valid before or after. Any token that we would produce would have to be valid for all rooms, and that would defeat the purpose of the token.

**Comment by Astagor** [comment]
Well, you can use fixed rooms in the current version, I have done it for my deployment. In config.js of the server, in the method userMapping I map usernames to room names. If a user is an owner of the room he gets the admin role, if not then authenticated role. Also I filter on nginx which room names are allowed, so nobody can create a room, so I have only owned fixed rooms.

**Comment by havfo** [comment]
> Ok, got it. Then someone could write a plugin for Outlook to reserve and manage rooms.
> 
> Will there be m-m database in the future version?

Yes, the new server role will include a default database (sqlite or something else), but with the option of configuring an external one (mysql or other SQL).

This database would then contain local users, rooms and potentially other data relevant to the service.

**Comment by cap19** [comment]
> > Ok, got it. Then someone could write a plugin for Outlook to reserve and manage rooms.
> > Will there be m-m database in the future version?
> 
> Yes, the new server role will include a default database (sqlite or something else), but with the option of configuring an external one (mysql or other SQL).
> 
> This database would then contain local users, rooms and potentially other data relevant to the service.

Awesome! Database opens this up to lots of opportunities. It keeps getting better  :)

**Comment by havfo** [comment]
> Well, you can use fixed rooms in the current version, I have done it for my deployment. In config.js of the server, in the method userMapping I map usernames to room names. If a user is an owner of the room he gets the admin role, if not then authenticated role. Also I filter on nginx which room names are allowed, so nobody can create a room, so I have only owned fixed rooms.

This sounds pretty much like the extent of what is possible today, you are using the `userMapping` function as intended. Nice to hear it being used.

**Comment by cap19** [comment]
> Well, you can use fixed rooms in the current version, I have done it for my deployment. In config.js of the server, in the method userMapping I map usernames to room names. If a user is an owner of the room he gets the admin role, if not then authenticated role. Also I filter on nginx which room names are allowed, so nobody can create a room, so I have only owned fixed rooms.

I love this suggestion. The only thing is then I/admin would have to constantly manage/update the config.js file for a large installation. But it will work for now!

**Comment by havfo** [comment]
@cap19 Remember that the `userMapping` function is an async function that can do lookups in a database or whatever.
