### ISSUE TITLE
suggestion - change microphone icon with speaker icon for other users

### ISSUE THREAD

**Issue by tapionx** [havfo/multiparty-meeting#308]
the "microphone" icon in the box of others users is misleading.
In my experience users do not understand that they are muting that user only for himself and not for everyone.
This could be mitigated changing that icon with a "speaker".

**Comment by havfo** [comment]
This has been fixed already in the `develop` branch commit 5c4eeb121a1bf16d1932d1a46e7da016c0ce8e60

**Comment by tapionx** [comment]
great!
