### ISSUE TITLE
suggestion - user media control buttons in bottom bar

### ISSUE THREAD

**Issue by tapionx** [havfo/multiparty-meeting#309]
in my experience users are not able to find the controls button inside their box.
we should follow the common pattern that already exists with similar software (Google Meet, Jitsi..):
a fixed bottom bar with controls button always visible, including a red "hang up" button

they could also be placed in the top bar, but on mobile there will not be enough orizontal space for everythng

**Comment by cap19** [comment]
Hi - in my opinion, horizontal media control buttons are preferable. It’s the norm. However, in Jitsi and other systems these buttons by default are not always visible. In Jitsi you can configure the bottom bar to be always visible I think. Otherwise by default when the user moves the cursor, it becomes visible. 

In the new branch these buttons are always visible like you want. Check letsmeet.no

**Comment by tapionx** [comment]
that's an improvement!

**Comment by Astagor** [comment]
No only always visible, the user can decide in setting if they should be always visible or only on cursor over his video.

**Comment by havfo** [comment]
I will make a setting available to have a separate control button bar

**Comment by Astagor** [comment]
You have killed the advance box on Me. It stopped to show the resolution and codecs.

**Comment by havfo** [comment]
Fixed! You are quick to test!

**Comment by nareshinstavc** [comment]
In Mobile when screen shared the button overlaps on the top of video. by adding this button on left made the video window becoming small. However we have option to not enable separate media controls.
I would suggest the buttons can be in buttom , but film strip video will block the controls.

I am attaching some screenshot of google meet how the layout looks 
![Screenshot 2020-05-07 at 6 38 00 PM](https://user-images.githubusercontent.com/14198671/81298402-5d1c9280-9092-11ea-95c1-603157736497.png)
![Screenshot 2020-05-07 at 6 38 18 PM](https://user-images.githubusercontent.com/14198671/81298406-5e4dbf80-9092-11ea-9908-dadbe4c1fbf6.png)

**Comment by Astagor** [comment]
One more bug. If the controls are in the separate toolbar, the translation is not working. On the video it is working.

**Comment by Astagor** [comment]
Would you fix the translations please.
