### ISSUE TITLE
Feature Request: ability for admin/moderator to remotely mute/disable video

### ISSUE THREAD

**Issue by L4ky** [havfo/multiparty-meeting#310]
Hi, 
i think it would be useful if admin and moderators could disable mic or video for a specific user from Participant List.
This action would be effective for everyone in the room.

Example: someone leaves mic open and makes a lot of noise. A moderator can mute him and no-one will hear him again until he unmute again.

Something like the "Mute All" button but for specific peer.

This would also require specific icons in the participant list to differentiate local mute from global mute.

**Comment by cap19** [comment]
Hi - this is cared for in the upcoming version. Moderator/admin can mute mic and video for all participants for chose from the list.

It's in the develop branch currently if you want to try it.

**Comment by havfo** [comment]
There is still no option to mute a single participant, only all, but we are working on it.

**Comment by L4ky** [comment]
I reached the goal, please see https://github.com/havfo/multiparty-meeting/pull/316

**Comment by cap19** [comment]
@L4ky Amazing! You rock!
