### ISSUE TITLE
Room based load Balancing with HAProxy 

### ISSUE THREAD

**Issue by chinthakadeshapriya** [havfo/multiparty-meeting#312]
Can solution make pipe between rooms on different hosts

**Comment by havfo** [comment]
Not at the moment, we are working in this in the feat-media-node branch. This will be included in the next version.

**Comment by chinthakadeshapriya** [comment]
You have done good job, Does the current version support piping between routers within different workers of the same host.?

**Comment by chinthakadeshapriya** [comment]
Also, when you will be expecting to release feat-media-node. Can we we install code in the current branch and test

**Comment by havfo** [comment]
> You have done good job, Does the current version support piping between routers within different workers of the same host.?

Yes, the current `develop` uses all available workers on a host for a meeting if it is big enough.

**Comment by chinthakadeshapriya** [comment]
Thanks
