### ISSUE TITLE
Feature request - ability to disable file sharing and chat through config file

### ISSUE THREAD

**Issue by cap19** [havfo/multiparty-meeting#314]
Most products offer this as owner configuration feature for each room.

Can this be done through config file at the install level in m-m? Especially the file sharing for security reasons.

**Comment by havfo** [comment]
There is a way to do this already, by setting the correct `userRoles` in the server config. The UI will still be present though (because someone in the room could have the right to send chat and files and you want to be able to receive it).

**Comment by Astagor** [comment]
Use the roles, Luke. ;-)
I think that the roles and permissions model is great. You can build your own scenarios of usage. And as you control the userMapping in server/config/config.js you exactly control, who gets which role in which room. I'm against putting everything as a config parameter, it will e a nightmare to manage.

**Comment by so010** [comment]
Agree with Astagor, when we have database back-end it will be available there as room config.

**Comment by cap19** [comment]
> There is a way to do this already, by setting the correct `userRoles` in the server config. The UI will still be present though (because someone in the room could have the right to send chat and files and you want to be able to receive it).

I know userRoles has this feature but it does not help when you have hundreds of users all from the same domain. It's hard to manage hundreds of users through their emails in the config.js file.

**Comment by havfo** [comment]
If you have the information about the the users somewhere else, the `userMapping` function can do a database lookup or API call to somewhere else for the data.

**Comment by cap19** [comment]
> Use the roles, Luke. ;-)
> I think that the roles and permissions model is great. You can build your own scenarios of usage. And as you control the userMapping in server/config/config.js you exactly control, who gets which role in which room. I'm against putting everything as a config parameter, it will e a nightmare to manage.

Dude -; checkout Jitsi or any other FOSS. It works because of it's flexibility and ability to configure each and every little thing through the config files. Of course they did it over the number of years as people requested it.

**Comment by Astagor** [comment]
Sure, but es there will be a release soon, I think now it is the time to concentrate on getting rid of all bugs in the current functionality and as so010 has written, more will come in the db version. Now, adding all things to config makes little sense. Better to have a well planned architecture with the db later on.

**Comment by cap19** [comment]
> If you have the information about the the users somewhere else, the `userMapping` function can do a database lookup or API call to somewhere else for the data.

My user information is in Google db or it could be any other OIDC offerings. These companies don’t give access to their db via api.

I totally understand and accept whatever you decide.

**Comment by havfo** [comment]
It is a feature I understand the need for, so it will get done probably, but probably not for this upcoming 3.3 version.

As for how to solve it right now, if I were you I would at least have the mail addresses in a separate file that `userMapping` could read. That way you wouldn't have to restart the server every time it changes.

**Comment by cap19** [comment]
Thank you @havfo Appreciate your support and suggestion.

m-m right now is simple to install and configure. I hope the future release simplifies it even more for people like me that are semi-technical. That I feel is the key for mass adaption.

**Comment by cap19** [comment]
> Sure, but es there will be a release soon, I think now it is the time to concentrate on getting rid of all bugs in the current functionality and as so010 has written, more will come in the db version. Now, adding all things to config makes little sense. Better to have a well planned architecture with the db later on.

Yeah, sure. Just remember bruv not everyone is as smart and talented as you.
