### ISSUE TITLE
Safari, screen sharing disabled

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#318]
Hi, why is the screen sharing disabled in Safari?

**Comment by havfo** [comment]
There is no support for sharing screen in Safari:

https://bugs.webkit.org/show_bug.cgi?id=186294

**Comment by Astagor** [comment]
OK, got it. But you know, it is extremely difficult to explain to Mac users that Safari does not have a feature that Chrome has :-)
Furthermore, I convinced the user to install Chrome, but in his system settings he does not see Chrome, to give it permissions to Mic and Cam. Without it, Chrome dose not even ask in MM, if we want to give access to mic and cam, as he does not have it in the system. Very strange, but yeah, it's a Mac.

**Comment by havfo** [comment]
There is unfortunately nothing we can do.
