### ISSUE TITLE
Make it posssible to have the chat fixed, instead of a flyout

### ISSUE THREAD

**Issue by bpcurse** [havfo/multiparty-meeting#320]
ATM the chat is a flyout and covers some of the participants.
In our use case the chat is important and we need to have it open all the time.

It would be great if there was an option to show the chat/participants list as a permanent part of the screen, that does not cover the other participants.

**Comment by bpcurse** [comment]
Wow, that was lightning fast :+1:  Thank you very much for your work, again!

**Comment by L4ky** [comment]
@havfo Unbelieable.. i was working on it right now! 
Obviously you coded it in a much better way ;)
Good job

**Comment by havfo** [comment]
Don't get used to everything getting fixed that fast :wink:

**Comment by Astagor** [comment]
You have already spoiled us all. LOL
