### ISSUE TITLE
How to check what room are being used?

### ISSUE THREAD

**Issue by helfio** [havfo/multiparty-meeting#329]
Hi, 

Is there a way to check what rooms are being used?
I found some not-very-skillful users to get into the wrong room...

Thanks

**Comment by Astagor** [comment]
Use the logging function in server/config/config.js there in develop you get a rooms and peer lists.

**Comment by Alex-YddeR** [comment]
I Tried to enable logs and also roles but ended up with errors , can you please send the sample config

**Comment by misi** [comment]
use the `server/connect.js --stats`

**Comment by havfo** [comment]
On a running server you may also connect to the console of the server. Simply run `npm run connect` in the server folder. From there you can do for example: `dumpRooms`

You can also run `t` in the console which brings you to a Javascript console where you can inspect the `rooms` and `peers` maps directly (handle with care!!!)

**Comment by helfio** [comment]
Thank you everyone!
I guess in case I have it deployed with dockers, I need to get a shell inside the container beforehand, right?
