### ISSUE TITLE
Impossible to access from outside

### ISSUE THREAD

**Issue by herbalizer404** [havfo/multiparty-meeting#330]
I followed the tutorial, I setup the app on my scaleway server but when I try start, event after shut down my firewall, no rules defined, it's impossible to do a telnet on every ports when outside the machine. when I do a netstat, i see that its listenning on 0.0.0.0:4443.

I dont understand what im doing wrong, do you have an idea?

**Comment by Astagor** [comment]
Put your public IP address in server/config/config.js. it is at the end of the file.

**Comment by herbalizer404** [comment]
here is my conf at the end, i replaced xxxprivate an xxxpublic.
Is there another parameter I forgot?

	webRtcTransport :
		{
			listenIps :
			[
				// change 192.0.2.1 IPv4 to your server's IPv4 address!!
				{ ip: 'x.x.x.private, announcedIp: 'x.x.x.public' }

				// Can have multiple listening interfaces
				// change 2001:DB8::1 IPv6 to your server's IPv6 address!!
				// { ip: '2001:DB8::1', announcedIp: null }
			],
			initialAvailableOutgoingBitrate : 1000000,
			minimumAvailableOutgoingBitrate : 600000,
			// Additional options that are not part of WebRtcTransportOptions.
			maxIncomingBitrate              : 1500000
		}

**Comment by herbalizer404** [comment]
also when I dont precise listeningHost: '0.0.0.0', 
When i do a netstat, i see its listening on tcp6.

**Comment by herbalizer404** [comment]
when i precise listeninhost my netstat:
tcp        0      0 0.0.0.0:4443            0.0.0.0:*               LISTEN      1244/multiparty-mee 
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1244/multiparty-mee 
tcp        0      0 127.0.0.1:41276         127.0.0.1:6379          ESTABLISHED 1244/multiparty-mee

**Comment by herbalizer404** [comment]
here is my entire config:
`
const os = require('os');

module.exports =
{

	// Auth conf
	/*
	auth :
	{
		lti :
		{
			consumerKey    : 'key',
			consumerSecret : 'secret'
		},
		oidc:
		{
			// The issuer URL for OpenID Connect discovery
			// The OpenID Provider Configuration Document
			// could be discovered on:
			// issuerURL + '/.well-known/openid-configuration'

			issuerURL     : 'https://example.com',
			clientOptions :
			{
				client_id     : '',
				client_secret : '',
				scope       		: 'openid email profile',
				// where client.example.com is your multiparty meeting server
				redirect_uri  : 'https://client.example.com/auth/callback'
			}

		}
	},
	*/
	redisOptions : {},
	// session cookie secret
	cookieSecret : 'T0P-S3cR3t_cook!e',
	cookieName   : 'multiparty-meeting.sid',
	tls          :
	{
		cert : `${__dirname}/certs/fullchain.pem`,
		key  : `${__dirname}/certs/privkey.pem`
	},
	// listening Host or IP 
	// If omitted listens on every IP. ("0.0.0.0" and "::")
	listeningHost: '0.0.0.0',
	// Listening port for https server.
	listeningPort         : 4443,
	// Any http request is redirected to https.
	// Listening port for http server. 
	listeningRedirectPort : 8080,
	// Listens only on http, only on listeningPort
	// listeningRedirectPort disabled
	// use case: loadbalancer backend
	httpOnly              : false,
	// WebServer/Express trust proxy config for httpOnly mode
	// You can find more info:
	//  - https://expressjs.com/en/guide/behind-proxies.html
	//  - https://www.npmjs.com/package/proxy-addr
	// use case: loadbalancer backend
	trustProxy           : '',
	// If this is set to true, only signed-in users will be able
	// to join a room directly. Non-signed-in users (guests) will
	// always be put in the lobby regardless of room lock status.
	// If false, there is no difference between guests and signed-in
	// users when joining.
	requireSignInToAccess : false,
	// This flag has no effect when requireSignInToAccess is false
	// When truthy, the room will be open to all users when the first
	// authenticated user has already joined the room.
	activateOnHostJoin    : true,
	// Mediasoup settings
	mediasoup             :
	{
		numWorkers : Object.keys(os.cpus()).length,
		// mediasoup Worker settings.
		worker     :
		{
			logLevel : 'warn',
			logTags  :
			[
				'info',
				'ice',
				'dtls',
				'rtp',
				'srtp',
				'rtcp'
			],
			rtcMinPort : 40000,
			rtcMaxPort : 49999
		},
		// mediasoup Router settings.
		router :
		{
			// Router media codecs.
			mediaCodecs :
			[
				{
					kind      : 'audio',
					mimeType  : 'audio/opus',
					clockRate : 48000,
					channels  : 2
				},
				{
					kind       : 'video',
					mimeType   : 'video/VP8',
					clockRate  : 90000,
					parameters :
					{
						'x-google-start-bitrate' : 1000
					}
				},
				{
					kind       : 'video',
					mimeType   : 'video/VP9',
					clockRate  : 90000,
					parameters :
					{
						'profile-id'             : 2,
						'x-google-start-bitrate' : 1000
					}
				},
				{
					kind       : 'video',
					mimeType   : 'video/h264',
					clockRate  : 90000,
					parameters :
					{
						'packetization-mode'      : 1,
						'profile-level-id'        : '4d0032',
						'level-asymmetry-allowed' : 1,
						'x-google-start-bitrate'  : 1000
					}
				},
				{
					kind       : 'video',
					mimeType   : 'video/h264',
					clockRate  : 90000,
					parameters :
					{
						'packetization-mode'      : 1,
						'profile-level-id'        : '42e01f',
						'level-asymmetry-allowed' : 1,
						'x-google-start-bitrate'  : 1000
					}
				}
			]
		},
		// mediasoup WebRtcTransport settings.
		webRtcTransport :
		{
			listenIps :
			[
				// change 192.0.2.1 IPv4 to your server's IPv4 address!!
				{ ip: 'x.x.x.private, announcedIp: 'x.x.x.public' }

				// Can have multiple listening interfaces
				// change 2001:DB8::1 IPv6 to your server's IPv6 address!!
				// { ip: '2001:DB8::1', announcedIp: null }
			],
			initialAvailableOutgoingBitrate : 1000000,
			minimumAvailableOutgoingBitrate : 600000,
			// Additional options that are not part of WebRtcTransportOptions.
			maxIncomingBitrate              : 1500000
		}
	}
};

`

**Comment by havfo** [comment]
If you are going to have HTTP server listen on all interfaces, simply remove the line
`listeningHost: '0.0.0.0',`

further, in:
```
listenIps :
	[
		// change 192.0.2.1 IPv4 to your server's IPv4 address!!
		{ ip: 'x.x.x.private, announcedIp: 'x.x.x.public' }

		// Can have multiple listening interfaces
		// change 2001:DB8::1 IPv6 to your server's IPv6 address!!
		// { ip: '2001:DB8::1', announcedIp: null }
	],
```

Set `announcedIp: null`, and change `ip` to your public IP.

**Comment by so010** [comment]
Find out your public IP and set it to the announcedIp: 'x.x.x.public' in config.

**Comment by enterux** [comment]
put two entries like this :

{ ip: 'x.x.x.private, announcedIp: 'null' },
{ ip: 'x.x.x.public, announcedIp: 'null' }

**Comment by misi** [comment]
I feel this question has been answered. If there is still open question open a new issue.
