### ISSUE TITLE
No voice after sometime when we connect blutooth headphones to laptop

### ISSUE THREAD

**Issue by Alex-YddeR** [havfo/multiparty-meeting#332]
It is observed that when we connect blutooth headphones to the laptop after some time we dont hear voice of the users. but it is verymuch continous when we remove the same.

Thanks

**Comment by misi** [comment]
@Alex-YddeR  We need much more details to be able to get after the issue. Collected logs versions, exact issues.
I use a Bluetooth headphone and it works fine for me.. Please open a new isse with more details.
