### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by squid46** [havfo/multiparty-meeting#334]
How to enable localization?

**Comment by so010** [comment]
It's always enabled. Set your browser (or OS) to preferred language and it should work.

**Comment by squid46** [comment]
> 
> 
> It's always enabled. Set your browser (or OS) to preferred language and it should work.

**Comment by squid46** [comment]
Everything is fixed - it doesn't work.

**Comment by squid46** [comment]
> 
> 
> It's always enabled. Set your browser (or OS) to preferred language and it should work.

Everything is fixed - it doesn't work.

**Comment by squid46** [comment]
It's always enabled. Set your browser (or OS) to preferred language and it should work.
All is set - it doesn't work.

**Comment by Astagor** [comment]
I can confirm, that it does work, what language are you trying to get?

**Comment by squid46** [comment]
ru. I created a ru.json translation file. Removed the app/build. Run "npm run build"

**Comment by Astagor** [comment]
You must add the translation to app/src/index.js if you add a new language.

**Comment by squid46** [comment]
Yes! Thanks.
