### ISSUE TITLE
Role based access control in develop branch

### ISSUE THREAD

**Issue by chinthakadeshapriya** [havfo/multiparty-meeting#339]
I deployed dev branch using ansible deployment and it working fine. How do we enable and use role based access control and test it

**Comment by havfo** [comment]
You need an OIDC provider. From the OIDC provider you get a userinfo object. After that, please see the examples in the server config on how to set up the usermapping function.

**Comment by chinthakadeshapriya** [comment]
Thanks. I tried OCID and  the DEV version with https://phantauth.net/_faker/.well-known/openid-configuration and working perfect. My confusion is  that how I can enable it in config file or in GUI ?

**Comment by Astagor** [comment]
You mean, how to enable login in the GUI? In app/public/config/config.js 
set loginEnabled     : true,

For the server part, you configure it in server/config/config.js

**Comment by Alex-YddeR** [comment]
Which part of server/config/config.js needs to changed for these user roles, because when i uncomment the code below code to enable roles i am getting errors in startup
/*
	// All authenicated users will be MODERATOR and AUTHENTICATED
	userMapping : async ({ peer, roomId, userinfo }) =>
	{
		peer.addRole(userRoles.MODERATOR);
		peer.addRole(userRoles.AUTHENTICATED);
	},
	// All authenicated users will be AUTHENTICATED,
	// and those with the moderator role set in the userinfo
	// will also be MODERATOR
	userMapping : async ({ peer, roomId, userinfo }) =>
	{
		if (
			Array.isArray(userinfo.meet_roles) &&
			userinfo.meet_roles.includes('moderator')
		)
		{
			peer.addRole(userRoles.MODERATOR);
		}
		if (
			Array.isArray(userinfo.meet_roles) &&
			userinfo.meet_roles.includes('meetingadmin')
		)
		{
			peer.addRole(userRoles.ADMIN);
		}
		peer.addRole(userRoles.AUTHENTICATED);
	},
	// All authenicated users will be AUTHENTICATED,
	// and those with email ending with @example.com
	// will also be MODERATOR
	userMapping : async ({ peer, roomId, userinfo }) =>
	{
		if (userinfo.email && userinfo.email.endsWith('@example.com'))
		{
			peer.addRole(userRoles.MODERATOR);
		}
		peer.addRole(userRoles.AUTHENTICATED);
	}
	// All authenicated users will be AUTHENTICATED,
	// and those with email ending with @example.com
	// will also be MODERATOR
	userMapping : async ({ peer, roomId, userinfo }) =>
	{
		if (userinfo.email && userinfo.email.endsWith('@example.com'))
		{
			peer.addRole(userRoles.MODERATOR);
		}
		peer.addRole(userRoles.AUTHENTICATED);
	},
	*/

Thanks

**Comment by havfo** [comment]
Please use code tag to format the code properly here, it is very difficult to see what is what, I fixed it for the previous one.

Those different versions of `userMapping` are different examples on what you might want. You need to provide **ONE** `userMapping` function that specifies the `userRoles` you want on the users you want.

**Comment by misi** [comment]
I think here are no more open questions. If there are please open new issues.
