### ISSUE TITLE
Improving mobile support

### ISSUE THREAD

**Issue by torjusti** [havfo/multiparty-meeting#34]
- [x] Sidebar button either does not allow clicks or is incredibly inresponsive when open
- [x] Sidebar is slow to open
- [x] Me is a little to slow to actually drag around
- [x] Peers have no vertical margins
- [ ] Displaying tooltips by mousemove is difficult
- [x] Sidebar is not wide enough and the buttons are incredibly, should probably cover the entire screen below a certain screen size
- [x] There is for some reason a vertical scrollbar
- [x] Notifications overlap with the tooltip for the share link button
- [x] Floating action buttons could be a bit bigger
- [ ] Consider disabling selection, as the `Copy` screen is a bit irritating and hard to remove sometimes
- [ ] Fullscreen button does not show a video
- [ ] Currently, Peer only shows tools when *hovering*

**Comment by havfo** [comment]
This is considered done for now. Creating new issue if we need.
