### ISSUE TITLE
Aggregated room size in Dev version

### ISSUE THREAD

**Issue by chinthakadeshapriya** [havfo/multiparty-meeting#341]
If we keep LastN=1, what will be combined (piped) room size in 8 core and 8 cpu media node

**Comment by Astagor** [comment]
In the current version of Dev, as peers in a single room can be served by all workers, the main limit you should worry about is the network bandwidth and the CPU power of a single core. So if you have set, that each user can produce a maximum of 1.5 Mbps and you have 1 Gbps connection, then take 800Mbps (as you should assume 80% of the link speed) and divide it through 1,5 =+- 533 users. Now you can make a test, how mamy users can a single core of your machine serve and the set the routerScaleSize in server/config/config.js accordingly. The default setting is 40, so on a 8 core machine you can get 320 users. But if you cores are faster, then you can set it higher. So I guess, with 1 Gbps and a medium 8 core machine, you are between 320 and 533 users. If I'm not wrong. :-)

**Comment by so010** [comment]
8 core = 16 threads = 16 workers

**Comment by Astagor** [comment]
Well, it depends, if it is a virtual machine in a data center then CPU is vCPU and then you get 8 workers.

**Comment by chinthakadeshapriya** [comment]
Thank you !!!

**Comment by chinthakadeshapriya** [comment]
Thanks
