### ISSUE TITLE
You are providing a disabled `button` child to the Tooltip component.

### ISSUE THREAD

**Issue by misi** [havfo/multiparty-meeting#343]
There are such errors in develop:

Me mute icon..

Material-UI: you are providing a disabled `button` child to the Tooltip component.
A disabled element does not fire events.
Tooltip needs to listen to the child element's events to display the title.

Add a simple wrapper element, such as a `span`. 
    in Tooltip (created by WithStyles(ForwardRef(Tooltip)))
    in WithStyles(ForwardRef(Tooltip)) (at Me.js:401)
    in Me (created by WithStyles(Me))
    in WithStyles(Me) (created by ConnectFunction)
    in ConnectFunction (at RoomContext.js:11)
    in Context.Consumer (at RoomContext.js:10)
    in Anonymous (at Democratic.js:163)
    in Democratic (created by WithStyles(Democratic))
    in WithStyles(Democratic) (created by ConnectFunction)
    in ConnectFunction (at Room.js:266)
    in Room (created by WithStyles(Room))
    in WithStyles(Room) (created by ConnectFunction)
    in ConnectFunction (at App.js:36)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Router.Consumer)
    in Router.Consumer (created by Route)
    in Route (at src/​index.js:206)

**Comment by misi** [comment]
I add a div around icons and fabs

**Comment by havfo** [comment]
Sorry for not commenting sooner, but we had an issue with this. If you wrap it in a div the tooltips will show even though the button is disabled. This might not be prefferable on all buttons.

**Comment by misi** [comment]
How can I reproduce it? I don't saw this issue. Do you have time to show me?

**Comment by cap19** [comment]
Hi, just fyi - not sure if the issue I'm seeing is tied to this fix. While testing something in three different browsers, I could no longer click on the mute button on Me window in all three tabs. Video and screen sharing buttons worked fine. All the buttons works fine on my install which is from this weekend's develop branch.

Upon changing the size of the browser the mute button became clickable again on letsmeet.no. 


![mute](https://user-images.githubusercontent.com/63865380/81866781-516b1900-9535-11ea-80c2-cd4f98e95679.png)
