### ISSUE TITLE
Moderator actions use the same string as not moderator

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#346]
In the participant list, the moderator actions (mute, mute video, mute screen share) use the same IDs from translation as the mute... only for me. They should be different, so the text can state ie. 'Mute audio for all'. Now you cannot distinguish what is what.

**Comment by L4ky** [comment]
I agree with you

Fixed in https://github.com/havfo/multiparty-meeting/pull/348

**Comment by Astagor** [comment]
OK, butt still as in #347 there is no button for mute screen sharing for all (for a single peer on the list) . You should either add it, but I think better is to reactivate the mute video and treat screen sharing as video.

**Comment by L4ky** [comment]
Already done. PR will arrive soon.

**Comment by misi** [comment]
@L4ky it is merged! 
All: Please update your translations..
@Astagor please close the issue if you agree
