### ISSUE TITLE
Screen share tool tip visible without the button

### ISSUE THREAD

**Issue by cap19** [havfo/multiparty-meeting#358]
After stopping screen share, the tool tip is still visible without the button (using hidden media control mode)

![share](https://user-images.githubusercontent.com/63865380/81827400-5791d300-94fe-11ea-9e07-e3937fa3ff36.png)

**Comment by misi** [comment]
Because it is jumping when we remove content.
We need to control it manually according this:
https://github.com/mui-org/material-ui/issues/12299

I will try to fix it.

**Comment by misi** [comment]
@cap19 Please check it!

**Comment by cap19** [comment]
@misi has the fix made it's way to letsmeet.no? I tested there and still ran into the same issue with tool tip in Chrome.

Additionally, not sure what's going on as resizing the browser to certain height and width disables to camera button for me now.  Thank you.

**Comment by havfo** [comment]
Not in letsmeet.no yet

**Comment by cap19** [comment]
Tested. The fix works.

**Comment by misi** [comment]
>Additionally, not sure what's going on as resizing the browser to certain height and width disables to camera button for me now. Thank you.
Please open a separate issue with full details and we can give try to dig into it and fix.

**Comment by Astagor** [comment]
Well, It happened today to me, label visible when button disappears. I have updated the version today.
![image](https://user-images.githubusercontent.com/11389003/82052283-acc71380-96bb-11ea-9a39-b5f878edfeb2.png)

**Comment by cap19** [comment]
Well, it works fine for me from yesterday's pull.

**Comment by cap19** [comment]
> > Additionally, not sure what's going on as resizing the browser to certain height and width disables to camera button for me now. Thank you.
> 
> Please open a separate issue with full details and we can give try to dig into it and fix.

@misi opened #370

**Comment by misi** [comment]
@Astagor If you could reproduce it please open a new issue with it. I can't find out how to reproduce with the latest develop

**Comment by Astagor** [comment]
#371
