### ISSUE TITLE
Adding back camera disables front camera in mobile

### ISSUE THREAD

**Issue by cap19** [havfo/multiparty-meeting#359]
In mobile:

1. turn on front camera; works fine
2. add back camera video
3. front camera me window becomes completely black
4. back camera works
5. close back camera me window
6. front camera me window is still completely black

![backcamera](https://user-images.githubusercontent.com/63865380/81846406-a5ff9b80-9517-11ea-80eb-f52c6c7e5bfa.png)

**Comment by Astagor** [comment]
I think it depends on the mobile. On my OnePlus5 I can use both at the same time.

![Screenshot_20200513-203539](https://user-images.githubusercontent.com/11389003/81851309-8a1ce980-9559-11ea-982b-e5fd9df1d715.jpg)

**Comment by cap19** [comment]
Interesting. Mine was on iPhone 8.

**Comment by enterux** [comment]
Works on my OnePlus and iPhone X

**Comment by cap19** [comment]
Thanks for testing guys. I'll try on other phones soon as well.

**Comment by YiPrograms** [comment]
Works fine on OnePlus 6 with Chrome
I can use both cameras at the same time

**Comment by cap19** [comment]
Tested on Samsung S10 and it works fine. Perhaps it's something with my iPhone.
