### ISSUE TITLE
requireSignInToAccess is not working

### ISSUE THREAD

**Issue by ray1422** [havfo/multiparty-meeting#361]
I've set requireSignInToAccess to true, but guest can still create and enter rooms.
In addition, it seems that it doesn't verify the response from auth issuer.
![image](https://user-images.githubusercontent.com/30434835/81854663-dcc5c800-9590-11ea-96bf-200e75e2a933.png)

**Comment by misi** [comment]
Which branch do you use? Master or develop. Please notice that in develop we moved to new auth options and there is no requireSignInToAccess

**Comment by ray1422** [comment]
It seems that I copied the wrnog config.example.js. 
but how should I configure that I just want to let signned in user create a room?
thanks!

**Comment by ray1422** [comment]
oh I got it.
I set 
`[BYPASS_LOBBY]     : [ userRoles.AUTHENTICATED ]`

**Comment by ray1422** [comment]
![image](https://user-images.githubusercontent.com/30434835/81858056-b8201f00-9595-11ea-8761-d9f1e5cf70d0.png)
as the image below, I've logged in but still can't create the room sometimes.
is it a bug?

**Comment by havfo** [comment]
You need to set the `userRole.AUTHENTICATED` to the user in question in the `userMapping` function.

**Comment by ray1422** [comment]
solved. thank you so much!
