### ISSUE TITLE
Astagor/browse_passive_users is borken in filmstrip

### ISSUE THREAD

**Issue by misi** [havfo/multiparty-meeting#362]
Filmstrip view: it doesn't display video stream if I use browse participant.

I tested Last-N=1, 
4 participant in the room

Unfortunately I am busy with other issues, and don't have time to look into it.
@Astagor please fix it until Friday, or I will revert it and we could not include it in the next release. :-/

![kép](https://user-images.githubusercontent.com/311629/81912254-9f802b00-95ce-11ea-95b7-1aa8dccc6776.png)

**Comment by misi** [comment]
@Astagor Also fix the `while(true)` and set it to a real different condition.
See `npm run lint`

**Comment by Astagor** [comment]
Done

**Comment by Astagor** [comment]
@misi I have crated a new PR.

**Comment by misi** [comment]
Thanks a lot for your fast fix. It is much better now. 
THX 1 more
