### ISSUE TITLE
WSS can't pass through NGINX proxy

### ISSUE THREAD

**Issue by ray1422** [havfo/multiparty-meeting#363]
I've built the server behind nginx with reversed proxy, but when I enter the room, I got the error message "WebSocket connection to `wss://........../socket.io/?peerId=xyyeshq5&roomId=kjbwvgax&EIO=3&transport=websocket&sid=YIUGjQLLcQ74oSSmAAAA` failed: Error during WebSocket handshake: Unexpected response code: 400"
any help?

**Comment by havfo** [comment]
Did you find a solution? In that case, could you please share it here in case others have the same issue. Thanks!

**Comment by Astagor** [comment]
I use this nginx config

location /socket.io/ {
	proxy_pass http://127.0.0.1:6080;
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection 'upgrade';
	proxy_read_timeout 86400;                
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Fowarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Fowarded-Proto $scheme;
	proxy_cache_bypass $http_upgrade;
	proxy_set_header X-NginX-Proxy true;
	proxy_redirect off;
	proxy_set_header Host $host;
}

location / {
	proxy_pass http://127.0.0.1:6080;
	proxy_http_version 1.1;
	proxy_read_timeout 86400;                
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Fowarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Fowarded-Proto $scheme;
	proxy_set_header X-NginX-Proxy true;
	proxy_redirect off;
	proxy_set_header Host $host;
}

in server/config/config.js:
 listeningPort         : 6080,
 httpOnly              : true,
 trustProxy           : 'loopback',
 listeningHost: '127.0.0.1',


But I had to make a small change to server.js as there was a problem in React in setting session cookie:
const session = expressSession({
	secret			: config.cookieSecret,
	name			: config.cookieName,
	resave			: true,
	saveUninitialized	: true,
	proxy			: config.trustProxy ? true : false,
	store			: new RedisStore({ client: redisClient }),
	cookie			: {
					secure   : config.trustProxy ? false : true,
					httpOnly : true,
					maxAge   : 60 * 60 * 1000 // Expire after 1 hour since last request from user
				  }
});

**Comment by ray1422** [comment]
here's my config. everything works.

```
server {
    server_name .......;
    location / {
        proxy_pass http://localhost:8888;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade"; 
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/......../fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/......./privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
```

**Comment by Astagor** [comment]
Well, but this means that the websocket connection is not working. Look in the Chrome console, you should have an error:

WebSocket connection to 'wss://......../socket.io/?peerId=8jklhxfw&roomId=test11&EIO=3&transport=websocket&sid=9Swz-AVw0-Xzj7FGAAAK' failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by ray1422** [comment]
No, I don't get the error. And I think it is using WS instead of pooling.

![image](https://user-images.githubusercontent.com/30434835/81965121-31794980-964a-11ea-8a39-fc9103bca9df.png)

**Comment by Astagor** [comment]
Hmm, let me try on my config.
