### ISSUE TITLE
Not working on Firefox

### ISSUE THREAD

**Issue by YiPrograms** [havfo/multiparty-meeting#365]
I'm using the latest develop branch to setup a new meeting server
It works on Chrome, Edge and Safari. However, I can't get it to work on Firefox

I've also set up coturn on the server and  add it to server's config.js:
```=js
    backupTurnServers : [
        {
            urls : [
                'turn:mm-meet.eastasia.cloudapp.azure.com:3478'
            ],
            username   : 'meet',
            credential : 'meetmeet'
        }
    ],
```
Firefox still says `ICE failed, add a STUN server and see about:webrtc for more details`
However I'm not sure whether it's turn server's problem because other browsers can connect even without turn servers

Here are some extra info:
Full server config.js: https://pastebin.com/TT0DQpyP
Firefox's about:webrtc log: https://pastebin.com/HqLTh7z0
Firefox version: 76.0.1 on Arch Linux
(Also tested with Firefox on Windows and other computers)

The server is at https://mm-meet.eastasia.cloudapp.azure.com, testing is appreciated  :heart:

Additional info: Firefox works fine on letsmeet.no

**Comment by cap19** [comment]
Your site worked for me in FF 76.0.1 in Windows.

**Comment by YiPrograms** [comment]
Can your Firefox connect to other peers?

**Comment by ray1422** [comment]
not working on my firefox either.
there's no error message until the second client joining.
![image](https://user-images.githubusercontent.com/30434835/82011307-315b6700-96a7-11ea-862f-5f8539d3fadd.png)

my `about:webrtc`:
```
SDP
Local SDP (Offer)
v=0
o=mozilla...THIS_IS_SDPARTA-76.0.1 6650463322493026578 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 E3:46:12:F8:86:83:D2:9D:CC:CC:31:C6:FB:2D:E8:84:1D:78:64:E0:BC:05:4D:91:D3:DC:15:E7:A7:FD:63:F5
a=group:BUNDLE 0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 58691 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 10.0.0.4
a=candidate:0 1 UDP 92217343 10.0.0.4 58691 typ relay raddr 10.0.0.4 rport 58691
a=candidate:0 2 UDP 92217342 10.0.0.4 54107 typ relay raddr 10.0.0.4 rport 54107
a=sendonly
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:b216b5c01cc627443322a1ff97ecc381
a=ice-ufrag:21e861c3
a=mid:0
a=msid:{c7f81f12-c8d8-404a-94ba-9986648a6426} {b89ae09c-df7a-4373-9ac0-f6bcd62c7985}
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:4166219292 cname:{c1bcdb47-edbb-4846-a2cc-47a5344f664f}

Remote SDP (Answer)
v=0
o=mediasoup-client 10000 1 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-512 FB:2C:F0:8C:28:2C:EA:5F:11:93:C3:09:33:40:FC:03:45:26:5B:52:16:11:7C:4B:4C:8A:6C:DD:14:71:C4:FF:FA:2F:8B:71:F4:CC:6C:B4:04:DA:36:96:0D:0B:F7:3F:5E:CB:F3:99:D6:DA:C1:B1:3D:A0:21:C9:47:23:3A:4D
a=group:BUNDLE 0
a=ice-lite
a=msid-semantic:WMS *
m=audio 7 UDP/TLS/RTP/SAVPF 109
c=IN IP4 127.0.0.1
a=candidate:udpcandidate 1 udp 1076302079 mm-meet.eastasia.cloudapp.azure.com 45580 typ host
a=recvonly
a=end-of-candidates
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=fmtp:109 maxplaybackrate=48000;stereo=0;useinbandfec=1
a=ice-options:renomination
a=ice-pwd:3h8z1ucqcjgdexdt4q1oujtbdwxi3qae
a=ice-ufrag:ecnu0ljpzij8twcw
a=mid:0
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=setup:passive
```

**Comment by misi** [comment]
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
check your turn relay. It gives back 10.0.0.4 as global address that is definitely not global ipv4.
If you related to NREN community I can provide you a free TURN service

**Comment by YiPrograms** [comment]
Thanks for your help, but I'm hosting this for personal use
I've fixed(?) my turn server, now it uses global ip
![image](https://user-images.githubusercontent.com/16501891/82020703-2eb73c80-96bc-11ea-89c6-a92f28961886.png)
and this is my coturn config:
```
fingerprint
lt-cred-mech
listening-ip=10.0.0.4
external-ip=mm-meet.eastasia.cloudapp.azure.com/10.0.0.4
min-port=50000
verbose
realm=mm-meet.eastasia.cloudapp.azure.com

user=meet:meetmeet
```

But I am still unable to connect to other peers
Here is my new webrtc log: https://pastebin.com/SCWUAnHc

**Comment by misi** [comment]
In FF there is an ICE negotiation issue. https://bugzilla.mozilla.org/show_bug.cgi?id=1034964 
It still use the deprecated aggressive nomination that causing issue with ICE lite. 
As workaround we enforce turn usage in case of Firefox. If your TURN works properly it should work properly in theory.

**Comment by misi** [comment]
I opened an issue to #383 to make ICE negotiation smarter, and I hope it will also help you to run it in private. I will close this, because I think we can't help more here.
