### ISSUE TITLE
Safari MacOS Problems

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#366]
Some users report that on MacOS Wand Safari they get a white screen. I thought it was only a problem of iOS. On my Mac and Safari it works, so there must be a version of Safari or combination Safari version- MacOS version that does not work?
Do you have of tested systems/browsers?

**Comment by misi** [comment]
Can you describe the exact browser string?

**Comment by Astagor** [comment]
Unfortunately, not. The teacher has reported this, said what a student reported her about his problems.

**Comment by misi** [comment]
My PR #344 will at least help on the white screen on unsupported versions of safari.

**Comment by Astagor** [comment]
Great, thanks! You know I have now on my 3 instances about 300 users in total, so I get A LOT of strange reports of bugs.

**Comment by misi** [comment]
I can't help you more on this...

**Comment by Astagor** [comment]
I know.... thanks.
