### ISSUE TITLE
Strange text showing up

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#369]
One user reported 2 strange things, it was a German user:

- instead of "Video gestoppt" he had "Video basiert". I have checked the German translation and all the files but the word "basiert" is not in the application.

- second thing, during the call he got few times the message on the blue boxes "Der Raum wurde erstellt", which means the room has been created, but I do not also see this text anywhere in the app....

I would say he is crazy, but I got a Foto from him with the "Video basiert".

Any ideas?

**Comment by havfo** [comment]
Probably an older translation that has since changed.

**Comment by Astagor** [comment]
But how? It is a fresh build, I have searched using grep for the text in the whole app folder looking for the string.
But also what is the text about, the room being created, coming in the middle of the session? I have never seen such a message.

**Comment by mi4aux** [comment]
some browser cache issue? some missing/wrong translation (on old cached files) in combination with "translate this site" option ... my guess ... don't remember exactly, but saw something similar (same) on testing some day (march/april) ...

**Comment by Astagor** [comment]
I have reproduced the first thing "Video basiert". It is google translate, although the page is in German, it recognizes it as being in English and translates German to Wrong German....  So, maybe in the HTML, we should set what language it is... as currently google translate built in chrome, ruins the translations.

**Comment by Astagor** [comment]
Pleas insert in app/src/index.js line 102:
document.documentElement.lang = locale;
This fixes the problem

**Comment by havfo** [comment]
Thank you very much!
