### ISSUE TITLE
Camera button does not work when the layout changes

### ISSUE THREAD

**Issue by cap19** [havfo/multiparty-meeting#370]
In Chrome, I start with democratic view and there is Me and 2 guests. The 3 windows are arranged horizontally next to each other.

![first](https://user-images.githubusercontent.com/63865380/82060171-9eadce80-968c-11ea-8b6c-638af0100a72.png)

Then I change the browser size (because I want Notepad next to Chrome).  Now, there is Me and 1st Guest in the top row and 2nd Guest in the second row.

![second](https://user-images.githubusercontent.com/63865380/82060181-a3728280-968c-11ea-8709-3b896bfd7558.png)

When I try to click on the camera button in Me window, nothing happens. And, there is no tool tip display either. Mute and Share buttons work fine.

**Comment by misi** [comment]
@havfo @so010 me-ptt element is hiding it. What is your suggestion?

**Comment by Astagor** [comment]
I think, that the old way, when me-ptt was displayed only on the ME screen was better. Now it disturbs, when watching other videos and having background noise.

**Comment by misi** [comment]
I agree with @Astagor it was better on the only ME screen.
For a quick fix until it will be fixed more properly I hide the element..

**Comment by misi** [comment]
Please check my quick fix..

**Comment by cap19** [comment]
Wondering if there is beta or test version of letsmeet.no where all the fixes are pushed immediately?

I don't have a test system and my pulls into prod are on a weekly basis.
