### ISSUE TITLE
Flashing lobby alert is subdued when the toolbar menu is collapsed

### ISSUE THREAD

**Issue by cap19** [havfo/multiparty-meeting#375]
On a mobile phone / tablet or any smaller screen, the flashing lobby alert is not visible when the menu icons are collapsed under the three dots.

**Comment by misi** [comment]
I added to top-bar the lobby waiting icon back.
So now if room locked somebody arrives you can see on both in the additional list and on the top bar that someone waiting for a decision.

Please check and feedback
@cap19 @havfo

**Comment by cap19** [comment]
@misi the waiting icon works now when the menu is collapsed. 

However a side effect: when you expand the browser to see the full menu, there are two waiting icons now.

**Comment by Astagor** [comment]
In my opinion the waiting room icon should be always in the top bar, even on mobile, and not on the drop down list. This is an action button, that only shows up for some time and requires action.

**Comment by cap19** [comment]
Agree @Astagor it's redundant in the drop down list.

**Comment by misi** [comment]
It is fixed..

**Comment by Astagor** [comment]
I don't see a commit with it
