### ISSUE TITLE
Question - how to redirect when the user hits Leave?

### ISSUE THREAD

**Issue by cap19** [havfo/multiparty-meeting#377]
What file(s) require modification to change the Leave button action?

 I'm trying to redirect users to a URL to collect meeting feedback via a simple survey. It could be googleforms, survey monkey, etc.

**Comment by havfo** [comment]
The redirect happens here:
https://github.com/havfo/multiparty-meeting/blob/2e552fb07dd84fd87b7606bc71f6f9624705f451/app/src/RoomClient.js#L267

**Comment by cap19** [comment]
Thank you @havfo
