### ISSUE TITLE
Question-How to add authentication?

### ISSUE THREAD

**Issue by rvigneshw** [havfo/multiparty-meeting#387]
I'm new to this and  I want to either 
1.Modify the ChooseRoom.js Dialog to have also E-mail and password 
2.How to implement the OpenID configuration.

[I have already developed an API end point which gives a JWT token for successful login attempt]

**Comment by cap19** [comment]
OIDC is configured through the server config file

https://github.com/havfo/multiparty-meeting/tree/master/server/config
