### ISSUE TITLE
Lobby icon shown 2 times on desktop

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#390]
![image](https://user-images.githubusercontent.com/11389003/82310688-03d32e00-99c5-11ea-986d-12e84e448de4.png)

**Comment by misi** [comment]
Fixed! Thanks for the report!

**Comment by cap19** [comment]
Is this same as one reported yesterday?  https://github.com/havfo/multiparty-meeting/issues/375#issuecomment-630221710

**Comment by misi** [comment]
@cap19  Yes, my fault, but now it is fixed correctly
