### ISSUE TITLE
Wrong label muteScreenSharing

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#391]
RoomClient.js line 2661 is 
id             : 'moderator.muteScreenSharingModerator',

should be
id             : 'moderator.muteScreenSharing',

**Comment by Astagor** [comment]
On the commit from today the moderator.muteScreenSharing has been replaced in the code by moderator.stopScreenSharing.

So moderator.muteScreenSharing can be now removed from translations, as it is unused.

**Comment by misi** [comment]
Fixed! @Astagor Many many Thanks! Check and close.. :)

**Comment by Astagor** [comment]
It's good
