### ISSUE TITLE
autoMuteThreshold bug

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#394]
In RoomClient.js in line 3048 you have
const { autoMuteThreshold } = store.getState().settings;

but this is wrong, as it reads the autoMuteThreshold from the store, not the config. So once set in the reducer, it cannot be changed in config, unless the user clears his local storage in the browser. 

It should be 

let autoMuteThreshold = 4;
if ('autoMuteThreshold' in window.config) { //as 0 is also a valid value
    autoMuteThreshold = window.config.autoMuteThreshold;
}
@misi

**Comment by Astagor** [comment]
And there is a second bug in the next line
if (autoMuteThreshold && peers.length > autoMuteThreshold)

it should be 
if (autoMuteThreshold && peers.length + 1 > autoMuteThreshold)

as the peer that is joining is not yet on peers list, so now if you set autoMuteThreshold =1 in config it will never work, always 2 will be unmuted, and we wanted 1. 

I also thinking that it should be like this:
-1 - unlimited
0 - all muted
x - (where x >0) - x unmuted, rest muted

**Comment by so010** [comment]
Thanks for catching!

**Comment by Astagor** [comment]
Looks good, thanks!
