### ISSUE TITLE
Regression - changing video device not working on ME, but it did

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#398]
Scenario, I have 2 webcams, Cam1 and Cam2. Cam1 is default in MM.
I have Skype using Cam1. I enter a MM room, Cam1 is default, so I get the warning, that the camera could not be accessed. So far so good. I go into settings and choose Cam2 as my camera. On the ME screen I see no video from my Cam2, but the remote participants can see my video. So there is a bug on the ME screen. Maybe it is related to the bug with changing of the audio device #395

**Comment by Astagor** [comment]
Works also for me FF 76.0.1.

**Comment by Astagor** [comment]
For me this and #395 are critical, as I have it already deployed for my users. :-(

**Comment by havfo** [comment]
Will look into this.

**Comment by Astagor** [comment]
Thanks!

**Comment by havfo** [comment]
Please check if 0654acded86c06382876d45885059c201aeb7173 fixes this.

**Comment by Astagor** [comment]
Works! Thanks.
