### ISSUE TITLE
RaiseHand button

### ISSUE THREAD

**Issue by so010** [havfo/multiparty-meeting#40]
- [ ] don't show if participants < 3
- [ ] set raiseHandStatus to false for all participants if participant number decreases to 2
- [ ] configuration option for enable/disable "raise hand" in config

**Comment by bpcurse** [comment]
This feature would really help us a lot, the only problem is I cannot find this setting in the config files, the readme or the changelog.
If it already is in the code (there seems to be no commit linked here), could you please add the commented option to the config file and if possible to the readme?

Thank you very much for this great tool!

**Comment by havfo** [comment]
Will add raise hand back. It was removed during the migration to material ui, but there seems to be interest for it. All the logic is still in place, it simply needs to be added back in the UI.

**Comment by Astagor** [comment]
Please add sound notification and flashing number, like in the case of chat message or file sharing.

**Comment by Astagor** [comment]
Sorry for being a pain in the ass. :-)

**Comment by havfo** [comment]
Your input is very good, keep it coming :)
