### ISSUE TITLE
openid nginx problem

### ISSUE THREAD

**Issue by himpierre** [havfo/multiparty-meeting#400]
Hi Devs.

Got openid running successfully but when i put a nginx in front of my installation i get this
after beeing redirected from a successfull login via keycloak.. Any ideas whats going wrong here?

```
Error: did not find expected authorization request details in session, req.session["oidc:kc.fluffycloud.de"] is undefined
    at /home/himbeere/multiparty-meeting/server/node_modules/openid-client/lib/passport_strategy.js:126:13
    at OpenIDConnectStrategy.authenticate (/home/himbeere/multiparty-meeting/server/node_modules/openid-client/lib/passport_strategy.js:174:5)
    at attempt (/home/himbeere/multiparty-meeting/server/node_modules/passport/lib/middleware/authenticate.js:366:16)
    at authenticate (/home/himbeere/multiparty-meeting/server/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at Layer.handle [as handle_request] (/home/himbeere/multiparty-meeting/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/himbeere/multiparty-meeting/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/himbeere/multiparty-meeting/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/himbeere/multiparty-meeting/server/node_modules/express/lib/router/layer.js:95:5)
    at /home/himbeere/multiparty-meeting/server/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/himbeere/multiparty-meeting/server/node_modules/express/lib/router/index.js:335:12)
```

thanks and cheers

**Comment by misi** [comment]
Something went wrong when you match your callback with request based on cookie.
Please explain more without it we can't help more. 
Try to check your OIDC settings..

**Comment by himpierre** [comment]
Hi @misi, thanks for your answer. What information you like me to provide you with? Here is my server config.js:

```
        auth :
        {
                oidc:
                {
                        // The issuer URL for OpenID Connect discovery
                        // The OpenID Provider Configuration Document
                        // could be discovered on:
                        // issuerURL + '/.well-known/openid-configuration'

                        issuerURL     : 'https://kc.fluffycloud.de/auth/realms/fluffy/.well-known/openid-configuration',
                        clientOptions :
                        {
                                client_id     : 'multiparty-meeting',
                                client_secret : 'client secret redacted',
                                scope                   : 'openid email profile',
                                // where client.example.com is your multiparty meeting server
                                redirect_uri  : 'https://meeting.fluffycloud.de/auth/callback'
                        }

                }
        },
```

Attached the keycloak settings. Thanks again.

![image](https://user-images.githubusercontent.com/40269193/82642815-cb269500-9c0e-11ea-96cc-298a68eb61d5.png)

**Comment by himpierre** [comment]
my nginx settings:

```
    location / {
        proxy_pass "http://127.0.0.1:8000";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Proto https;
}
```

**Comment by L4ky** [comment]
In server confg.js the issuerURL is wrong.
You need to add keycloak port in the URL, standard is 8443 so your issuerURL will be:

`https://kc.fluffycloud.de:8443/auth/realms/fluffy/.well-known/openid-configuration`

**Comment by himpierre** [comment]
@L4ky hm? the keycloak server is not listening on port 8443.

**Comment by misi** [comment]
@himpierre 
In server config the:
``` 
redirect_uri  : 'https://meeting.fluffycloud.de/auth/callback'
```
And keycloak 
`Valid redirect URI should be the same`

**Comment by misi** [comment]
Ans also issuer url should not contain the `.well-known/openid-configuration` just https://kc.fluffycloud.de/auth/realms/fluffy/

**Comment by himpierre** [comment]
@misi Thanks for taking the time. 

`redirect_uri ` and `Valid Redirect URIs` are the same. Both is set to https://meeting.fluffycloud.de/auth/callback. I also `.well-known/openid-configuration`. 

Problem is still the same. Any other ideas?

**Comment by himpierre** [comment]
@misi why is MM complaining about `req.session["oidc:kc.fluffycloud.de"] is undefined`? Is there some header gone missing using nginx maybe?

**Comment by misi** [comment]
@himpierre It looks for session cookie and tries to restore session and pair the response with the reqest..

**Comment by himpierre** [comment]
@misi And somehow this cookie goes missing when using a loadbalancer. I see. How can i help you to debug this? Do you need access to the virtual machines? It's all testing stage only.

**Comment by himpierre** [comment]
Uahh. `trustProxy           : 'loopback',` seems to solve my problem. I'm testing a little bit more.

**Comment by himpierre** [comment]
Yes. That fixed that problem. :exploding_head:
