### ISSUE TITLE
[Question-Efficiency] How many simultaneous rooms and users can this handle?

### ISSUE THREAD

**Issue by rvigneshw** [havfo/multiparty-meeting#405]
When hosted on a VM having single core CPU and 4Gigs of RAM

**Comment by Astagor** [comment]
Depends on the Core speed, and how you configure the room parameters, like lastN and maxLastN. But it should be between 30 and 60.

**Comment by cap19** [comment]
See this and there are few open and closed discussions on topic already. 

https://github.com/havfo/multiparty-meeting/wiki/Scaling-and-recommended-Hardware

**Comment by rvigneshw** [comment]
Thanks :-)
