### ISSUE TITLE
Feature: Put the FPS and quality in advanced

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#415]
I think that like for audio and echo cancelling and so on you have the advanced section, this should be also for FPS and quality. No normal user will know what to do with this. 
Also I think that changing resolution for Screen Sharing is a bad idea. Before it was auto set by the browser depending on the resolution of the window. Now, if I change in options, the content is cut off, as the lower resolutions are 4:3 , but most screens are 16:9. I would let the browser take care of the resolution of screen sharing and NOT let the user change it. Now the user by setting medium destroys the screen sharing. The browser stops to auto scale the resolution if I resize the window being shared.

**Comment by Astagor** [comment]
What about that a user can now destroy screen sharing when choosing a resolution and stops the browser from auto setting the resolution based on the actual size of the shared window?

**Comment by havfo** [comment]
Ah, forgot about that, yes, we might want to remove this option.

**Comment by havfo** [comment]
Also removed video frame rate. Should be enough with screen sharing frame rate.
