### ISSUE TITLE
how do i un-mirror local video

### ISSUE THREAD

**Issue by Alex-YddeR** [havfo/multiparty-meeting#419]
Where should i change the parameter so that i don't want to see mirrored self video. want to see the same video how it looks to other user.

**Comment by havfo** [comment]
Remove this line:

https://github.com/havfo/multiparty-meeting/blob/46a2c075f03a7e348ecfbc34ba425cc458f5f3a0/app/src/components/VideoContainers/VideoView.js#L41

**Comment by Alex-YddeR** [comment]
Thank you
