### ISSUE TITLE
Connected with google oauth2 but no moderator privilege

### ISSUE THREAD

**Issue by verbavolant** [havfo/multiparty-meeting#420]
Hi!
I've enabled oidc with google, i can login correctly but i can't give to auth user "moderator" id
I must see something in the screen that identify me as moderator?

i've this in config.js:
userMapping : async ({ peer, roomId, userinfo }) =>
{
     peer.addRole(userRoles.MODERATOR);
     peer.addRole(userRoles.AUTHENTICATED);
},                       

thanks!

**Comment by havfo** [comment]
What does your `permissionsFromRoles` look like?

**Comment by verbavolant** [comment]
Default:
        permissionsFromRoles : {
                // The role(s) have permission to lock/unlock a room
                [CHANGE_ROOM_LOCK] : [ userRoles.MODERATOR ],
                // The role(s) have permission to promote a peer from the lobby
                [PROMOTE_PEER]     : [ userRoles.NORMAL ],
                // The role(s) have permission to send chat messages
                [SEND_CHAT]        : [ userRoles.NORMAL ],
                // The role(s) have permission to moderate chat
                [MODERATE_CHAT]    : [ userRoles.MODERATOR ],
                // The role(s) have permission to share screen
                [SHARE_SCREEN]     : [ userRoles.NORMAL ],
                // The role(s) have permission to produce extra video
                [EXTRA_VIDEO]      : [ userRoles.NORMAL ],
                // The role(s) have permission to share files
                [SHARE_FILE]       : [ userRoles.NORMAL ],
                // The role(s) have permission to moderate files
                [MODERATE_FILES]   : [ userRoles.MODERATOR ],
                // The role(s) have permission to moderate room (e.g. kick user)
                [MODERATE_ROOM]    : [ userRoles.MODERATOR ]
        },

**Comment by havfo** [comment]
Do you have the red buttons in the top in the participant list in the side drawer?

**Comment by verbavolant** [comment]
Nothing...

![image](https://user-images.githubusercontent.com/27216842/82787289-636a8700-9e66-11ea-8501-f63374d245da.png)

**Comment by misi** [comment]
@verbavolant  can you please share your config, and please test it with the latest 3.3 version.

**Comment by verbavolant** [comment]
@misi i'm using lastest 3.3 git

Here are my configs, thanks a lot!
[mm.tar.gz](https://github.com/havfo/multiparty-meeting/files/4675877/mm.tar.gz)

**Comment by havfo** [comment]
I see you have `userMapping` defined twice, please remove one of them.

**Comment by verbavolant** [comment]
Ok now it works, thanks a lot.
I need to merge the userMappings if i want to use name ad image from oauth2, so is better to insert in the config.example.js:

        userMapping           : async ({ peer, roomId, userinfo }) =>
        {
                peer.addRole(userRoles.MODERATOR);
                peer.addRole(userRoles.AUTHENTICATED);
 
               if (userinfo.picture != null)
                {
                        if (!userinfo.picture.match(/^http/g))
                        {
                                peer.picture = `data:image/jpeg;base64, ${userinfo.picture}`;
                        }
                        else
                        {
                                peer.picture = userinfo.picture;
                        }
                }

                if (userinfo.nickname != null)
                {
                        peer.displayName = userinfo.nickname;
                }

                if (userinfo.name != null)
                {
                        peer.displayName = userinfo.name;
                }

                if (userinfo.email != null)
                {
                        peer.email = userinfo.email;
                }
        },
