### ISSUE TITLE
ability for Prometheus exporter to listen on localhost

### ISSUE THREAD

**Issue by christian-2** [havfo/multiparty-meeting#421]
* add property `prometheus.listen` to `server/config.js`
* similar e.g. to [`listen_addresses`](https://www.postgresql.org/docs/current/runtime-config-connection.html) in PostgreSQL
* if not set, exporter listens on all available IP interfaces (default; current semantics)
* if set to `localhost`, exporter listens only on loopback interface
* in preparation for misi/mm-ansible#7, related to #381: when playbook shall install MM together with Prometheus and Grafana, let it restrict exporter to `localhost` and expose Grafana (thru firewall, across HTTPS, with password) instead

**Comment by christian-2** [comment]
(assign: self)

**Comment by misi** [comment]
:) :1st_place_medal:

**Comment by christian-2** [comment]
@misi You may also assign this to me, if the project/platform supports this.

**Comment by misi** [comment]
Sorry again for the delayed merge.
