### ISSUE TITLE
Moderator "mute all" active when someone joins

### ISSUE THREAD

**Issue by verbavolant** [havfo/multiparty-meeting#424]
Hello!
Il would be nice if "mute all" option (for moderator) can mute also those who enter later.
thanks!

**Comment by misi** [comment]
It is already addressed by the https://github.com/havfo/multiparty-meeting/blob/85d7c7f94d699d8fabbd75bee86c941d7f144913/app/public/config/config.example.js#L111
In below of this threshold 4, the moderator could easily handle this.

**Comment by verbavolant** [comment]
Uh! Missed! @misi thanks!
