### ISSUE TITLE
Option requireSignInToAccess not working in 3.3

### ISSUE THREAD

**Issue by himpierre** [havfo/multiparty-meeting#427]
Hi Devs.

Just upgraded to 3.3. Great work! But now i'm not forwarded anymore to my keycloak server. It's possible now to enter a room without authentication. Any ideas whats going on here? server config.js is unchanged from 3.2.

thanks and cheers, t.

**Comment by havfo** [comment]
You need to change your config. Take a look at the example config, `requireSignInToAccess` does not exist anymore.

**Comment by himpierre** [comment]
Thanks for your answer @havfo. Could you please a little bit more specific. I'm looking at the example config for quite a while now. :-)

**Comment by havfo** [comment]
Sorry about that, I was on my phone. You need to set up a `userMapping` function, look at the examples. In the `userMapping` you need to add some sort of `userRole` to the `peer` object, again look at the examples.

Further you need to set up `accessFromRoles`, and especially, set `[BYPASS_LOBBY]` to contain the `userRole` you granted the `peer` in `userMapping`. As an example, if you did:
```
peer.addRole(userRoles.AUTHENTICATED);
```
in the `userMapping`, set:
```
[BYPASS_LOBBY]     : [ userRoles.AUTHENTICATED ]
```
in `accessFromRoles`. Then only the peers with the `AUTHENTICATED` role will be able to enter from the lobby.

**Comment by himpierre** [comment]
Now i'm starting to understand. Let's see how far I come. :-)

**Comment by misi** [comment]
@havfo I think  we need to add to documentation more info about the auth concept..

**Comment by himpierre** [comment]
Redirect to Keycloak and back is working now. Thank you.
