### ISSUE TITLE
Keycloak in infinite loop in authentication. 

### ISSUE THREAD

**Issue by chinthakadeshapriya** [havfo/multiparty-meeting#428]
I can successfully get direct to Key cloak authentication and it successfully get the username and password and comes to a infinite loop and browser prompts ERR_TOO_MANY_REDIRECTS.  My Keycloak server ruining in docker behind Nginx SSL proxy.  In search of google I have found the same issue with several users with different application. One of the the for your reference: https://stackoverflow.com/questions/54989160/openshift-keycloak-4-8-3-login-to-admin-console-infinite-redirect-loop.

Some people doubt about it has a session cache issue with Redis

Thanks in advance for your valuable time on our issues !!!

**Comment by chinthakadeshapriya** [comment]
One more REF: https://stackoverflow.com/questions/56681972/infinite-loop-after-logging-in-with-keycloak-behind-a-reverse-proxy

**Comment by misi** [comment]
We rertry in case of error and this cause the loop i guess, 
so find the error with your keycloak and nginx setup and it should work.

**Comment by misi** [comment]
Or try to use HA proxy we have example in the repository.

**Comment by chinthakadeshapriya** [comment]
Thanks, now I am able to get login via keycloak.

I have also created two client roles "moderator & meetingadmin" and enabled the following user mapping function. Still I can not access the meeting after having successfully login to Key cloak user

userMapping : async ({ peer, roomId, userinfo }) =>
        {
                if (
                        Array.isArray(userinfo.roles) &&
                        userinfo.roles.includes('moderator')
                )
                {
                        peer.addRole(userRoles.MODERATOR);
                }

                if (
                        Array.isArray(userinfo.roles) &&
                        userinfo.roles.includes('meetingadmin')
                )
                {
                        peer.addRole(userRoles.ADMIN);
                }

                peer.addRole(userRoles.AUTHENTICATED);
        },
