### ISSUE TITLE
Up to date aspect ratio - 16:9 video

### ISSUE THREAD

**Issue by erykes** [havfo/multiparty-meeting#439]
The system is running for a while and does a great job! It uses many up to date technologies and offers more and more features. But for us, who do a lot with video production, it is totally not understandable why the old fashioned and obsolete 4:3 picture format is still present.

I would like to kindly ask you - please change the video aspect ratio to 16:9. Everyone has now 16:9 (or 16:10) displays. All media production is done in 16:9. Live events are based on 16:9 picture-in-picture video frames. It also loos a lot more professional. 

I'm aware that some users have old PC cameras and even in new laptops there are 4:3 cameras installed but this is only a little % of all. Fitting this image into a 16:9 frame involves cutting top and bottom part (now the system is removing left and right side for 4:3 conversion...).

**Comment by Astagor** [comment]
It could be configurable, switching between 4:3 and 16:9 (16:9 should be default). this issue is also killing me. As, if I have a presentation or video playout using a video capture device, I have the right and left cut off.

**Comment by Astagor** [comment]
I will test today! Thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by havfo** [comment]
My primary monitor is 21 : 9, so I might use something else too :smile:

**Comment by Alex-YddeR** [comment]
When 2 Participants are there i cannot change back to 4:3 from 16:9

**Comment by havfo** [comment]
There is a "bug" at the moment. When you are at a screen size where the sizes won't change, it won't rerender. Just do an action that will cause a rerender (e.g. resize) and it will change aspect.

**Comment by havfo** [comment]
Will of course fix this.

**Comment by Astagor** [comment]
One more thing, if you open a participant video in a new window, the window is 4:3.
