### ISSUE TITLE
use rtsp ip camera

### ISSUE THREAD

**Issue by volkankoc** [havfo/multiparty-meeting#440]
hi 
i want to use ip camera how can i do 
thank u

**Comment by Astagor** [comment]
Have a look at [https://obsproject.com/](url)
There you have a lot of plugins.
You would need to configure a video source, that would be your IP camera. Then add a plugin to display OBS out as a web cam in the system, and then in multiparty-meeting choose OBS as the webcam.

**Comment by volkankoc** [comment]
thank u
