### ISSUE TITLE
 Where do I change the config.js file

### ISSUE THREAD

**Issue by volkankoc** [havfo/multiparty-meeting#443]
Where do I change the config.js file. I found the following lines in config.js at. mm github(for docker)

// URI and key for requesting geoip-based TURN server closest to the client
	turnAPIKey    : 'examplekey',
	turnAPIURI    : 'https://example.com/api/turn',
	turnAPIparams : {
		'uri_schema' 	: 'turn',
		'transport' 		: 'tcp',
		'ip_ver'    		: 'ipv4',
		'servercount'	: '2'
	},

	// Backup turnservers if REST fails or is not configured
	backupTurnServers : [
		{
			urls : [
				'turn:turn.example.com:443?transport=tcp'
			],
			username   : 'example',
			credential : 'example'
		}
	],`
`

**Comment by cap19** [comment]
Here https://github.com/havfo/multiparty-meeting/tree/master/app/public/config AND

here https://github.com/havfo/multiparty-meeting/tree/master/server/config
