### ISSUE TITLE
Mic does not re-init after reconnect

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#446]
Scenario to reproduce:
2 users in room
 - 1 user on mobile using wifi, Chrome
 - 1 user on desktop, Chrome

Both sides can here and see each other.

Now, I turn WiFi off on the mobile, the phone switches to LTE, the connection drops for a moment, but then the user reconnects to the room automatically (returning user). The video re-inits well, but the mic does not. I have to go into settings and change the audio device for mic to make it work again.

**Comment by so010** [comment]
Test again with last develop!
I think last fix for https://github.com/havfo/multiparty-meeting/issues/444 resolved this too.

**Comment by Astagor** [comment]
Yes it did!
