### ISSUE TITLE
android client can't connect to this

### ISSUE THREAD

**Issue by ghostsf** [havfo/multiparty-meeting#453]
android client can't connect to `https://letsmeet.no`
show error log:

`D/WebSocketTransport: <-- HTTP FAILED: java.io.IOException: unexpected end of stream on https://letsmeet.no`

**Comment by havfo** [comment]
To be able to help we need to know Android version, browser type/version, network type.

**Comment by iQuick** [comment]
@havfo 
use : https://github.com/haiyangwu/mediasoup-demo-android
android version : v8.1.0

**Comment by havfo** [comment]
Why do you assume that a totally unrelated project should be able to connect to https://letsmeet.no ?

**Comment by iQuick** [comment]
Both of these are based on webrtc and I want to know how to modify it to connect me to https://letsmeet.no . 
Did multiparty-meeting modify the protocol address?

**Comment by havfo** [comment]
This project is now fundamentally incompatible with the mediasoup-demo project. The biggest difference is that this project uses socket.io, not protoo.js for signaling.

**Comment by iQuick** [comment]
Yes, I saw it, but the java version of socket.io does not support wss.
I can use protoo.js to connect to https://letsmeet.no ?

**Comment by havfo** [comment]
That is not possible, they are not compatible. You would have to either rewrite multiparty-meeting to use protoo, or implement socket.io support in java.

**Comment by ghostsf** [comment]
Ok, i got it. Thank you very much !
