### ISSUE TITLE
Pass unauthenticated user Display Name using URL. ex.: letsmeet.no/test?name=myself

### ISSUE THREAD

**Issue by flaviostutz** [havfo/multiparty-meeting#458]
I thought about integrating letsmeet.no rooms to our website for communicating with our users that needs some kind of support.

The room name will be the user id (so that the room is private), but today the user will have to type his/hers name during room entry. 

As the user is already authenticated in our website, I could send the person name to the URL directly. Something like "http://letsmeet.no/user-anthony?name=Anthony Evans"

What do you think?

**Comment by havfo** [comment]
Have you tried sending `https://x.x?displayName=example`? 😉

**Comment by flaviostutz** [comment]
I had tested ?name= with no sucess. Now I testes with displayName and it works! Thanks!

**Comment by flaviostutz** [comment]
Where can I find any documentation on those query parameters?
