### ISSUE TITLE
Control panel

### ISSUE THREAD

**Issue by so010** [havfo/multiparty-meeting#46]
Independent  real time control panel for each room for use for moderators or from admin side

- participant list:
  - Change  moderator role / admin role
  - Kickout
  - Mute all or arbitrary participants
- Room : 
  - Lock/unlock 
(  - set pin)
  - LastN
  - Default Layout
  - Raise Hand
(  - Delete)
(  - Save )

**Comment by misi** [comment]
We need to split this issue to smaller issues. Some are already done.

**Comment by havfo** [comment]
This issue is no longer relevant, if something is missing, lets add new issues
