### ISSUE TITLE
40000-49999/udp/tcp i have allowed this port as udp but video and voice not showing

### ISSUE THREAD

**Issue by rootSectornet** [havfo/multiparty-meeting#460]
40000-49999/udp/tcp i have allowed this port as udp but video and voice not showing

  _multiparty-meeting-server:ERROR:Room TypeError: Cannot read property 'user' of undefined
  multiparty-meeting-server:ERROR:Room     at Room._handleSocketRequest (/var/www/html/multiparty-meeting/server/lib/Room.js:430:49)
  multiparty-meeting-server:ERROR:Room     at Socket.<anonymous> (/var/www/html/multiparty-meeting/server/lib/Room.js:349:9)
  multiparty-meeting-server:ERROR:Room     at Socket.emit (events.js:203:13)
  multiparty-meeting-server:ERROR:Room     at Socket.EventEmitter.emit (domain.js:471:20)
  multiparty-meeting-server:ERROR:Room     at /var/www/html/multiparty-meeting/server/node_modules/socket.io/lib/socket.js:528:12
  multiparty-meeting-server:ERROR:Room     at processTicksAndRejections (internal/process/task_queues.js:75:11) +8s
  mediasoup:Transport consume() +471ms_

**Comment by aravindgp** [comment]
> 40000-49999/udp/tcp i have allowed this port as udp but video and voice not showing
> 
> _multiparty-meeting-server:ERROR:Room TypeError: Cannot read property 'user' of undefined
> multiparty-meeting-server:ERROR:Room at Room._handleSocketRequest (/var/www/html/multiparty-meeting/server/lib/Room.js:430:49) multiparty-meeting-server:ERROR:Room at Socket. (/var/www/html/multiparty-meeting/server/lib/Room.js:349:9) multiparty-meeting-server:ERROR:Room at Socket.emit (events.js:203:13) multiparty-meeting-server:ERROR:Room at Socket.EventEmitter.emit (domain.js:471:20) multiparty-meeting-server:ERROR:Room at /var/www/html/multiparty-meeting/server/node_modules/socket.io/lib/socket.js:528:12 multiparty-meeting-server:ERROR:Room at processTicksAndRejections (internal/process/task_queues.js:75:11) +8s mediasoup:Transport consume() +471ms_

How did u resolve this issue
