### ISSUE TITLE
Virtual Background Plugin

### ISSUE THREAD

**Issue by Alex-YddeR** [havfo/multiparty-meeting#464]
Can we use below chrome plugin for virtual background. it works with google meet

https://github.com/Coderantine/VirtualBackgroundsForWeb

https://chrome.google.com/webstore/detail/virtual-backgrounds-for-g/ghlkgnalbbkgpdlodjlackgjehofahoc

Thanks

**Comment by havfo** [comment]
I just tried it, and it works for the video, but it screws up audio. You need to change the two instances of `meet.google.com` in `manifest.json` to whatever your multiparty-meeting fqdn is and build it. Enable dev mode in Chrome and install local extension.

**Comment by Alex-YddeR** [comment]
Yes. it screws up audio part. may be some changes needed in plugin, i dont know. anyways it will be good if we have virtual background as a feature.

**Comment by havfo** [comment]
Duplicate https://github.com/havfo/multiparty-meeting/issues/213
