### ISSUE TITLE
Start and exit page

### ISSUE THREAD

**Issue by so010** [havfo/multiparty-meeting#47]
Something to display on start without room name in URL.

Exit page showing after pressing exit button could be the same as start page?
Optionally with "go back to your old room" or last visited rooms view ...

**Comment by havfo** [comment]
We now have a start page.

**Comment by misi** [comment]
@so010 It is done? Am I correct? Can we close this issue?

**Comment by so010** [comment]
Exit page still does not exist.

**Comment by misi** [comment]
Ok I just thought it is the same as the start! (-; Sorry..
>Exit page showing after pressing exit button could be the same as start page?

**Comment by so010** [comment]
Closing this and opening issue for exit page:
https://github.com/havfo/multiparty-meeting/issues/121
