### ISSUE TITLE
voiceActivityMute in app config is not used

### ISSUE THREAD

**Issue by misi** [havfo/multiparty-meeting#480]
voiceActivityMute
https://github.com/havfo/multiparty-meeting/blob/511a7de25b5c9226c7f90046a5f7c7e120449a83/app/public/config/config.example.js#L97

**Comment by so010** [comment]
resolved 
https://github.com/havfo/multiparty-meeting/commit/0ad219d98f74ed2f57f55a64c24515e26f0a4f08
