### ISSUE TITLE
Only Creat and Join Meeting Pages Are getting Loaded

### ISSUE THREAD

**Issue by harivyas35** [havfo/multiparty-meeting#486]
HI,
I have created a secure tunnul so that i could access this app from outside network , but only first two pages of choosing room and joining meeting are the pages which are rendered , after clicking on joining (both audio or audio/video ) the further page is not getting loaded .

Regards,
Hari Vyas

**Comment by misi** [comment]
Check websocket connection and developer console. It is not a general issue with multiparty meeting. For such support goto community list and try to get help there.
