### ISSUE TITLE
Will self signed certificates work in production 

### ISSUE THREAD

**Issue by harivyas35** [havfo/multiparty-meeting#488]
Hi, 
I have deployed this app using a third party deployment platform. 
Actually first two pages gets loaded but nothing after that. I guess it is because I am using self signed SSL certificates .I am not able to figure out how to get valid TLS certificates,  can any one guide me about it .

Regards,
Hari vyas

**Comment by Astagor** [comment]
Self signed will maybe work for testing, if you add them to trusted in the browsers you will use for all clients. For production, don't do it. You can get free certificates from https://letsencrypt.org/
How to get them depends on your server setup. What OS, direct MM or Apache/Nginx proxy.
