### ISSUE TITLE
How to get a valid TLS Certificate 

### ISSUE THREAD

**Issue by harivyas35** [havfo/multiparty-meeting#489]
HI ,
Can anyone tell me me how to get a valid TLS certificate , (not self signed one )

Regards,
Hari Vyas

**Comment by bianxg** [comment]
I update certificate to server/certs and modify server/config/config.js with my certificate name.
I start app using npm start method. 
$cd app
$npm start
But browser show the certificate is still localhost. How to set the certificate that app use?

**Comment by bianxg** [comment]
I can join room using localhost browser, but can not join room from another comuputer. It(browser debug console) show invalid certificate.

**Comment by harivyas35** [comment]
@bianxg have you deployed your code to prodution

**Comment by bianxg** [comment]
After modify productionPort in app/public/config/config.js as same as  listeningPort in server/config/config.js (I use 5443) and deploy, It works now. Thanks.

**Comment by misi** [comment]
@harivyas35 See https://letsencrypt.org/ to see how to get a cert it is not strongly related to multiparty-meeting
