### ISSUE TITLE
Configure as progressive web app

### ISSUE THREAD

**Issue by torjusti** [havfo/multiparty-meeting#52]
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app

- Add a manifest file and related configuration, so that the app can be added to phone homescreens
- Service workers to improve loading speed, regardless of if the page is installed as an app or not

**Comment by torjusti** [comment]
See #53

**Comment by havfo** [comment]
Fixed in 0449d6ff
