### ISSUE TITLE
webpack

### ISSUE THREAD

**Issue by torjusti** [havfo/multiparty-meeting#68]
If we want #67 without a massive increase to the bundle size, it seems to me that the most reasonable way to go ahead is to make the feature opt-in by a switch in the settings. Then, we can dynamically load the module when enabling the feature in the client.

However, I don't know how the support for code splitting is in Gulp. I think it's a bit easier to do in wbepack using modules such as [react-loadable](https://github.com/jamiebuilds/react-loadable), so this issue is basically for discussing whether we would want to consider moving to webpack or not. I think moving to something like `create-react-app` would be nice, however there is no support for Stylus in CRA. Writing a custom webpack configuration is certainly viable, though.

Is this something to consider?

**Comment by torjusti** [comment]
There is apparently also [factor-bundle](https://github.com/browserify/factor-bundle) for browserify

**Comment by havfo** [comment]
Fixed in 0449d6ff
