### ISSUE TITLE
gulp dist error

### ISSUE THREAD

**Issue by quickstreamingmedia** [havfo/multiparty-meeting#69]
[20:30:14] Plumber found unhandled error:
 GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: keyword (const)
File: /root/multiparty-meeting/app/multiparty-meeting.js

please check and let me know solution

**Comment by xxxman2008** [comment]
OK , same error too. when i  run "gulp dist" in  app  dir.

**Comment by misi** [comment]
See branch eper..

**Comment by xxxman2008** [comment]
ok , i resolved the problem by switch to branch develop .. thanks for the reply .

**Comment by havfo** [comment]
Working on merging the fixes in the eper branch into the develop branch.

**Comment by havfo** [comment]
This is fixed by commit f941c574f22941e3bd02e1edd018c2b4b83bb08a
