### ISSUE TITLE
Failed to construct 'RTCPeerConnection'

### ISSUE THREAD

**Issue by xxxman2008** [havfo/multiparty-meeting#71]
Hi, 
   I  have an very strange Error when i set the project on my own server.
   First,  My server is  debian 8 .  nodejs 8.11  and  npm 6.4  ,
   I have install the  all depends by webtorrent-hybrid.  use following commond
  " apt-get install libgtk2.0-0 libxtst-dev libxss-dev libgconf2-dev libnss3 libasound2-dev xvfb"

  I  cloned the git branch "develop",And  following your guid ,npm install everything.  It seems everything is OK .. 
  also  ,i changed the  cert file to my  let's encrypt  wild cert.
  But ,when I open the URL  https://xxx.mydomain.club/  , always get error message : 
   "Failed to initialize native PeerConnection"
  
 Also  ,because i'm using  chrome ,so  i try to add "https://webrtc.github.io/adapter/adapter-latest.js" .
but no lucky . It's still  same error.

I have attach the console log for your referrence.

Any help will be appreciate.

Raymond

BTW:   I've also try these steps on  other  "clean"  VHost . But ...you  known the result.
 
[noname.zssp.club-1540042472958.log](https://github.com/havfo/multiparty-meeting/files/2498184/noname.zssp.club-1540042472958.log)

**Comment by xxxman2008** [comment]
Here is my  config.js  under  "server"
--------------------------------------------------------------
module.exports =
{
	// oAuth2 conf
	oauth2 :
	{
		clientID  			: 'wrongid',
		clientSecret	: 'wrongid',
		callbackURL 	: 'https://noname.zssp.club:3443/auth-callback'
	},
	// Listening hostname for `gulp live|open`.
	domain : 'localhost',
	tls    :
	{
		cert : `${__dirname}/certs/fullchain1.pem`,
		key  : `${__dirname}/certs/privkey1.pem`
	},
	// Listening port for https server.
	listeningPort : 3443,
	turnServers     : [
		{
			urls : [
				'turn:stream.912586.com:3478?transport=tcp'
			],
			username   : '',
			credential : ''
		}
	],
	mediasoup :
	{
		// mediasoup Server settings.
		logLevel : 'warn',
		logTags  :
		[
			'info',
			'ice',
			'dtls',
			'rtp',
			'srtp',
			'rtcp',
			'rbe',
			'rtx'
		],
		rtcIPv4          : true,
		rtcIPv6          : true,
		rtcAnnouncedIPv4 : null,
		rtcAnnouncedIPv6 : null,
		rtcMinPort       : 40000,
		rtcMaxPort       : 49999,
		// mediasoup Room codecs.
		mediaCodecs      :
		[
			{
				kind       : 'audio',
				name       : 'opus',
				clockRate  : 48000,
				channels   : 2,
				parameters :
				{
					useinbandfec : 1
				}
			},
			{
				kind      : 'video',
				name      : 'VP8',
				clockRate : 90000
			}
			// {
			// 	kind       : 'video',
			// 	name       : 'H264',
			// 	clockRate  : 90000,
			// 	parameters :
			// 	{
			// 		'packetization-mode' : 1
			// 	}
			// }
		],
		// mediasoup per Peer max sending bitrate (in bps).
		maxBitrate : 4096000
	}
};
-------------------------------------------------------------------

**Comment by havfo** [comment]
I have updated a lot of dependencies in both client and server. Can you pull the latest changes from the develop branch, and run npm install in both the app/ and server/ folders, and then run gulp dist again?

**Comment by havfo** [comment]
Also, you shouldn't have to use adapter.js.

**Comment by havfo** [comment]
I have just tried installing from scratch following the guide, and it worked without a problem. The mediasoup media-server is initialized in [mediasoup.js](https://github.com/havfo/multiparty-meeting/blob/2b8947e0c1583f9c3bd6a2a91be00303a3fccb8c/server/mediasoup.js#L9).

Are you running this behind some proxy, or are you exposing it directly?
