### ISSUE TITLE
No communication between clients

### ISSUE THREAD

**Issue by kkar** [havfo/multiparty-meeting#80]
Hello, it seems I am unable to successfully setup the app. Although the app and the server are deployed with success, none of the clients, nor me with my local tests can receive audio or video from another client. Please, I need someone to even have access to my root server and help me find out why, or suggest me a way of getting any logs that can guide me through the process.

I am trying to make it work for over 15 days now and due to I didn't have any previous experience with webrtc, it's more than difficult to debug the installation.

ANY help would be appreciated.

**Comment by misi** [comment]
Have you tried the docker image? May it is easier.
https://github.com/misi/mm

**Comment by kkar** [comment]
@misi thank you. I should try to run docker but, will it be a deployed installation? I mean, is it ready for production or should i make any further actions?

**Comment by kkar** [comment]
@havfo you are awesome. Changing that and giving a new try in a moment. I will keep you informed.

**Comment by kkar** [comment]
```
root@h2782615:~# cd multiparty-meeting/
root@h2782615:~/multiparty-meeting# cd server/
root@h2782615:~/multiparty-meeting/server# nano config.js
```

Contents of config.js at rtcIPv4 line:
`rtcIPv4          : "85.214.103.72",`

```
root@h2782615:~/multiparty-meeting/server# npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 7076 packages in 9.44s
found 0 vulnerabilities



   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │       New minor version of npm available! 6.5.0 → 6.7.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.7.0   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯

root@h2782615:~/multiparty-meeting/server# cd ..
root@h2782615:~/multiparty-meeting# cp multiparty-meeting.service /etc/systemd/system/
root@h2782615:~/multiparty-meeting# nano /etc/systemd/system/multiparty-meeting.service
root@h2782615:~/multiparty-meeting# pwd
/root/multiparty-meeting
root@h2782615:~/multiparty-meeting# nano /etc/systemd/system/multiparty-meeting.service
```

Content of multiparty-meeting.service:
```
[Unit]
Description=multiparty-meeting is a audio / video meeting service running in the browser and powered by webRTC
After=network.target

[Service]
ExecStart=/root/multiparty-meeting/server/server.js
Restart=always
User=root
Group=root
Environment=PATH=/usr/bin:/usr/local/bin
Environment=NODE_ENV=production
WorkingDirectory=/root/multiparty-meeting/server
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```

```
root@h2782615:~/multiparty-meeting# systemctl daemon-reload
root@h2782615:~/multiparty-meeting# systemctl start multiparty-meeting
root@h2782615:~/multiparty-meeting#
```

But as I can see, the same thing happens...

**Comment by kkar** [comment]
@havfo may I send you my root login details if you have a minute or two to help me?

**Comment by havfo** [comment]
@kkar Before we try that, try also setting the rtcAnnouncedIPv4 to the same address. Is this a public facing host, or is this some mapped address?

**Comment by kkar** [comment]
Done that as suggested, and rebuilded & restarted the service...

**Comment by misi** [comment]
> @misi thank you. I should try to run docker but, will it be a deployed installation? I mean, is it ready for production or should i make any further actions?
@kkar Yes it is the same source code as you can find in the devel branch. 
Automagically created after every commit.

I suggested because may it is faster/simplier to deploy for you.

**Comment by havfo** [comment]
I also suggest using the docker image, should be better.

**Comment by kkar** [comment]
Should I completely remove the manual installation before trying the docker image? Please, can we leave the "issue" open for further assistance if needed?

**Comment by havfo** [comment]
As long as the services are not running, you don't need to remove anything. Yes, we can leave it open.
