### ISSUE TITLE
Update server to http2

### ISSUE THREAD

**Issue by havfo** [havfo/multiparty-meeting#85]
Update Express to use http2.

**Comment by misi** [comment]
See #95

**Comment by misi** [comment]
Notice: I just realized that spdy cause an issue in with latest nodejs! 
There is a deadlock until express5 will come out and we can move to official http2.
See:
https://github.com/tamasszoke/mern-boilerplate/issues/1#issuecomment-483208472

**Comment by so010** [comment]
This should be solved now.

**Comment by misi** [comment]
Still issue with actual node version.
Fix is comming:
- https://github.com/spdy-http2/handle-thing/issues/6#issuecomment-587397067
- https://github.com/spdy-http2/handle-thing/pull/13

**Comment by misi** [comment]
It seems  

-  spdy-http2/handle-thing#6 (comment)
-  spdy-http2/handle-thing#13
fix is merged so we need to check with newer node version how it behaves..

**Comment by misi** [comment]
I will close it. I updated mm docker file the master to lts node and the dev to nodejs13.
