### ISSUE TITLE
/server/public is missing

### ISSUE THREAD

**Issue by misi** [havfo/multiparty-meeting#88]
2.0 is broken due this error.
There is two way to fix:

1. Create an empty dir with a placeholder file. Empty dir not allowed in git

2. change script 
```
-react-scripts build && rm -rf ../server/public/* && cp -r build/* ../server/public/
+react-scripts build && rm -rf ../server/public && cp -r build ../server/public
```
Which one do you prefer? I don't want to bug you too much: I will do the change. 
I am just wondering which one  should I pick..

**Comment by misi** [comment]
I have added the dir and a placeholder  file as a temp solution.

**Comment by misi** [comment]
@havfo  Should I close this issue? 
I didn't get any feedback..
Do you agree with my temp solution?

**Comment by havfo** [comment]
Yes, that solution is fine.
