### ISSUE TITLE
Option for selecting alternative audio output

### ISSUE THREAD

**Issue by lagebj** [havfo/multiparty-meeting#94]
Is it possible to add an option for selecting an alternative audio output? Or maybe have the audio select to the standard communication device by default?

**Comment by havfo** [comment]
The API for changing audio sink is not fully supported on Firefox and is unsupported on Safari at the moment: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId#Browser_compatibility

**Comment by lagebj** [comment]
I see, can we expect this to be implemented if/when Firefox and Safari adds support for it?

**Comment by so010** [comment]
Yes

**Comment by misi** [comment]
It is in feat-output-select

**Comment by misi** [comment]
It is merged to develop. Will be rolled out in 3.3.
