### ISSUE TITLE
Picture not set in participant list after rehidrate

### ISSUE THREAD

**Issue by misi** [havfo/multiparty-meeting#96]
In participant list picture is not set if it get from the local store, or page is reloaded after login.
Any hint would be great.

**Comment by misi** [comment]
My guess changeProfilePicture is not called after persist local store rehydrate.

**Comment by so010** [comment]
It is working for me for URL picture. Is your picture a URL or local file?

**Comment by misi** [comment]
url

**Comment by so010** [comment]
Try on letsmeet.no!

**Comment by misi** [comment]
Underway..

**Comment by misi** [comment]
Unfortunately my IdP not giving out jpegPhoto attribute to your SP. So I can't test it.. :(

**Comment by misi** [comment]
Can we discuss it live?

**Comment by so010** [comment]
Wrote a privat email to you ...

**Comment by misi** [comment]
I made a working fix.
See:  [fix/picture-participantlist](https://github.com/havfo/multiparty-meeting/tree/fix/picture-participantlist)
BUT
I am not fully happy with the fix because I had to add a delay.  
Without delay the result was fuzzy. (Sometimes worked sometimes not.) 

Please review and help me how to fix it more correctly. 
Many Thanks in advance!

**Comment by havfo** [comment]
Fixed in 0aa0aa08b0e5b18b765b7c284773b4eea9859c39 and a763d37879426c9003a3af5462e82ac649d0cf76
